//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.05 at 07:41:07 PM IST 
//


package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}exchangeID"/>
 *         &lt;element name="citizenshipVerification" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}verificationType" minOccurs="0"/>
 *         &lt;element name="lawfulPresenceVerification" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}verificationType" minOccurs="0"/>
 *         &lt;element name="selfAttestedDateOfEntry" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="fedHubDateOfEntry" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="eligibilityStatementCd" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}eligibilityStatementCodes" minOccurs="0"/>
 *         &lt;element name="fedHubLawfulPresenceVerfCd" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}verfCodes" minOccurs="0"/>
 *         &lt;element name="qualifiedNonCitizenCd" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}verfCodes" minOccurs="0"/>
 *         &lt;element name="fedHubFiveYrBarApplyVerfCd" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}fedVerfCodes" minOccurs="0"/>
 *         &lt;element name="fedHubFiveYrBarMetVerfCd" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}fedVerfCodes" minOccurs="0"/>
 *         &lt;element ref="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}currentINS" minOccurs="0"/>
 *         &lt;element name="classOfAdmissionCd" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}classOfAdmissionCodes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "exchangeID",
    "citizenshipVerification",
    "lawfulPresenceVerification",
    "selfAttestedDateOfEntry",
    "fedHubDateOfEntry",
    "eligibilityStatementCd",
    "fedHubLawfulPresenceVerfCd",
    "qualifiedNonCitizenCd",
    "fedHubFiveYrBarApplyVerfCd",
    "fedHubFiveYrBarMetVerfCd",
    "currentINS",
    "classOfAdmissionCd"
})
@XmlRootElement(name = "citizenship", namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema")
public class Citizenship {

    @XmlElement(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema")
    @XmlSchemaType(name = "integer")
    protected long exchangeID;
    protected VerificationType citizenshipVerification;
    protected VerificationType lawfulPresenceVerification;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar selfAttestedDateOfEntry;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fedHubDateOfEntry;
    protected String eligibilityStatementCd;
    @XmlSchemaType(name = "string")
    protected VerfCodes fedHubLawfulPresenceVerfCd;
    @XmlSchemaType(name = "string")
    protected VerfCodes qualifiedNonCitizenCd;
    @XmlSchemaType(name = "string")
    protected FedVerfCodes fedHubFiveYrBarApplyVerfCd;
    @XmlSchemaType(name = "string")
    protected FedVerfCodes fedHubFiveYrBarMetVerfCd;
    @XmlElement(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema")
    protected CurrentINS currentINS;
    protected String classOfAdmissionCd;

    /**
     * Gets the value of the exchangeID property.
     * 
     */
    public long getExchangeID() {
        return exchangeID;
    }

    /**
     * Sets the value of the exchangeID property.
     * 
     */
    public void setExchangeID(long value) {
        this.exchangeID = value;
    }

    /**
     * Gets the value of the citizenshipVerification property.
     * 
     * @return
     *     possible object is
     *     {@link VerificationType }
     *     
     */
    public VerificationType getCitizenshipVerification() {
        return citizenshipVerification;
    }

    /**
     * Sets the value of the citizenshipVerification property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerificationType }
     *     
     */
    public void setCitizenshipVerification(VerificationType value) {
        this.citizenshipVerification = value;
    }

    /**
     * Gets the value of the lawfulPresenceVerification property.
     * 
     * @return
     *     possible object is
     *     {@link VerificationType }
     *     
     */
    public VerificationType getLawfulPresenceVerification() {
        return lawfulPresenceVerification;
    }

    /**
     * Sets the value of the lawfulPresenceVerification property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerificationType }
     *     
     */
    public void setLawfulPresenceVerification(VerificationType value) {
        this.lawfulPresenceVerification = value;
    }

    /**
     * Gets the value of the selfAttestedDateOfEntry property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSelfAttestedDateOfEntry() {
        return selfAttestedDateOfEntry;
    }

    /**
     * Sets the value of the selfAttestedDateOfEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSelfAttestedDateOfEntry(XMLGregorianCalendar value) {
        this.selfAttestedDateOfEntry = value;
    }

    /**
     * Gets the value of the fedHubDateOfEntry property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFedHubDateOfEntry() {
        return fedHubDateOfEntry;
    }

    /**
     * Sets the value of the fedHubDateOfEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFedHubDateOfEntry(XMLGregorianCalendar value) {
        this.fedHubDateOfEntry = value;
    }

    /**
     * Gets the value of the eligibilityStatementCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibilityStatementCd() {
        return eligibilityStatementCd;
    }

    /**
     * Sets the value of the eligibilityStatementCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibilityStatementCd(String value) {
        this.eligibilityStatementCd = value;
    }

    /**
     * Gets the value of the fedHubLawfulPresenceVerfCd property.
     * 
     * @return
     *     possible object is
     *     {@link VerfCodes }
     *     
     */
    public VerfCodes getFedHubLawfulPresenceVerfCd() {
        return fedHubLawfulPresenceVerfCd;
    }

    /**
     * Sets the value of the fedHubLawfulPresenceVerfCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerfCodes }
     *     
     */
    public void setFedHubLawfulPresenceVerfCd(VerfCodes value) {
        this.fedHubLawfulPresenceVerfCd = value;
    }

    /**
     * Gets the value of the qualifiedNonCitizenCd property.
     * 
     * @return
     *     possible object is
     *     {@link VerfCodes }
     *     
     */
    public VerfCodes getQualifiedNonCitizenCd() {
        return qualifiedNonCitizenCd;
    }

    /**
     * Sets the value of the qualifiedNonCitizenCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerfCodes }
     *     
     */
    public void setQualifiedNonCitizenCd(VerfCodes value) {
        this.qualifiedNonCitizenCd = value;
    }

    /**
     * Gets the value of the fedHubFiveYrBarApplyVerfCd property.
     * 
     * @return
     *     possible object is
     *     {@link FedVerfCodes }
     *     
     */
    public FedVerfCodes getFedHubFiveYrBarApplyVerfCd() {
        return fedHubFiveYrBarApplyVerfCd;
    }

    /**
     * Sets the value of the fedHubFiveYrBarApplyVerfCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link FedVerfCodes }
     *     
     */
    public void setFedHubFiveYrBarApplyVerfCd(FedVerfCodes value) {
        this.fedHubFiveYrBarApplyVerfCd = value;
    }

    /**
     * Gets the value of the fedHubFiveYrBarMetVerfCd property.
     * 
     * @return
     *     possible object is
     *     {@link FedVerfCodes }
     *     
     */
    public FedVerfCodes getFedHubFiveYrBarMetVerfCd() {
        return fedHubFiveYrBarMetVerfCd;
    }

    /**
     * Sets the value of the fedHubFiveYrBarMetVerfCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link FedVerfCodes }
     *     
     */
    public void setFedHubFiveYrBarMetVerfCd(FedVerfCodes value) {
        this.fedHubFiveYrBarMetVerfCd = value;
    }

    /**
     * Gets the value of the currentINS property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentINS }
     *     
     */
    public CurrentINS getCurrentINS() {
        return currentINS;
    }

    /**
     * Sets the value of the currentINS property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentINS }
     *     
     */
    public void setCurrentINS(CurrentINS value) {
        this.currentINS = value;
    }

    /**
     * Gets the value of the classOfAdmissionCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassOfAdmissionCd() {
        return classOfAdmissionCd;
    }

    /**
     * Sets the value of the classOfAdmissionCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassOfAdmissionCd(String value) {
        this.classOfAdmissionCd = value;
    }

}
