//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.05 at 07:41:07 PM IST 
//


package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for entity_eligibilityreasonInstanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entity_eligibilityreasonInstanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="out_text_eligibility_denial_reason_code" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}textAttributeType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entity_eligibilityreasonInstanceType", namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", propOrder = {

})
public class EntityEligibilityreasonInstanceType {

    @XmlElement(name = "out_text_eligibility_denial_reason_code")
    protected TextAttributeType outTextEligibilityDenialReasonCode;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the outTextEligibilityDenialReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link TextAttributeType }
     *     
     */
    public TextAttributeType getOutTextEligibilityDenialReasonCode() {
        return outTextEligibilityDenialReasonCode;
    }

    /**
     * Sets the value of the outTextEligibilityDenialReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextAttributeType }
     *     
     */
    public void setOutTextEligibilityDenialReasonCode(TextAttributeType value) {
        this.outTextEligibilityDenialReasonCode = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
