//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.05 at 07:41:07 PM IST 
//


package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for entity_eligibilityperiodEntityListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entity_eligibilityperiodEntityListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entity_eligibilityperiod" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}entity_eligibilityperiodInstanceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="properties" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}ListCustomPropertiesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="inferred" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entity_eligibilityperiodEntityListType", namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", propOrder = {
    "entityEligibilityperiod",
    "properties"
})
public class EntityEligibilityperiodEntityListType {

    @XmlElement(name = "entity_eligibilityperiod")
    protected List<EntityEligibilityperiodInstanceType> entityEligibilityperiod;
    protected ListCustomPropertiesType properties;
    @XmlAttribute(name = "inferred")
    protected Boolean inferred;

    /**
     * Gets the value of the entityEligibilityperiod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entityEligibilityperiod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntityEligibilityperiod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityEligibilityperiodInstanceType }
     * 
     * 
     */
    public List<EntityEligibilityperiodInstanceType> getEntityEligibilityperiod() {
        if (entityEligibilityperiod == null) {
            entityEligibilityperiod = new ArrayList<EntityEligibilityperiodInstanceType>();
        }
        return this.entityEligibilityperiod;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link ListCustomPropertiesType }
     *     
     */
    public ListCustomPropertiesType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListCustomPropertiesType }
     *     
     */
    public void setProperties(ListCustomPropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the inferred property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInferred() {
        return inferred;
    }

    /**
     * Sets the value of the inferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInferred(Boolean value) {
        this.inferred = value;
    }

}
