//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.05 at 07:41:07 PM IST 
//


package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.service;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for incomeTypeCodes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="incomeTypeCodes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ALI"/>
 *     &lt;enumeration value="ANN"/>
 *     &lt;enumeration value="CAP"/>
 *     &lt;enumeration value="DIV"/>
 *     &lt;enumeration value="DVI"/>
 *     &lt;enumeration value="EAI"/>
 *     &lt;enumeration value="EDF"/>
 *     &lt;enumeration value="EQU"/>
 *     &lt;enumeration value="FAR"/>
 *     &lt;enumeration value="FEI"/>
 *     &lt;enumeration value="FPC"/>
 *     &lt;enumeration value="FTI"/>
 *     &lt;enumeration value="IMA"/>
 *     &lt;enumeration value="INT"/>
 *     &lt;enumeration value="IRA"/>
 *     &lt;enumeration value="ISS"/>
 *     &lt;enumeration value="MBI"/>
 *     &lt;enumeration value="OTH"/>
 *     &lt;enumeration value="REN"/>
 *     &lt;enumeration value="RNI"/>
 *     &lt;enumeration value="ROY"/>
 *     &lt;enumeration value="RRI"/>
 *     &lt;enumeration value="RRR"/>
 *     &lt;enumeration value="SEI"/>
 *     &lt;enumeration value="SSA"/>
 *     &lt;enumeration value="SSI"/>
 *     &lt;enumeration value="SSS"/>
 *     &lt;enumeration value="TRB"/>
 *     &lt;enumeration value="TRU"/>
 *     &lt;enumeration value="UNI"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "incomeTypeCodes", namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema")
@XmlEnum
public enum IncomeTypeCodes {

    ALI,
    ANN,
    CAP,
    DIV,
    DVI,
    EAI,
    EDF,
    EQU,
    FAR,
    FEI,
    FPC,
    FTI,
    IMA,
    INT,
    IRA,
    ISS,
    MBI,
    OTH,
    REN,
    RNI,
    ROY,
    RRI,
    RRR,
    SEI,
    SSA,
    SSI,
    SSS,
    TRB,
    TRU,
    UNI;

    public String value() {
        return name();
    }

    public static IncomeTypeCodes fromValue(String v) {
        return valueOf(v);
    }

}
