//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.05 at 07:41:07 PM IST 
//


package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.service;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}exchangeID"/>
 *         &lt;element name="incomeTypeCd" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}incomeTypeCodes"/>
 *         &lt;element name="incomeAmt" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}negativeAmountType"/>
 *         &lt;element ref="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}frequencyCd"/>
 *         &lt;element name="lumpSumReceivedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="incomeStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="incomeEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "exchangeID",
    "incomeTypeCd",
    "incomeAmt",
    "frequencyCd",
    "lumpSumReceivedDate",
    "incomeStartDate",
    "incomeEndDate"
})
@XmlRootElement(name = "income", namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema")
public class Income {

    @XmlElement(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema")
    @XmlSchemaType(name = "integer")
    protected long exchangeID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected IncomeTypeCodes incomeTypeCd;
    @XmlElement(required = true)
    protected BigDecimal incomeAmt;
    @XmlElement(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", required = true)
    @XmlSchemaType(name = "string")
    protected FrequencyCodes frequencyCd;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lumpSumReceivedDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar incomeStartDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar incomeEndDate;

    /**
     * Gets the value of the exchangeID property.
     * 
     */
    public long getExchangeID() {
        return exchangeID;
    }

    /**
     * Sets the value of the exchangeID property.
     * 
     */
    public void setExchangeID(long value) {
        this.exchangeID = value;
    }

    /**
     * Gets the value of the incomeTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link IncomeTypeCodes }
     *     
     */
    public IncomeTypeCodes getIncomeTypeCd() {
        return incomeTypeCd;
    }

    /**
     * Sets the value of the incomeTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncomeTypeCodes }
     *     
     */
    public void setIncomeTypeCd(IncomeTypeCodes value) {
        this.incomeTypeCd = value;
    }

    /**
     * Gets the value of the incomeAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeAmt() {
        return incomeAmt;
    }

    /**
     * Sets the value of the incomeAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeAmt(BigDecimal value) {
        this.incomeAmt = value;
    }

    /**
     * Gets the value of the frequencyCd property.
     * 
     * @return
     *     possible object is
     *     {@link FrequencyCodes }
     *     
     */
    public FrequencyCodes getFrequencyCd() {
        return frequencyCd;
    }

    /**
     * Sets the value of the frequencyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequencyCodes }
     *     
     */
    public void setFrequencyCd(FrequencyCodes value) {
        this.frequencyCd = value;
    }

    /**
     * Gets the value of the lumpSumReceivedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLumpSumReceivedDate() {
        return lumpSumReceivedDate;
    }

    /**
     * Sets the value of the lumpSumReceivedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLumpSumReceivedDate(XMLGregorianCalendar value) {
        this.lumpSumReceivedDate = value;
    }

    /**
     * Gets the value of the incomeStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIncomeStartDate() {
        return incomeStartDate;
    }

    /**
     * Sets the value of the incomeStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIncomeStartDate(XMLGregorianCalendar value) {
        this.incomeStartDate = value;
    }

    /**
     * Gets the value of the incomeEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIncomeEndDate() {
        return incomeEndDate;
    }

    /**
     * Sets the value of the incomeEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIncomeEndDate(XMLGregorianCalendar value) {
        this.incomeEndDate = value;
    }

}
