//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.05 at 07:41:07 PM IST 
//


package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.service;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for langCodes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="langCodes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ARM"/>
 *     &lt;enumeration value="ALB"/>
 *     &lt;enumeration value="AMH"/>
 *     &lt;enumeration value="ARA"/>
 *     &lt;enumeration value="BIK"/>
 *     &lt;enumeration value="BUL"/>
 *     &lt;enumeration value="BEN"/>
 *     &lt;enumeration value="BRX"/>
 *     &lt;enumeration value="BUR"/>
 *     &lt;enumeration value="CAX"/>
 *     &lt;enumeration value="CEB"/>
 *     &lt;enumeration value="CCX"/>
 *     &lt;enumeration value="CHI"/>
 *     &lt;enumeration value="CMX"/>
 *     &lt;enumeration value="CHA"/>
 *     &lt;enumeration value="CZE"/>
 *     &lt;enumeration value="PRS"/>
 *     &lt;enumeration value="DAN"/>
 *     &lt;enumeration value="DUT"/>
 *     &lt;enumeration value="ENG"/>
 *     &lt;enumeration value="FAX"/>
 *     &lt;enumeration value="CPF"/>
 *     &lt;enumeration value="FIN"/>
 *     &lt;enumeration value="FIJ"/>
 *     &lt;enumeration value="FRE"/>
 *     &lt;enumeration value="GER"/>
 *     &lt;enumeration value="GUJ"/>
 *     &lt;enumeration value="GRE"/>
 *     &lt;enumeration value="HAT"/>
 *     &lt;enumeration value="HEB"/>
 *     &lt;enumeration value="HIN"/>
 *     &lt;enumeration value="HAK"/>
 *     &lt;enumeration value="HMN"/>
 *     &lt;enumeration value="HUN"/>
 *     &lt;enumeration value="IBO"/>
 *     &lt;enumeration value="ILO"/>
 *     &lt;enumeration value="IND"/>
 *     &lt;enumeration value="HIL"/>
 *     &lt;enumeration value="ITA"/>
 *     &lt;enumeration value="JPN"/>
 *     &lt;enumeration value="KJG"/>
 *     &lt;enumeration value="KOR"/>
 *     &lt;enumeration value="KIK"/>
 *     &lt;enumeration value="LOA"/>
 *     &lt;enumeration value="LPX"/>
 *     &lt;enumeration value="MAC"/>
 *     &lt;enumeration value="MIX"/>
 *     &lt;enumeration value="MAY"/>
 *     &lt;enumeration value="MAL"/>
 *     &lt;enumeration value="MAR"/>
 *     &lt;enumeration value="NOR"/>
 *     &lt;enumeration value="ORM"/>
 *     &lt;enumeration value="OTX"/>
 *     &lt;enumeration value="PUS"/>
 *     &lt;enumeration value="PER"/>
 *     &lt;enumeration value="POR"/>
 *     &lt;enumeration value="PAN"/>
 *     &lt;enumeration value="POL"/>
 *     &lt;enumeration value="PUX"/>
 *     &lt;enumeration value="QUE"/>
 *     &lt;enumeration value="RUM"/>
 *     &lt;enumeration value="RUS"/>
 *     &lt;enumeration value="SMO"/>
 *     &lt;enumeration value="SAL"/>
 *     &lt;enumeration value="SWA"/>
 *     &lt;enumeration value="SGN"/>
 *     &lt;enumeration value="SOM"/>
 *     &lt;enumeration value="SNA"/>
 *     &lt;enumeration value="SPA"/>
 *     &lt;enumeration value="SLO"/>
 *     &lt;enumeration value="SWE"/>
 *     &lt;enumeration value="TGL"/>
 *     &lt;enumeration value="TIB"/>
 *     &lt;enumeration value="THA"/>
 *     &lt;enumeration value="TIR"/>
 *     &lt;enumeration value="TUR"/>
 *     &lt;enumeration value="TAM"/>
 *     &lt;enumeration value="TNX"/>
 *     &lt;enumeration value="CHK"/>
 *     &lt;enumeration value="UKR"/>
 *     &lt;enumeration value="URD"/>
 *     &lt;enumeration value="VIE"/>
 *     &lt;enumeration value="VSX"/>
 *     &lt;enumeration value="YAX"/>
 *     &lt;enumeration value="YID"/>
 *     &lt;enumeration value="YOR"/>
 *     &lt;enumeration value="ZUL"/>
 *     &lt;enumeration value="SRP"/>
 *     &lt;enumeration value="SUN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "langCodes", namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema")
@XmlEnum
public enum LangCodes {

    ARM,
    ALB,
    AMH,
    ARA,
    BIK,
    BUL,
    BEN,
    BRX,
    BUR,
    CAX,
    CEB,
    CCX,
    CHI,
    CMX,
    CHA,
    CZE,
    PRS,
    DAN,
    DUT,
    ENG,
    FAX,
    CPF,
    FIN,
    FIJ,
    FRE,
    GER,
    GUJ,
    GRE,
    HAT,
    HEB,
    HIN,
    HAK,
    HMN,
    HUN,
    IBO,
    ILO,
    IND,
    HIL,
    ITA,
    JPN,
    KJG,
    KOR,
    KIK,
    LOA,
    LPX,
    MAC,
    MIX,
    MAY,
    MAL,
    MAR,
    NOR,
    ORM,
    OTX,
    PUS,
    PER,
    POR,
    PAN,
    POL,
    PUX,
    QUE,
    RUM,
    RUS,
    SMO,
    SAL,
    SWA,
    SGN,
    SOM,
    SNA,
    SPA,
    SLO,
    SWE,
    TGL,
    TIB,
    THA,
    TIR,
    TUR,
    TAM,
    TNX,
    CHK,
    UKR,
    URD,
    VIE,
    VSX,
    YAX,
    YID,
    YOR,
    ZUL,
    SRP,
    SUN;

    public String value() {
        return name();
    }

    public static LangCodes fromValue(String v) {
        return valueOf(v);
    }

}
