//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.05 at 07:41:07 PM IST 
//


package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.service;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eligStatusCd" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}eligStatusCodes"/>
 *         &lt;element ref="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}reasonCd" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="certStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="certEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="eligBeginDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="eligEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="eligDeterminationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="medicalCoverageGroupCd" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}medicalCoverageGroupCodes" minOccurs="0"/>
 *         &lt;element name="chipPremiumAmt" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}amountType" minOccurs="0"/>
 *         &lt;element name="householdMemberExchangeID" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}exchangeIDType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eligStatusCd",
    "reasonCd",
    "certStartDate",
    "certEndDate",
    "eligBeginDate",
    "eligEndDate",
    "eligDeterminationDate",
    "medicalCoverageGroupCd",
    "chipPremiumAmt",
    "householdMemberExchangeID"
})
@XmlRootElement(name = "magiEligibility", namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema")
public class MagiEligibility {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected EligStatusCodes eligStatusCd;
    @XmlElement(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema")
    protected List<String> reasonCd;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar certStartDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar certEndDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eligBeginDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eligEndDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eligDeterminationDate;
    @XmlSchemaType(name = "string")
    protected MedicalCoverageGroupCodes medicalCoverageGroupCd;
    protected BigDecimal chipPremiumAmt;
    @XmlElement(type = Long.class)
    @XmlSchemaType(name = "integer")
    protected List<Long> householdMemberExchangeID;

    /**
     * Gets the value of the eligStatusCd property.
     * 
     * @return
     *     possible object is
     *     {@link EligStatusCodes }
     *     
     */
    public EligStatusCodes getEligStatusCd() {
        return eligStatusCd;
    }

    /**
     * Sets the value of the eligStatusCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link EligStatusCodes }
     *     
     */
    public void setEligStatusCd(EligStatusCodes value) {
        this.eligStatusCd = value;
    }

    /**
     * Gets the value of the reasonCd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reasonCd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReasonCd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getReasonCd() {
        if (reasonCd == null) {
            reasonCd = new ArrayList<String>();
        }
        return this.reasonCd;
    }

    /**
     * Gets the value of the certStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCertStartDate() {
        return certStartDate;
    }

    /**
     * Sets the value of the certStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCertStartDate(XMLGregorianCalendar value) {
        this.certStartDate = value;
    }

    /**
     * Gets the value of the certEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCertEndDate() {
        return certEndDate;
    }

    /**
     * Sets the value of the certEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCertEndDate(XMLGregorianCalendar value) {
        this.certEndDate = value;
    }

    /**
     * Gets the value of the eligBeginDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEligBeginDate() {
        return eligBeginDate;
    }

    /**
     * Sets the value of the eligBeginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEligBeginDate(XMLGregorianCalendar value) {
        this.eligBeginDate = value;
    }

    /**
     * Gets the value of the eligEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEligEndDate() {
        return eligEndDate;
    }

    /**
     * Sets the value of the eligEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEligEndDate(XMLGregorianCalendar value) {
        this.eligEndDate = value;
    }

    /**
     * Gets the value of the eligDeterminationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEligDeterminationDate() {
        return eligDeterminationDate;
    }

    /**
     * Sets the value of the eligDeterminationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEligDeterminationDate(XMLGregorianCalendar value) {
        this.eligDeterminationDate = value;
    }

    /**
     * Gets the value of the medicalCoverageGroupCd property.
     * 
     * @return
     *     possible object is
     *     {@link MedicalCoverageGroupCodes }
     *     
     */
    public MedicalCoverageGroupCodes getMedicalCoverageGroupCd() {
        return medicalCoverageGroupCd;
    }

    /**
     * Sets the value of the medicalCoverageGroupCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedicalCoverageGroupCodes }
     *     
     */
    public void setMedicalCoverageGroupCd(MedicalCoverageGroupCodes value) {
        this.medicalCoverageGroupCd = value;
    }

    /**
     * Gets the value of the chipPremiumAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChipPremiumAmt() {
        return chipPremiumAmt;
    }

    /**
     * Sets the value of the chipPremiumAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChipPremiumAmt(BigDecimal value) {
        this.chipPremiumAmt = value;
    }

    /**
     * Gets the value of the householdMemberExchangeID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the householdMemberExchangeID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHouseholdMemberExchangeID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getHouseholdMemberExchangeID() {
        if (householdMemberExchangeID == null) {
            householdMemberExchangeID = new ArrayList<Long>();
        }
        return this.householdMemberExchangeID;
    }

}
