//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.05 at 07:41:07 PM IST 
//


package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for memberEligibilityDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="memberEligibilityDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="benefitType" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}benefitTypeCodes"/>
 *         &lt;element name="eligStatusCd" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}medicalCoverageGroupCodes" minOccurs="0"/>
 *         &lt;element name="csrCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eligibilityStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="eligibilityEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="benefitSource" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}benefitSourceCodes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "memberEligibilityDetails", namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", propOrder = {
    "benefitType",
    "eligStatusCd",
    "csrCategory",
    "eligibilityStartDate",
    "eligibilityEndDate",
    "benefitSource"
})
public class MemberEligibilityDetails {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected BenefitTypeCodes benefitType;
    @XmlSchemaType(name = "string")
    protected MedicalCoverageGroupCodes eligStatusCd;
    protected String csrCategory;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eligibilityStartDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eligibilityEndDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected BenefitSourceCodes benefitSource;

    /**
     * Gets the value of the benefitType property.
     * 
     * @return
     *     possible object is
     *     {@link BenefitTypeCodes }
     *     
     */
    public BenefitTypeCodes getBenefitType() {
        return benefitType;
    }

    /**
     * Sets the value of the benefitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BenefitTypeCodes }
     *     
     */
    public void setBenefitType(BenefitTypeCodes value) {
        this.benefitType = value;
    }

    /**
     * Gets the value of the eligStatusCd property.
     * 
     * @return
     *     possible object is
     *     {@link MedicalCoverageGroupCodes }
     *     
     */
    public MedicalCoverageGroupCodes getEligStatusCd() {
        return eligStatusCd;
    }

    /**
     * Sets the value of the eligStatusCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedicalCoverageGroupCodes }
     *     
     */
    public void setEligStatusCd(MedicalCoverageGroupCodes value) {
        this.eligStatusCd = value;
    }

    /**
     * Gets the value of the csrCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsrCategory() {
        return csrCategory;
    }

    /**
     * Sets the value of the csrCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsrCategory(String value) {
        this.csrCategory = value;
    }

    /**
     * Gets the value of the eligibilityStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEligibilityStartDate() {
        return eligibilityStartDate;
    }

    /**
     * Sets the value of the eligibilityStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEligibilityStartDate(XMLGregorianCalendar value) {
        this.eligibilityStartDate = value;
    }

    /**
     * Gets the value of the eligibilityEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEligibilityEndDate() {
        return eligibilityEndDate;
    }

    /**
     * Sets the value of the eligibilityEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEligibilityEndDate(XMLGregorianCalendar value) {
        this.eligibilityEndDate = value;
    }

    /**
     * Gets the value of the benefitSource property.
     * 
     * @return
     *     possible object is
     *     {@link BenefitSourceCodes }
     *     
     */
    public BenefitSourceCodes getBenefitSource() {
        return benefitSource;
    }

    /**
     * Sets the value of the benefitSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link BenefitSourceCodes }
     *     
     */
    public void setBenefitSource(BenefitSourceCodes value) {
        this.benefitSource = value;
    }

}
