//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.05 at 07:41:07 PM IST
//


package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.deloitteinnovation.us.hbx.edbc.eligibility.driver.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FrequencyCd_QNAME = new QName("http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", "frequencyCd");
    private final static QName _PhysicalApplicationID_QNAME = new QName("http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", "physicalApplicationID");
    private final static QName _ReasonCd_QNAME = new QName("http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", "reasonCd");
    private final static QName _PrimaryExchangeID_QNAME = new QName("http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", "primaryExchangeID");
    private final static QName _ApplicationID_QNAME = new QName("http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", "applicationID");
    private final static QName _DependentExchangeID_QNAME = new QName("http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", "dependentExchangeID");
    private final static QName _AcesClientID_QNAME = new QName("http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", "acesClientID");
    private final static QName _ExchangeID_QNAME = new QName("http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", "exchangeID");
    private final static QName _ApplicationMode_QNAME = new QName("http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", "applicationMode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.deloitteinnovation.us.hbx.edbc.eligibility.driver.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Member }
     * 
     */
    public Member createMember() {
        return new Member();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link QdpResults }
     * 
     */
    public QdpResults createQdpResults() {
        return new QdpResults();
    }

    /**
     * Create an instance of {@link BooleanChangePoint }
     * 
     */
    public BooleanChangePoint createBooleanChangePoint() {
        return new BooleanChangePoint();
    }

    /**
     * Create an instance of {@link NumberAttributeType }
     * 
     */
    public NumberAttributeType createNumberAttributeType() {
        return new NumberAttributeType();
    }

    /**
     * Create an instance of {@link Residency }
     * 
     */
    public Residency createResidency() {
        return new Residency();
    }

    /**
     * Create an instance of {@link ApplicationMember }
     * 
     */
    public ApplicationMember createApplicationMember() {
        return new ApplicationMember();
    }

    /**
     * Create an instance of {@link BooleanDataType }
     * 
     */
    public BooleanDataType createBooleanDataType() {
        return new BooleanDataType();
    }

    /**
     * Create an instance of {@link ApplicationResponse }
     * 
     */
    public ApplicationResponse createApplicationResponse() {
        return new ApplicationResponse();
    }

    /**
     * Create an instance of {@link EntityEligibilityperiodEntityListType }
     * 
     */
    public EntityEligibilityperiodEntityListType createEntityEligibilityperiodEntityListType() {
        return new EntityEligibilityperiodEntityListType();
    }

    /**
     * Create an instance of {@link DatetimeAttributeType }
     * 
     */
    public DatetimeAttributeType createDatetimeAttributeType() {
        return new DatetimeAttributeType();
    }

    /**
     * Create an instance of {@link EntityEligibilityreasonInstanceType }
     * 
     */
    public EntityEligibilityreasonInstanceType createEntityEligibilityreasonInstanceType() {
        return new EntityEligibilityreasonInstanceType();
    }

    /**
     * Create an instance of {@link VerificationType }
     * 
     */
    public VerificationType createVerificationType() {
        return new VerificationType();
    }

    /**
     * Create an instance of {@link TextAttributeType }
     * 
     */
    public TextAttributeType createTextAttributeType() {
        return new TextAttributeType();
    }

    /**
     * Create an instance of {@link MagiBenefitMonth }
     * 
     */
    public MagiBenefitMonth createMagiBenefitMonth() {
        return new MagiBenefitMonth();
    }

    /**
     * Create an instance of {@link DateAttributeType }
     * 
     */
    public DateAttributeType createDateAttributeType() {
        return new DateAttributeType();
    }

    /**
     * Create an instance of {@link CustomPropertyType }
     * 
     */
    public CustomPropertyType createCustomPropertyType() {
        return new CustomPropertyType();
    }

    /**
     * Create an instance of {@link Referral }
     * 
     */
    public Referral createReferral() {
        return new Referral();
    }

    /**
     * Create an instance of {@link Facility }
     * 
     */
    public Facility createFacility() {
        return new Facility();
    }

    /**
     * Create an instance of {@link TimeChangePoint }
     * 
     */
    public TimeChangePoint createTimeChangePoint() {
        return new TimeChangePoint();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link UncertainValue }
     * 
     */
    public UncertainValue createUncertainValue() {
        return new UncertainValue();
    }

    /**
     * Create an instance of {@link FormerFosterCareDetail }
     * 
     */
    public FormerFosterCareDetail createFormerFosterCareDetail() {
        return new FormerFosterCareDetail();
    }

    /**
     * Create an instance of {@link Tribal }
     * 
     */
    public Tribal createTribal() {
        return new Tribal();
    }

    /**
     * Create an instance of {@link RelationshipTargetType }
     * 
     */
    public RelationshipTargetType createRelationshipTargetType() {
        return new RelationshipTargetType();
    }

    /**
     * Create an instance of {@link SsnDetails }
     * 
     */
    public SsnDetails createSsnDetails() {
        return new SsnDetails();
    }

    /**
     * Create an instance of {@link Income }
     * 
     */
    public Income createIncome() {
        return new Income();
    }

    /**
     * Create an instance of {@link MagiFinancialComp }
     * 
     */
    public MagiFinancialComp createMagiFinancialComp() {
        return new MagiFinancialComp();
    }

    /**
     * Create an instance of {@link ThirdPartyLiability }
     * 
     */
    public ThirdPartyLiability createThirdPartyLiability() {
        return new ThirdPartyLiability();
    }

    /**
     * Create an instance of {@link Pregnancy }
     * 
     */
    public Pregnancy createPregnancy() {
        return new Pregnancy();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link MagiEligibility }
     * 
     */
    public MagiEligibility createMagiEligibility() {
        return new MagiEligibility();
    }

    /**
     * Create an instance of {@link ListCustomPropertiesType }
     * 
     */
    public ListCustomPropertiesType createListCustomPropertiesType() {
        return new ListCustomPropertiesType();
    }

    /**
     * Create an instance of {@link NumberDataType }
     * 
     */
    public NumberDataType createNumberDataType() {
        return new NumberDataType();
    }

    /**
     * Create an instance of {@link DatetimeDataType }
     * 
     */
    public DatetimeDataType createDatetimeDataType() {
        return new DatetimeDataType();
    }

    /**
     * Create an instance of {@link AuthRep }
     * 
     */
    public AuthRep createAuthRep() {
        return new AuthRep();
    }

    /**
     * Create an instance of {@link EsiCoverageDetails }
     * 
     */
    public EsiCoverageDetails createEsiCoverageDetails() {
        return new EsiCoverageDetails();
    }

    /**
     * Create an instance of {@link RulebaseEventType.Parameters }
     * 
     */
    public RulebaseEventType.Parameters createRulebaseEventTypeParameters() {
        return new RulebaseEventType.Parameters();
    }

    /**
     * Create an instance of {@link Relationship }
     * 
     */
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link BooleanAttributeType }
     * 
     */
    public BooleanAttributeType createBooleanAttributeType() {
        return new BooleanAttributeType();
    }

    /**
     * Create an instance of {@link CurrentINS }
     * 
     */
    public CurrentINS createCurrentINS() {
        return new CurrentINS();
    }

    /**
     * Create an instance of {@link ApplicationRequest }
     * 
     */
    public ApplicationRequest createApplicationRequest() {
        return new ApplicationRequest();
    }

    /**
     * Create an instance of {@link ApplicationMemberIDs }
     * 
     */
    public ApplicationMemberIDs createApplicationMemberIDs() {
        return new ApplicationMemberIDs();
    }

    /**
     * Create an instance of {@link DatetimeChangePoint }
     * 
     */
    public DatetimeChangePoint createDatetimeChangePoint() {
        return new DatetimeChangePoint();
    }

    /**
     * Create an instance of {@link NumberChangePoint }
     * 
     */
    public NumberChangePoint createNumberChangePoint() {
        return new NumberChangePoint();
    }

    /**
     * Create an instance of {@link MemberEligibilityDetails }
     * 
     */
    public MemberEligibilityDetails createMemberEligibilityDetails() {
        return new MemberEligibilityDetails();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link AlreadyProvenNodeType }
     * 
     */
    public AlreadyProvenNodeType createAlreadyProvenNodeType() {
        return new AlreadyProvenNodeType();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AptcFinancialComp }
     * 
     */
    public AptcFinancialComp createAptcFinancialComp() {
        return new AptcFinancialComp();
    }

    /**
     * Create an instance of {@link TimeDataType }
     * 
     */
    public TimeDataType createTimeDataType() {
        return new TimeDataType();
    }

    /**
     * Create an instance of {@link TextChangePoint }
     * 
     */
    public TextChangePoint createTextChangePoint() {
        return new TextChangePoint();
    }

    /**
     * Create an instance of {@link EntityIndividualEntityListType }
     * 
     */
    public EntityIndividualEntityListType createEntityIndividualEntityListType() {
        return new EntityIndividualEntityListType();
    }

    /**
     * Create an instance of {@link DateChangePoint }
     * 
     */
    public DateChangePoint createDateChangePoint() {
        return new DateChangePoint();
    }

    /**
     * Create an instance of {@link EntityEligibilityreasonEntityListType }
     * 
     */
    public EntityEligibilityreasonEntityListType createEntityEligibilityreasonEntityListType() {
        return new EntityEligibilityreasonEntityListType();
    }

    /**
     * Create an instance of {@link AttributeNodeType.ChangePoint }
     * 
     */
    public AttributeNodeType.ChangePoint createAttributeNodeTypeChangePoint() {
        return new AttributeNodeType.ChangePoint();
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link CoverageRequest }
     * 
     */
    public CoverageRequest createCoverageRequest() {
        return new CoverageRequest();
    }

    /**
     * Create an instance of {@link QhpResults }
     * 
     */
    public QhpResults createQhpResults() {
        return new QhpResults();
    }

    /**
     * Create an instance of {@link MagiResults }
     * 
     */
    public MagiResults createMagiResults() {
        return new MagiResults();
    }

    /**
     * Create an instance of {@link TimeAttributeType }
     * 
     */
    public TimeAttributeType createTimeAttributeType() {
        return new TimeAttributeType();
    }

    /**
     * Create an instance of {@link Taxfiler }
     * 
     */
    public Taxfiler createTaxfiler() {
        return new Taxfiler();
    }

    /**
     * Create an instance of {@link AttributeNodeType }
     * 
     */
    public AttributeNodeType createAttributeNodeType() {
        return new AttributeNodeType();
    }

    /**
     * Create an instance of {@link RelationshipNodeType }
     * 
     */
    public RelationshipNodeType createRelationshipNodeType() {
        return new RelationshipNodeType();
    }

    /**
     * Create an instance of {@link EntityEligibilityperiodInstanceType }
     * 
     */
    public EntityEligibilityperiodInstanceType createEntityEligibilityperiodInstanceType() {
        return new EntityEligibilityperiodInstanceType();
    }

    /**
     * Create an instance of {@link ListEventsType }
     * 
     */
    public ListEventsType createListEventsType() {
        return new ListEventsType();
    }

    /**
     * Create an instance of {@link MagiFinancialComp.IncomeResult }
     * 
     */
    public MagiFinancialComp.IncomeResult createMagiFinancialCompIncomeResult() {
        return new MagiFinancialComp.IncomeResult();
    }

    /**
     * Create an instance of {@link DateDataType }
     * 
     */
    public DateDataType createDateDataType() {
        return new DateDataType();
    }

    /**
     * Create an instance of {@link OutcomeType }
     * 
     */
    public OutcomeType createOutcomeType() {
        return new OutcomeType();
    }

    /**
     * Create an instance of {@link Deduction }
     * 
     */
    public Deduction createDeduction() {
        return new Deduction();
    }

    /**
     * Create an instance of {@link LifeEventChange }
     * 
     */
    public LifeEventChange createLifeEventChange() {
        return new LifeEventChange();
    }

    /**
     * Create an instance of {@link Citizenship }
     * 
     */
    public Citizenship createCitizenship() {
        return new Citizenship();
    }

    /**
     * Create an instance of {@link Race }
     * 
     */
    public Race createRace() {
        return new Race();
    }

    /**
     * Create an instance of {@link UnknownValue }
     * 
     */
    public UnknownValue createUnknownValue() {
        return new UnknownValue();
    }

    /**
     * Create an instance of {@link DecisionReportType }
     * 
     */
    public DecisionReportType createDecisionReportType() {
        return new DecisionReportType();
    }

    /**
     * Create an instance of {@link Equifax }
     * 
     */
    public Equifax createEquifax() {
        return new Equifax();
    }

    /**
     * Create an instance of {@link TextDataType }
     * 
     */
    public TextDataType createTextDataType() {
        return new TextDataType();
    }

    /**
     * Create an instance of {@link EntityIndividualInstanceType }
     * 
     */
    public EntityIndividualInstanceType createEntityIndividualInstanceType() {
        return new EntityIndividualInstanceType();
    }

    /**
     * Create an instance of {@link TaxMember }
     * 
     */
    public TaxMember createTaxMember() {
        return new TaxMember();
    }

    /**
     * Create an instance of {@link AptcResults }
     * 
     */
    public AptcResults createAptcResults() {
        return new AptcResults();
    }

    /**
     * Create an instance of {@link RulebaseEventType }
     * 
     */
    public RulebaseEventType createRulebaseEventType() {
        return new RulebaseEventType();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link TaxFilingStatus }
     * 
     */
    public TaxFilingStatus createTaxFilingStatus() {
        return new TaxFilingStatus();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FrequencyCodes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", name = "frequencyCd")
    public JAXBElement<FrequencyCodes> createFrequencyCd(FrequencyCodes value) {
        return new JAXBElement<FrequencyCodes>(_FrequencyCd_QNAME, FrequencyCodes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", name = "physicalApplicationID")
    public JAXBElement<Long> createPhysicalApplicationID(Long value) {
        return new JAXBElement<Long>(_PhysicalApplicationID_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", name = "reasonCd")
    public JAXBElement<String> createReasonCd(String value) {
        return new JAXBElement<String>(_ReasonCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", name = "primaryExchangeID")
    public JAXBElement<Long> createPrimaryExchangeID(Long value) {
        return new JAXBElement<Long>(_PrimaryExchangeID_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", name = "applicationID")
    public JAXBElement<Long> createApplicationID(Long value) {
        return new JAXBElement<Long>(_ApplicationID_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", name = "dependentExchangeID")
    public JAXBElement<Long> createDependentExchangeID(Long value) {
        return new JAXBElement<Long>(_DependentExchangeID_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", name = "acesClientID")
    public JAXBElement<Long> createAcesClientID(Long value) {
        return new JAXBElement<Long>(_AcesClientID_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", name = "exchangeID")
    public JAXBElement<Long> createExchangeID(Long value) {
        return new JAXBElement<Long>(_ExchangeID_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationModes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", name = "applicationMode")
    public JAXBElement<ApplicationModes> createApplicationMode(ApplicationModes value) {
        return new JAXBElement<ApplicationModes>(_ApplicationMode_QNAME, ApplicationModes.class, null, value);
    }

}
