//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.05 at 07:41:07 PM IST 
//


package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.service;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for requestTypeCodes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="requestTypeCodes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MA"/>
 *     &lt;enumeration value="APTC"/>
 *     &lt;enumeration value="MAWD"/>
 *     &lt;enumeration value="TCWD"/>
 *     &lt;enumeration value="QHDP"/>
 *     &lt;enumeration value="QHP"/>
 *     &lt;enumeration value="QDP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "requestTypeCodes", namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema")
@XmlEnum
public enum RequestTypeCodes {

    MA,
    APTC,
    MAWD,
    TCWD,
    QHDP,
    QHP,
    QDP;

    public String value() {
        return name();
    }

    public static RequestTypeCodes fromValue(String v) {
        return valueOf(v);
    }

}
