//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.05 at 07:41:07 PM IST 
//


package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="taxFilingStsLastYr" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}taxFilingStatusCodes"/>
 *         &lt;element name="taxFilingStsThisYr" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}taxFilingStatusCodes" minOccurs="0"/>
 *         &lt;element name="taxFilingStsNextYr" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}taxFilingStatusCodes" minOccurs="0"/>
 *         &lt;element name="taxFilingComplianceInd" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}yesOrNoCodes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "taxFilingStsLastYr",
    "taxFilingStsThisYr",
    "taxFilingStsNextYr",
    "taxFilingComplianceInd"
})
@XmlRootElement(name = "taxFilingStatus", namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema")
public class TaxFilingStatus {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TaxFilingStatusCodes taxFilingStsLastYr;
    @XmlSchemaType(name = "string")
    protected TaxFilingStatusCodes taxFilingStsThisYr;
    @XmlSchemaType(name = "string")
    protected TaxFilingStatusCodes taxFilingStsNextYr;
    @XmlSchemaType(name = "string")
    protected YesOrNoCodes taxFilingComplianceInd;

    /**
     * Gets the value of the taxFilingStsLastYr property.
     * 
     * @return
     *     possible object is
     *     {@link TaxFilingStatusCodes }
     *     
     */
    public TaxFilingStatusCodes getTaxFilingStsLastYr() {
        return taxFilingStsLastYr;
    }

    /**
     * Sets the value of the taxFilingStsLastYr property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxFilingStatusCodes }
     *     
     */
    public void setTaxFilingStsLastYr(TaxFilingStatusCodes value) {
        this.taxFilingStsLastYr = value;
    }

    /**
     * Gets the value of the taxFilingStsThisYr property.
     * 
     * @return
     *     possible object is
     *     {@link TaxFilingStatusCodes }
     *     
     */
    public TaxFilingStatusCodes getTaxFilingStsThisYr() {
        return taxFilingStsThisYr;
    }

    /**
     * Sets the value of the taxFilingStsThisYr property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxFilingStatusCodes }
     *     
     */
    public void setTaxFilingStsThisYr(TaxFilingStatusCodes value) {
        this.taxFilingStsThisYr = value;
    }

    /**
     * Gets the value of the taxFilingStsNextYr property.
     * 
     * @return
     *     possible object is
     *     {@link TaxFilingStatusCodes }
     *     
     */
    public TaxFilingStatusCodes getTaxFilingStsNextYr() {
        return taxFilingStsNextYr;
    }

    /**
     * Sets the value of the taxFilingStsNextYr property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxFilingStatusCodes }
     *     
     */
    public void setTaxFilingStsNextYr(TaxFilingStatusCodes value) {
        this.taxFilingStsNextYr = value;
    }

    /**
     * Gets the value of the taxFilingComplianceInd property.
     * 
     * @return
     *     possible object is
     *     {@link YesOrNoCodes }
     *     
     */
    public YesOrNoCodes getTaxFilingComplianceInd() {
        return taxFilingComplianceInd;
    }

    /**
     * Sets the value of the taxFilingComplianceInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesOrNoCodes }
     *     
     */
    public void setTaxFilingComplianceInd(YesOrNoCodes value) {
        this.taxFilingComplianceInd = value;
    }

}
