//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.05 at 07:41:07 PM IST 
//


package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for verificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="verificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="selfAttestedInd" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}yesOrNoCodes"/>
 *         &lt;element name="fedHubInd" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}yesOrNoCodes" minOccurs="0"/>
 *         &lt;element name="verificationStatus" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}verificationStatusCodes" minOccurs="0"/>
 *         &lt;element name="verificationSource" type="{http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema}verificationSourceCodes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "verificationType", namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxeligibilityservice/schema", propOrder = {
    "selfAttestedInd",
    "fedHubInd",
    "verificationStatus",
    "verificationSource"
})
public class VerificationType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected YesOrNoCodes selfAttestedInd;
    @XmlSchemaType(name = "string")
    protected YesOrNoCodes fedHubInd;
    @XmlSchemaType(name = "string")
    protected VerificationStatusCodes verificationStatus;
    @XmlSchemaType(name = "string")
    protected VerificationSourceCodes verificationSource;

    /**
     * Gets the value of the selfAttestedInd property.
     * 
     * @return
     *     possible object is
     *     {@link YesOrNoCodes }
     *     
     */
    public YesOrNoCodes getSelfAttestedInd() {
        return selfAttestedInd;
    }

    /**
     * Sets the value of the selfAttestedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesOrNoCodes }
     *     
     */
    public void setSelfAttestedInd(YesOrNoCodes value) {
        this.selfAttestedInd = value;
    }

    /**
     * Gets the value of the fedHubInd property.
     * 
     * @return
     *     possible object is
     *     {@link YesOrNoCodes }
     *     
     */
    public YesOrNoCodes getFedHubInd() {
        return fedHubInd;
    }

    /**
     * Sets the value of the fedHubInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesOrNoCodes }
     *     
     */
    public void setFedHubInd(YesOrNoCodes value) {
        this.fedHubInd = value;
    }

    /**
     * Gets the value of the verificationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link VerificationStatusCodes }
     *     
     */
    public VerificationStatusCodes getVerificationStatus() {
        return verificationStatus;
    }

    /**
     * Sets the value of the verificationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerificationStatusCodes }
     *     
     */
    public void setVerificationStatus(VerificationStatusCodes value) {
        this.verificationStatus = value;
    }

    /**
     * Gets the value of the verificationSource property.
     * 
     * @return
     *     possible object is
     *     {@link VerificationSourceCodes }
     *     
     */
    public VerificationSourceCodes getVerificationSource() {
        return verificationSource;
    }

    /**
     * Sets the value of the verificationSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerificationSourceCodes }
     *     
     */
    public void setVerificationSource(VerificationSourceCodes value) {
        this.verificationSource = value;
    }

}
