package com.deloitteinnovation.us.hbx.shopping.shoppingflowrestriction.businessrules.constants;

public enum QualifyingLifeEvent {


    DOMESTIC_VIOLENCE("DOMESTIC_VIOLENCE"),
    EXCEPTIONAL("EXCEPTIONAL"),
    QHP_DECERTIFICATION("QHP_DECERTIFICATION"),
    EXCHANGE_ERROR("EXCHANGE_ERROR"),
    ADDITION_MARRIAGE("ADDITION_MARRIAGE"),
    ADDITION_ADOPTION_BIRTH_COURTORDER("ADDITION_ADOPTION_BIRTH_COURTORDER"),
    CHANGE_CSR_TIER_TO_OTHER("CHANGE_CSR_TIER_TO_OTHER"),
    CHANGE_CSR_TIER_TO_1("CHANGE_CSR_TIER_TO_1"),
    WAH_TO_QHP_OR_APTC("WAH_TO_QHP_OR_APTC"),
    ADDRESS_GAIN("ADDRESS_GAIN"),
    ADDRESS_LOSS("ADDRESS_LOSS"),
    ADDITION_MEC_LOSS_SEQ("ADDITION_MEC_LOSS_SEQ"),
    CHANGE_LAWFUL_PRESENCE("CHANGE_LAWFUL_PRESENCE"),
    REMOVAL_DIVORCE("REMOVAL_DIVORCE"),
    REMOVAL_DEATH("REMOVAL_DEATH"),
    REMOVAL_MOVING_OUT_OF_STATE("REMOVAL_MOVING_OUT_OF_STATE"),
    REMOVAL_TAX_FILING_HH_CHANGE("REMOVAL_TAX_FILING_HH_CHANGE"),
    REMOVAL_INCARCERATION("REMOVAL_INCARCERATION"),
    REMOVAL_OTHER("REMOVAL_OTHER"),
    CHANGE_INCOME("CHANGE_INCOME"),
    CHANGE_TAX_FILING_HH("CHANGE_TAX_FILING_HH"),
    TAX_FILING_RECONCILE("TAX_FILING_RECONCILE"),
    ADDITION_MEC_LOSS_FLOW("ADDITION_MEC_LOSS_FLOW"),
    ADDITION_OTHER("ADDITION_OTHER");

    private final String value;

    QualifyingLifeEvent(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

}