package com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.constants;

public enum NoticeReasonCode {
    INCARCERATION_PEND("EL001"), PREGNANCY_CHECK_FAIL("EL002"), INCARCERATION_CHECK_FAIL("EL939"), SSN_CHECK("EL208"),
    RESIDENCY_CHECK("EL210"), DECEASED_CHECK("EL913"), VLP_CASCADED("EL003"), CITIZEN_ALIEN_DENIAL("EL942"),
    MEC_MEDICARE("EL907"), MEC_PEACECORP("EL847"), MEC_TRICARE("EL810"), MEC_SMACARE("EL849"), MEC_VETERAN("EL809"),
    DUPLICATE_MEC_KCHIP("EL004"), DUPLICATE_MEC_APTC("EL808"), MEC_LOSE_GOOD_CAUSE("EL298"),
    POTENTIAL_NONMAGI_ELIGIBLE_SSI("EL225"), MEDICAID_DENIED_POTENTIAL_NONMAGI_ELIGIBLE("EL005"),
    POTENTIAL_NONMAGI_ELIGIBLE_AGED("EL804"), RECEIVES_ADOPTION_ASSISTANCE("EL006"), CHILD_NOT_MEETING_REQ("EL007"),
    GROUP_LEVEL_FAIL("EL599"), REFUSAL_MEDICALSUPPORT("EL008"), DUPLICATE_BENEFITS("EL009"),
    RECEIVING_BENEFITS_IN_OTHER_STATE("EL010"), APTC_FAIL_AS_QP_NOT_ELIGIBLE("EL011"), TAXFILERCHECK_FAIL("EL835"),
    FAILED_INCOME_TEST("EL817"), FAILED_ELIGIBILITY_TESTS_CSR("EL012"), AFFORDABLE_INSURANCE("EL848"),
    NO_APTC_RECONCILE("EL013"), AIAN_NOT_VERIFIED("EL014"), FAIL_RFI_DUEDATE_DOB_EL6007("EL015"),
    FAIL_RFI_DUEDATE_CITZN_EL6004("EL016"), FAIL_RFI_DUEDATE_ALIEN_EL6005("EL017"),
    FAIL_RFI_DUEDATE_INC_EL6012("EL018"), FAIL_RFI_DUEDATE_RESDNC_EL6017("EL019"), FAIL_RFI_DUEDATE_SSN_EL6020("EL020"),
    INCOME_VERF_FAILED("EL021"), INCARCERATION_VERF_FAILED("EL911"), DEATH_VERF_FAILED("EL022"),
    RESIDENCE_VERF_FAILED("EL200"), AIAN_VERF_FAILED("EL023"), FAIL_RFI_DUEDATE_HHRELN_EL6009("EL024"),
    FAIL_REQINFO_TIME_FRAME_DI4003("EL025"), FAIL_POSTPONED_VERIFICATION_DI4012("EL026"),
    FAIL_VERF_INFONF_EL6090("EL027"), DUPLICATE_MEC_ADLT("EL028"), EDG_OVERRIDDEN("EL029"),
    TAXDEPENDENT_APTC_DENIED("EL836"), MARRIED_FILING_SEPARATELY_APTC_FAIL("EL836"), STOPPED_REQUESTING_AID("EL921"),
    CASE_WITHDRAWN("EL921"), DUPLICATE_MEC_MEDICAID("EL808"), DENY_APPL_NOT_SIGNED("EL033"),
    PEND_APPL_NOT_SIGNED("EL034"), OVER_LAPPING_ELIGIBILITY("EL187"), OVER_LAPPING_OTHERSYSTEM_ELIGIBILITY("EL035"),
    INVALID_MEDICAID_RELATIONSHIP("EL846"), CURRENT_COVERAGEPREMIUM("EL848"), POTENTIAL_COVERAGE_PREMIUM("EL848"),
    NON_COOPERATION_NCP("EL038") // To be confirmed
    , INCOME_BELOW_LIMIT("EL818"), PRIOR_MEDICAID_FAIL("EL039"),
    COVERAGE_ENDDATE_FAILURE("EL040"), PERIOD_BEFORE_CONVERSION_REQUEST("EL041"), EMPLOYER_OPTED_OUT("EL042"),
    RELATIONSHIP_CHECK("EL815"), RELATED_AGE_26_CHECK("EL043"), ESHI_WITHDRAWN("EL044"),
    RECEIVING_SDX_BENEFITS("EL045"), DUPLICATE_MEC_CHEX("EL046"), RECEIVING_SC_BENEFITS("EL047"),
    RECEIVES_NONESIMEC("EL048"), RECEIVES_ESIMEC("EL049"), RECEIVES_MEDICARE_NONESI("EL050"),
    RECEIVING_OUT_OF_STATE_BENEFITS("EL249"), OUT_OF_HOUSEHOLD("EL602"), ELIGIBILITY_IS_PENDED("EL823"),
    RECEIVING_OTHERSYSTEM_BENEFITS("EL052"), PERSONNEL_RECEIVING_MA_BENEFITS("EL053"), SPENDDOWN_PEND("EL054"),
    RENEWAL_FAILURE("EL930"), P2_FACILITIES("EL055"), TAX_FILING_INFORMATION("EL825"),
    AGED_OR_RECEIVINGMEDICARE("EL804"), HOH_DECEASED("EL248"), EMCA_PEND("EL056"), ENTITLED_BENEFIT("EL057"),
    PARENT_NOT_TMA("EL058"), PRIOR_OR_RETROMONTHDENIAL("EL059"), SUSPENDED_DURING_RECERTIFICATION("EL060"),
    CE_DENIAL("EL061"), CLIENT_REQUEST("EL062"), MOVED_OUT_OF_STATE("EL601"), INCORRECT_APPROVAL("EL063"),
    MOVED_TO_ANOTHER_HH("EL064"), NON_COOPERATION("EL065"), INCOME_NON_COMPATIBLE("EL608"),
    MA_DENIED_ELIGIBILITY("EL609");

    private final String value;

    NoticeReasonCode(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

}
