//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.02 at 05:56:17 PM IST 
//


package com.deloitteinnovation.us.hbx.shopping.shoppingflowrestriction.driver.service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseOutcome complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseOutcome">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entity" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attribute-outcome" type="{http://hbx.us.deloitteinnovation.com/ws/hbxshoppingflowrestrictionservice/schema}OutcomeType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="relationship-outcome" type="{http://hbx.us.deloitteinnovation.com/ws/hbxshoppingflowrestrictionservice/schema}OutcomeType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseOutcome", propOrder = {
    "entity"
})
public class ResponseOutcome {

    protected List<ResponseOutcome.Entity> entity;

    /**
     * Gets the value of the entity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResponseOutcome.Entity }
     * 
     * 
     */
    public List<ResponseOutcome.Entity> getEntity() {
        if (entity == null) {
            entity = new ArrayList<ResponseOutcome.Entity>();
        }
        return this.entity;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attribute-outcome" type="{http://hbx.us.deloitteinnovation.com/ws/hbxshoppingflowrestrictionservice/schema}OutcomeType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="relationship-outcome" type="{http://hbx.us.deloitteinnovation.com/ws/hbxshoppingflowrestrictionservice/schema}OutcomeType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attributeOutcome",
        "relationshipOutcome"
    })
    public static class Entity {

        @XmlElement(name = "attribute-outcome")
        protected List<OutcomeType> attributeOutcome;
        @XmlElement(name = "relationship-outcome")
        protected List<OutcomeType> relationshipOutcome;
        @XmlAttribute(name = "id", required = true)
        protected String id;

        /**
         * Gets the value of the attributeOutcome property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attributeOutcome property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttributeOutcome().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OutcomeType }
         * 
         * 
         */
        public List<OutcomeType> getAttributeOutcome() {
            if (attributeOutcome == null) {
                attributeOutcome = new ArrayList<OutcomeType>();
            }
            return this.attributeOutcome;
        }

        /**
         * Gets the value of the relationshipOutcome property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the relationshipOutcome property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelationshipOutcome().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OutcomeType }
         * 
         * 
         */
        public List<OutcomeType> getRelationshipOutcome() {
            if (relationshipOutcome == null) {
                relationshipOutcome = new ArrayList<OutcomeType>();
            }
            return this.relationshipOutcome;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }

}
