package com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.rules;

import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.Case;
import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.Individual;

rule "Rule_1000_0600_Case_Withdrawn_1"
	salience 65534
	ruleflow-group "1000_0600_Case_Withdrawn"
	when
		$case:Case( IsCaseWithdrawn == true && $CaseIndivs : individual)
		$CaseIndiv:Individual() from $CaseIndivs
	then
		$CaseIndiv.setPerformNormalClosure(true);
		$CaseIndiv.setPerform_1000_002_1(true);
		$CaseIndiv.setPerform_1000_2_3(false);
end
