package com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.rules;
import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.Case;
import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.Individual;

rule "Rule_1000_0100_EDG_MAGI_Flow_Control_1"
	salience 65535
	ruleflow-group "1000_0100_EDG_MAGI_Flow_Control"
	when
		$case:Case($caseIndividual:individual)
		$CaseIndiv:Individual() from $caseIndividual
	then
		$case.setR5_TempEdgTraceIdIndex (0);
		$case.setHasUnbornChild(false);
		$CaseIndiv.setPerform_1000_2_3(true);
		$CaseIndiv.setPerform_SDX(false);
		$CaseIndiv.setIsSpendownMagiEligible(false);
		$CaseIndiv.setperform_OtherSystem(false);
		$CaseIndiv.setIsTaxGroupIdSetForDependent(false);
		$CaseIndiv.setIsTaxGroupIdSetForSpouse(false);
end

rule "Rule_1000_0100_EDG_MAGI_Flow_Control_2"
	salience 65534
	ruleflow-group "1000_0100_EDG_MAGI_Flow_Control"
	when
		$case:Case($caseIndividual:individual)
		$CaseIndiv:Individual(IsRebuild == true) from $caseIndividual
	then
		$CaseIndiv.setPerform_1000_2_3(false);
end