package com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.rules;

import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.Case;
import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.Individual;
import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.RelationShip;
import java.util.Arrays;

rule "Rule_1000_0200_Potentially_Non_MAGI_Eligible_0"
	salience 65536
	ruleflow-group "1000_0200_Potentially_Non_MAGI_Eligible"
	when
		$case:Case(PaymentBeginDate <= R5_NonMAGIStartDate && $caseIndividual:individual)
		$indiv:Individual() from $caseIndividual
	then
		$indiv.setIsRelatedToOtherIndividual(false);
		$indiv.setLPR("X");
		$indiv.setIsHistoricMAEligible(false);
		$indiv.setIsMAEligible(false);
		$indiv.setPerform_SDX(false);
		$indiv.setperform_OtherSystem(false);
		$indiv.setIsTaxGroupIdSetForSpouse(false);
		$indiv.setIsTaxGroupIdSetForDependent(false);
end

rule "Rule_1000_0200_Potentially_Non_MAGI_Eligible_1"
	salience 65535
	ruleflow-group "1000_0200_Potentially_Non_MAGI_Eligible"
	when
		$case:Case(PaymentBeginDate <= R5_NonMAGIStartDate && $caseIndividual:individual)
		$indiv:Individual(
			IsReceivingSSIFromSDX == false 
			&& IsReceivingSSIFromOtherSystem == false
			&& IsReceivingSSI == true
		) from $caseIndividual
	then
		$indiv.setPerform_1000_2_3(false);
		$indiv.setIsTP45(false);
		$indiv.setIsCHL1(false);
		$indiv.setIsCHL2(false);
		$indiv.setIsCHL3(false);
        $indiv.setIsCHL4(false);
		$indiv.setIsCHEX(false);
		$indiv.setIsCHIP(false);
		$indiv.setIsADLT(false);
		$indiv.setIsPREG(false);
		$indiv.setIsPACA(false);
		$indiv.setIsTMAE(false);
		$indiv.setIsTMAS(false);
		$indiv.setIsTMCE(false);
		$indiv.setIsTMCS(false);
		$indiv.setIsADPR(false);
		$indiv.setIsFFCC(false);
		$indiv.setIsFFOS(false);
end

rule "Rule_1000_0200_Potentially_Non_MAGI_Eligible_2"
	salience 65534
	ruleflow-group "1000_0200_Potentially_Non_MAGI_Eligible"
	when
		$case:Case(PaymentBeginDate <= R5_NonMAGIStartDate && $caseIndividual:individual)
		$indiv:Individual(
			IsReceivingSSIFromSDX == false 
			&& IsReceivingSSIFromOtherSystem == false
			&& IsReceivingStateSuppliment == true
		) from $caseIndividual
	then
		$indiv.setPerform_1000_2_3(false);
		$indiv.setIsTP45(false);
		$indiv.setIsCHL1(false);
		$indiv.setIsCHL2(false);
		$indiv.setIsCHL3(false);
        $indiv.setIsCHL4(false);
		$indiv.setIsCHEX(false);
		$indiv.setIsCHIP(false);
		$indiv.setIsADLT(false);
		$indiv.setIsPREG(false);
		$indiv.setIsPACA(false);
		$indiv.setIsTMAE(false);
		$indiv.setIsTMAS(false);
		$indiv.setIsTMCE(false);
		$indiv.setIsTMCS(false);
		$indiv.setIsADPR(false);
		$indiv.setIsFFCC(false);
		$indiv.setIsFFOS(false);
end

rule "Rule_1000_0200_Potentially_Non_MAGI_Eligible_3"
	salience 65533
	ruleflow-group "1000_0200_Potentially_Non_MAGI_Eligible"
	when
		$case:Case(PaymentBeginDate <= R5_NonMAGIStartDate && $caseIndividual:individual)
		$indiv:Individual(
			IsReceivingSSIFromSDX == false 
			&& IsReceivingSSIFromOtherSystem == false
			&& R5_IsNMAGIEligible == true
		) from $caseIndividual
	then
		$indiv.setPerform_1000_2_3(false);
		$indiv.setIsTP45(false);
		$indiv.setIsCHL1(false);
		$indiv.setIsCHL2(false);
		$indiv.setIsCHL3(false);
        $indiv.setIsCHL4(false);
		$indiv.setIsCHEX(false);
		$indiv.setIsCHIP(false);
		$indiv.setIsADLT(false);
		$indiv.setIsPREG(false);
		$indiv.setIsPACA(false);
		$indiv.setIsTMAE(false);
		$indiv.setIsTMAS(false);
		$indiv.setIsTMCE(false);
		$indiv.setIsTMCS(false);
		$indiv.setIsADPR(false);
		$indiv.setIsFFCC(false);
		$indiv.setIsFFOS(false);
end

rule "Rule_1000_0200_Potentially_Non_MAGI_Eligible_4"
	salience 65532
	ruleflow-group "1000_0200_Potentially_Non_MAGI_Eligible"
	when
		$case:Case(PaymentBeginDate <= R5_NonMAGIStartDate && $caseIndividual:individual)
		$indiv:Individual(
			IsReceivingSSIFromSDX == false 
			&& IsReceivingSSIFromOtherSystem == false
	 		&& IsEligibleForFosterCare == true
	 	) from $caseIndividual
	then
		$indiv.setPerform_1000_2_3(false);
		$indiv.setIsTP45(false);
		$indiv.setIsCHL1(false);
		$indiv.setIsCHL2(false);
		$indiv.setIsCHL3(false);
        $indiv.setIsCHL4(false);
		$indiv.setIsCHEX(false);
		$indiv.setIsCHIP(false);
		$indiv.setIsADLT(false);
		$indiv.setIsPREG(false);
		$indiv.setIsPACA(false);
		$indiv.setIsTMAE(false);
		$indiv.setIsTMAS(false);
		$indiv.setIsTMCE(false);
		$indiv.setIsTMCS(false);
		$indiv.setIsADPR(false);
		$indiv.setIsFFCC(false);
		$indiv.setIsFFOS(false);
end

rule "Rule_1000_0200_Potentially_Non_MAGI_Eligible_5"
	salience 65531
	ruleflow-group "1000_0200_Potentially_Non_MAGI_Eligible"
	when
		$case:Case(PaymentBeginDate <= R5_NonMAGIStartDate && $caseIndividual:individual)
		$indiv:Individual(
			IsReceivingSSIFromSDX == false 
			&& IsReceivingSSIFromOtherSystem == false 
			&& IsEligibleForSubsidizedAdoption == true
		) from $caseIndividual
	then
		$indiv.setPerform_1000_2_3(false);
		$indiv.setIsTP45(false);
		$indiv.setIsCHL1(false);
		$indiv.setIsCHL2(false);
		$indiv.setIsCHL3(false);
        $indiv.setIsCHL4(false);
		$indiv.setIsCHEX(false);
		$indiv.setIsCHIP(false);
		$indiv.setIsADLT(false);
		$indiv.setIsPREG(false);
		$indiv.setIsPACA(false);
		$indiv.setIsTMAE(false);
		$indiv.setIsTMAS(false);
		$indiv.setIsTMCE(false);
		$indiv.setIsTMCS(false);
		$indiv.setIsADPR(false);
		$indiv.setIsFFCC(false);
		$indiv.setIsFFOS(false);
end

rule "Rule_1000_0200_Potentially_Non_MAGI_Eligible_6"
	salience 65530
	ruleflow-group "1000_0200_Potentially_Non_MAGI_Eligible"
	when
		$case:Case(PaymentBeginDate <= R5_NonMAGIStartDate && $caseIndividual:individual)
		$indiv:Individual(
			IsReceivingSSIFromSDX == false 
			&& IsReceivingSSIFromOtherSystem == false
			&& IsEligibleForDJJM == true
		) from $caseIndividual
	then
		$indiv.setPerform_1000_2_3(false);
		$indiv.setIsTP45(false);
		$indiv.setIsCHL1(false);
		$indiv.setIsCHL2(false);
		$indiv.setIsCHL3(false);
        $indiv.setIsCHL4(false);
		$indiv.setIsCHEX(false);
		$indiv.setIsCHIP(false);
		$indiv.setIsADLT(false);
		$indiv.setIsPREG(false);
		$indiv.setIsPACA(false);
		$indiv.setIsTMAE(false);
		$indiv.setIsTMAS(false);
		$indiv.setIsTMCE(false);
		$indiv.setIsTMCS(false);
		$indiv.setIsADPR(false);
		$indiv.setIsFFCC(false);
		$indiv.setIsFFOS(false);
end

rule "Rule_1000_0200_Potentially_Non_MAGI_Eligible_7"
	salience 65529
	ruleflow-group "1000_0200_Potentially_Non_MAGI_Eligible"
	when
		$case:Case(PaymentBeginDate <= R5_NonMAGIStartDate && $caseIndividual:individual)
		$indiv:Individual(
			IsReceivingSSIFromSDX == false 
			&& IsReceivingSSIFromOtherSystem == false
			&& IsApprovedForSpendDown == true
		) from $caseIndividual
	then
		$indiv.setPerform_1000_2_3(false);
		$indiv.setIsTP45(false);
		$indiv.setIsCHL1(false);
		$indiv.setIsCHL2(false);
		$indiv.setIsCHL3(false);
        $indiv.setIsCHL4(false);
		$indiv.setIsCHEX(false);
		$indiv.setIsCHIP(false);
		$indiv.setIsADLT(false);
		$indiv.setIsPREG(false);
		$indiv.setIsPACA(false);
		$indiv.setIsTMAE(false);
		$indiv.setIsTMAS(false);
		$indiv.setIsTMCE(false);
		$indiv.setIsTMCS(false);
		$indiv.setIsADPR(false);
		$indiv.setIsFFCC(false);
		$indiv.setIsFFOS(false);	
end