package com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.rules;

import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.Case;
import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.Individual;
import java.util.Objects;

rule "Rule_1000_0800_Check_Unborn_Child_Count_1"
	salience 65535
	ruleflow-group "1000_0800_Check_Unborn_Child_Count"
	when
	 	$case:Case( $caseIndividual:individual )
   	 	$CaseIndiv:Individual(UnbornChildCount > 0L) from $caseIndividual
	then
	 	$case.setHasUnbornChild(true);
end

