package com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.rules;

import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.Case;
import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.EDGGroup;
import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.EDGIndividual;
import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.Individual;
import java.util.Objects;

rule "Rule_1000_0400_Set_Dummy_EDG_0"
	salience 65535
    ruleflow-group "1000_0400_Set_Dummy_EDG"
    when
        $case:Case($edgGroup:eDGGroup && $caseIndividual:individual)
        $Edg:EDGGroup($edgIndividual:eDGIndividual) from $edgGroup
        $EdgIndiv:EDGIndividual($individual:individual) from $edgIndividual
        $Indiv:Individual() from $individual
        $CaseIndiv:Individual() from $caseIndividual
    then
        $Edg.setIsDummyGroupCreated(true);
        $Edg.setCreatedForIndividualId(0L);
        $EdgIndiv.setV_isTargetTaxDependent_1000_140(false);
        $EdgIndiv.setV_isTaxDepOfTarget_1000_140(false);
        $EdgIndiv.setV_taxDepOfTaxPayer_1000_140(false);
        $EdgIndiv.setV_SpouseOfTarget_1000_150(false);
        $EdgIndiv.setV_parentOfTarget_1000_150(false);
        $EdgIndiv.setV_childOfTarget_1000_150(false);
        $EdgIndiv.setV_siblingOfTarget_1000_150(false);
        $Indiv.setV_SpouseOfFiler_1000_110(false);
        $Indiv.setV_taxDepOfNonCustodialPar_1000_110(false);
        $Indiv.setV_careTakerOfChild_1000_120(false);
        $Indiv.setV_parentOfChild_1000_120(false);
        $Indiv.setV_taxDependent_1000_110(false);
        $Indiv.setV_ChildOfFiler_1000_110(false);
        $CaseIndiv.setPerformNormalClosure(false);
        $CaseIndiv.setPerform_1000_002_1(false);
end

rule "Rule_1000_0400_Set_Dummy_EDG_1"
    salience 65534
    ruleflow-group "1000_0400_Set_Dummy_EDG"
    when
        $case:Case($edgGroup:eDGGroup && $caseIndividual:individual)
        $Edg:EDGGroup($edgIndividual:eDGIndividual) from $edgGroup
        $EdgIndiv:EDGIndividual($individual:individual) from $edgIndividual
        $Indiv:Individual() from $individual
        $CaseIndiv:Individual(IsRebuild == false) from  $caseIndividual
    then
        $CaseIndiv.setIsTP45(false);
        $CaseIndiv.setIsCHL1(false);
        $CaseIndiv.setIsCHL2(false);
        $CaseIndiv.setIsCHL3(false);
        $CaseIndiv.setIsCHL4(false);
        $CaseIndiv.setIsCHEX(false);
        $CaseIndiv.setIsCHIP(false);
        $CaseIndiv.setIsADLT(false);
        $CaseIndiv.setIsPREG(false);
        $CaseIndiv.setIsPACA(false);
        $CaseIndiv.setIsAPTC(false);
        $CaseIndiv.setIsFFCC(false);
        $CaseIndiv.setIsADFF(false);
        $CaseIndiv.setIsFFOS(false);
        $CaseIndiv.setIsADPR(false);
        $CaseIndiv.setIsReceivingMedicare(false);
        $CaseIndiv.setIsTMAE(false);
        $CaseIndiv.setIsTMAS(false);
        $CaseIndiv.setIsTMCE(false);
        $CaseIndiv.setIsTMCS(false);
        $CaseIndiv.setIsTMADeemed_ADLT(false);
        $CaseIndiv.setIsTMADeemed_Child(false);
        $CaseIndiv.setIsParentTMAEligible(false);
        $CaseIndiv.setIsParentCaretaker(false);
        $CaseIndiv.setIsEligibleForPACA(false);
end
