package com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.rules;

import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.Case;
import com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.magi.Individual;

rule "Rule_1000_0430_Identify_Individual_Tax_Group_1"
	salience 65534
	ruleflow-group "1000_0430_Identify_Individual_Tax_Group"
	when
		$case:Case( $caseIndividual:individual )
		$Indiv1:Individual(
			IsFiler == false 
			&& IsTaxDependent == false
		) from $caseIndividual
	then
		$Indiv1.setTaxGroupId($Indiv1.getTaxGroupId() +new Long(400));
end