package com.deloitteinnovation.us.hbx.edbc.eligibility.businessrules.qhp.constants;

public enum NoticeReasonCdType {

    RESIDENCY_CHECK("EL210"), CITIZEN_CHECK("EL900"), INCARCERATION_CHECK_FAIL("EL939"),
    QHP_DENIAL_AGE_GRATER_THAN_26("EL805"), GROUP_LEVEL_FAIL("EL599"), DECEASED_CHECK("EL913"),
    RELATIONSHIP_CHECK("EL914"), MARRIED_CHILD("EL001"), QHP_NOT_REQUESTED("EL921"), HAS_MEDICARE("EL907"),
    OVERLAPPING_OTHERSYSTEM_ELEIGIBILITY("EL004"), INCOMPLETE_RENEWAL("EL930"), INACTIVE_INDIVIDUAL("EL602"),
    HOH_DECEASED("EL248"), QHP_INACTIVE("EL006"), CLIENT_REQUEST("EL007"), MOVED_OUT_OF_STATE("EL008"),
    INCORRECT_APPROVOAL("EL009"), MOVED_TO_ANOTHER_HH("EL010"), NON_COOPERATION("EL011"),
    PERSONNEL_RECEIVING_MA_BENEFITS("EL012"), SSN_VERIFY_FAIL("EL901"), CITIZENSHIP_VERIFY_FAIL("EL120"),
    VLP_VERIFY_FAIL("EL812"), HAS_SMACARE("EL849");

    private final String value;

    NoticeReasonCdType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

}
