//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:26 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model.eligibilitydetermination;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//     This code was generated from a template.////     Manual changes to this file may cause unexpected behavior in your application.//     Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class EDBCExceptionLog {

	private int EDBCExceptionLog1;

	public int getEDBCExceptionLog1() {
		return EDBCExceptionLog1;
	}

	public void setEDBCExceptionLog1(int value) {
		EDBCExceptionLog1 = value;
	}

	private Integer CaseNumber;

	public Integer getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Integer value) {
		CaseNumber = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String ExceptionCode = "";

	public String getExceptionCode() {
		return ExceptionCode;
	}

	public void setExceptionCode(String value) {
		ExceptionCode = value;
	}

	private String ExceptionDetails = "";

	public String getExceptionDetails() {
		return ExceptionDetails;
	}

	public void setExceptionDetails(String value) {
		ExceptionDetails = value;
	}

	private String ExeceptionLogLevel = "";

	public String getExeceptionLogLevel() {
		return ExeceptionLogLevel;
	}

	public void setExeceptionLogLevel(String value) {
		ExeceptionLogLevel = value;
	}

	private String LogDetails = "";

	public String getLogDetails() {
		return LogDetails;
	}

	public void setLogDetails(String value) {
		LogDetails = value;
	}

	private String MethodName = "";

	public String getMethodName() {
		return MethodName;
	}

	public void setMethodName(String value) {
		MethodName = value;
	}

	private String ModuleName = "";

	public String getModuleName() {
		return ModuleName;
	}

	public void setModuleName(String value) {
		ModuleName = value;
	}

	private String ProcessName = "";

	public String getProcessName() {
		return ProcessName;
	}

	public void setProcessName(String value) {
		ProcessName = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	 private LocalDateTime RunTime;

	public LocalDateTime getRunTime() {
		return RunTime;
	}

	public void setRunTime(LocalDateTime value) {
		RunTime = value;
	}

	private Integer TransactionId;

	public Integer getTransactionId() {
		return TransactionId;
	}

	public void setTransactionId(Integer value) {
		TransactionId = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
