//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model.eligibilitydetermination;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//     This code was generated from a template.////     Manual changes to this file may cause unexpected behavior in your application.//     Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class EligibilitySpendDown {

	private int EdgNumber;

	public int getEdgNumber() {
		return EdgNumber;
	}

	public void setEdgNumber(int value) {
		EdgNumber = value;
	}

	private String PriorMedicaidCode = "";

	public String getPriorMedicaidCode() {
		return PriorMedicaidCode;
	}

	public void setPriorMedicaidCode(String value) {
		PriorMedicaidCode = value;
	}

	private Long CaseNumber;

	public Long getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Long value) {
		CaseNumber = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private LocalDateTime DispositionDate;

	public LocalDateTime getDispositionDate() {
		return DispositionDate;
	}

	public void setDispositionDate(LocalDateTime value) {
		DispositionDate = value;
	}

	private Double IncurredExpenseAmount;

	public Double getIncurredExpenseAmount() {
		return IncurredExpenseAmount;
	}

	public void setIncurredExpenseAmount(Double value) {
		IncurredExpenseAmount = value;
	}

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private String IsToConsiderQuarter = "";

	public String getIsToConsiderQuarter() {
		return IsToConsiderQuarter;
	}

	public void setIsToConsiderQuarter(String value) {
		IsToConsiderQuarter = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private Double SpendDownAmount;

	public Double getSpendDownAmount() {
		return SpendDownAmount;
	}

	public void setSpendDownAmount(Double value) {
		SpendDownAmount = value;
	}

	private LocalDateTime SpendDownEndDate;

	public LocalDateTime getSpendDownEndDate() {
		return SpendDownEndDate;
	}

	public void setSpendDownEndDate(LocalDateTime value) {
		SpendDownEndDate = value;
	}

	private LocalDateTime SpendDownMetDate;

	public LocalDateTime getSpendDownMetDate() {
		return SpendDownMetDate;
	}

	public void setSpendDownMetDate(LocalDateTime value) {
		SpendDownMetDate = value;
	}

	private LocalDateTime SpendDownStartDate;

	public LocalDateTime getSpendDownStartDate() {
		return SpendDownStartDate;
	}

	public void setSpendDownStartDate(LocalDateTime value) {
		SpendDownStartDate = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
