//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:25 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class CaseIndividualModel {

	private Long CaseNumber;

	public Long getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Long value) {
		CaseNumber = value;
	}

	private LocalDateTime EffectiveBeginDate;

	public LocalDateTime getEffectiveBeginDate() {
		return EffectiveBeginDate;
	}

	public void setEffectiveBeginDate(LocalDateTime value) {
		EffectiveBeginDate = value;
	}

	private Long IndividualId;

	public Long getIndividualId() {
		return IndividualId;
	}

	public void setIndividualId(Long value) {
		IndividualId = value;
	}

	private LocalDateTime CoverageLostDate;

	public LocalDateTime getCoverageLostDate() {
		return CoverageLostDate;
	}

	public void setCoverageLostDate(LocalDateTime value) {
		CoverageLostDate = value;
	}

	private String CoverageLostReasonCode = "";

	public String getCoverageLostReasonCode() {
		return CoverageLostReasonCode;
	}

	public void setCoverageLostReasonCode(String value) {
		CoverageLostReasonCode = value;
	}

	private String CoverageLostTypeCode = "";

	public String getCoverageLostTypeCode() {
		return CoverageLostTypeCode;
	}

	public void setCoverageLostTypeCode(String value) {
		CoverageLostTypeCode = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private LocalDateTime DocumentExpiryDate;

	public LocalDateTime getDocumentExpiryDate() {
		return DocumentExpiryDate;
	}

	public void setDocumentExpiryDate(LocalDateTime value) {
		DocumentExpiryDate = value;
	}

	private LocalDateTime EffectiveEndDate;

	public LocalDateTime getEffectiveEndDate() {
		return EffectiveEndDate;
	}

	public void setEffectiveEndDate(LocalDateTime value) {
		EffectiveEndDate = value;
	}

	private String IsActiveInCase = "";

	public String getIsActiveInCase() {
		return IsActiveInCase;
	}

	public void setIsActiveInCase(String value) {
		IsActiveInCase = value;
	}

	private String IsTMember = "";

	public String getIsTMember() {
		return IsTMember;
	}

	public void setIsTMember(String value) {
		IsTMember = value;
	}

	private String NameofCarrier = "";

	public String getNameofCarrier() {
		return NameofCarrier;
	}

	public void setNameofCarrier(String value) {
		NameofCarrier = value;
	}

	private String OtherHealthCoverageCode = "";

	public String getOtherHealthCoverageCode() {
		return OtherHealthCoverageCode;
	}

	public void setOtherHealthCoverageCode(String value) {
		OtherHealthCoverageCode = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
