//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:25 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class CitizenshipModel {

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private int CitizenshipId;

	public int getCitizenshipId() {
		return CitizenshipId;
	}

	public void setCitizenshipId(int value) {
		CitizenshipId = value;
	}

	private String CitizenshipAcquiredThrough = "";

	public String getCitizenshipAcquiredThrough() {
		return CitizenshipAcquiredThrough;
	}

	public void setCitizenshipAcquiredThrough(String value) {
		CitizenshipAcquiredThrough = value;
	}

	private LocalDateTime CitizenshipStartDate;

	public LocalDateTime getCitizenshipStartDate() {
		return CitizenshipStartDate;
	}

	public void setCitizenshipStartDate(LocalDateTime value) {
		CitizenshipStartDate = value;
	}

	private String CitizenshipVerificationCode = "";

	public String getCitizenshipVerificationCode() {
		return CitizenshipVerificationCode;
	}

	public void setCitizenshipVerificationCode(String value) {
		CitizenshipVerificationCode = value;
	}

	private LocalDateTime CitizenshipVerificationDate;

	public LocalDateTime getCitizenshipVerificationDate() {
		return CitizenshipVerificationDate;
	}

	public void setCitizenshipVerificationDate(LocalDateTime value) {
		CitizenshipVerificationDate = value;
	}

	private LocalDateTime ClientBecameAwareDate;

	public LocalDateTime getClientBecameAwareDate() {
		return ClientBecameAwareDate;
	}

	public void setClientBecameAwareDate(LocalDateTime value) {
		ClientBecameAwareDate = value;
	}

	private LocalDateTime ClientReportedDate;

	public LocalDateTime getClientReportedDate() {
		return ClientReportedDate;
	}

	public void setClientReportedDate(LocalDateTime value) {
		ClientReportedDate = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private LocalDateTime IdentificationExpirationDate;

	public LocalDateTime getIdentificationExpirationDate() {
		return IdentificationExpirationDate;
	}

	public void setIdentificationExpirationDate(LocalDateTime value) {
		IdentificationExpirationDate = value;
	}

	private String IdentificationNumber = "";

	public String getIdentificationNumber() {
		return IdentificationNumber;
	}

	public void setIdentificationNumber(String value) {
		IdentificationNumber = value;
	}

	private String IdentificationStateCode = "";

	public String getIdentificationStateCode() {
		return IdentificationStateCode;
	}

	public void setIdentificationStateCode(String value) {
		IdentificationStateCode = value;
	}

	private String IdentificationVerificationCode = "";

	public String getIdentificationVerificationCode() {
		return IdentificationVerificationCode;
	}

	public void setIdentificationVerificationCode(String value) {
		IdentificationVerificationCode = value;
	}

	private LocalDateTime IdentificationVerificationDate;

	public LocalDateTime getIdentificationVerificationDate() {
		return IdentificationVerificationDate;
	}

	public void setIdentificationVerificationDate(LocalDateTime value) {
		IdentificationVerificationDate = value;
	}

	private String IsParentAgreeToAttestChild = "";

	public String getIsParentAgreeToAttestChild() {
		return IsParentAgreeToAttestChild;
	}

	public void setIsParentAgreeToAttestChild(String value) {
		IsParentAgreeToAttestChild = value;
	}

	private String IsUSCitizen = "";

	public String getIsUSCitizen() {
		return IsUSCitizen;
	}

	public void setIsUSCitizen(String value) {
		IsUSCitizen = value;
	}

	private String IsUSCitizenValidated = "";

	public String getIsUSCitizenValidated() {
		return IsUSCitizenValidated;
	}

	public void setIsUSCitizenValidated(String value) {
		IsUSCitizenValidated = value;
	}

	private Long ParentIndividualId;

	public Long getParentIndividualId() {
		return ParentIndividualId;
	}

	public void setParentIndividualId(Long value) {
		ParentIndividualId = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
