//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:25 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class ComplianceModel {

	private int ComplianceId;

	public int getComplianceId() {
		return ComplianceId;
	}

	public void setComplianceId(int value) {
		ComplianceId = value;
	}

	private Long IndividualId;

	public Long getIndividualId() {
		return IndividualId;
	}

	public void setIndividualId(Long value) {
		IndividualId = value;
	}

	private Integer NonCustodialParentRelationshipId;

	public Integer getNonCustodialParentRelationshipId() {
		return NonCustodialParentRelationshipId;
	}

	public void setNonCustodialParentRelationshipId(Integer value) {
		NonCustodialParentRelationshipId = value;
	}

	private String AgreeToComply = "";

	public String getAgreeToComply() {
		return AgreeToComply;
	}

	public void setAgreeToComply(String value) {
		AgreeToComply = value;
	}

	private LocalDateTime BeginDate;

	public LocalDateTime getBeginDate() {
		return BeginDate;
	}

	public void setBeginDate(LocalDateTime value) {
		BeginDate = value;
	}

	private String ComplianceType = "";

	public String getComplianceType() {
		return ComplianceType;
	}

	public void setComplianceType(String value) {
		ComplianceType = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String CureReason = "";

	public String getCureReason() {
		return CureReason;
	}

	public void setCureReason(String value) {
		CureReason = value;
	}

	private String CureVerification = "";

	public String getCureVerification() {
		return CureVerification;
	}

	public void setCureVerification(String value) {
		CureVerification = value;
	}

	private LocalDateTime CureVerificationDate;

	public LocalDateTime getCureVerificationDate() {
		return CureVerificationDate;
	}

	public void setCureVerificationDate(LocalDateTime value) {
		CureVerificationDate = value;
	}

	private LocalDateTime DateComplianceMet;

	public LocalDateTime getDateComplianceMet() {
		return DateComplianceMet;
	}

	public void setDateComplianceMet(LocalDateTime value) {
		DateComplianceMet = value;
	}

	private LocalDateTime EndDate;

	public LocalDateTime getEndDate() {
		return EndDate;
	}

	public void setEndDate(LocalDateTime value) {
		EndDate = value;
	}

	private String ExemptionReason = "";

	public String getExemptionReason() {
		return ExemptionReason;
	}

	public void setExemptionReason(String value) {
		ExemptionReason = value;
	}

	private String ExemptionVerification = "";

	public String getExemptionVerification() {
		return ExemptionVerification;
	}

	public void setExemptionVerification(String value) {
		ExemptionVerification = value;
	}

	private LocalDateTime ExemptionVerificationDate;

	public LocalDateTime getExemptionVerificationDate() {
		return ExemptionVerificationDate;
	}

	public void setExemptionVerificationDate(LocalDateTime value) {
		ExemptionVerificationDate = value;
	}

	private String GoodCauseReason = "";

	public String getGoodCauseReason() {
		return GoodCauseReason;
	}

	public void setGoodCauseReason(String value) {
		GoodCauseReason = value;
	}

	private String GoodCauseVerification = "";

	public String getGoodCauseVerification() {
		return GoodCauseVerification;
	}

	public void setGoodCauseVerification(String value) {
		GoodCauseVerification = value;
	}

	private LocalDateTime GoodCauseVerificationDate;

	public LocalDateTime getGoodCauseVerificationDate() {
		return GoodCauseVerificationDate;
	}

	public void setGoodCauseVerificationDate(LocalDateTime value) {
		GoodCauseVerificationDate = value;
	}

	private String JobContactListVerificationCode = "";

	public String getJobContactListVerificationCode() {
		return JobContactListVerificationCode;
	}

	public void setJobContactListVerificationCode(String value) {
		JobContactListVerificationCode = value;
	}

	private LocalDateTime JobContactListVerificationDate;

	public LocalDateTime getJobContactListVerificationDate() {
		return JobContactListVerificationDate;
	}

	public void setJobContactListVerificationDate(LocalDateTime value) {
		JobContactListVerificationDate = value;
	}

	private Integer R5ConversionComplianceId;

	public Integer getR5ConversionComplianceId() {
		return R5ConversionComplianceId;
	}

	public void setR5ConversionComplianceId(Integer value) {
		R5ConversionComplianceId = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private String StatusCode = "";

	public String getStatusCode() {
		return StatusCode;
	}

	public void setStatusCode(String value) {
		StatusCode = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

	private String VerificationCode = "";

	public String getVerificationCode() {
		return VerificationCode;
	}

	public void setVerificationCode(String value) {
		VerificationCode = value;
	}

	private LocalDateTime VerificationDate;

	public LocalDateTime getVerificationDate() {
		return VerificationDate;
	}

	public void setVerificationDate(LocalDateTime value) {
		VerificationDate = value;
	}

	private LocalDateTime WorkRegistrationDate;

	public LocalDateTime getWorkRegistrationDate() {
		return WorkRegistrationDate;
	}

	public void setWorkRegistrationDate(LocalDateTime value) {
		WorkRegistrationDate = value;
	}

	private String WorkRegistrationSource = "";

	public String getWorkRegistrationSource() {
		return WorkRegistrationSource;
	}

	public void setWorkRegistrationSource(String value) {
		WorkRegistrationSource = value;
	}

}
