//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:26 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;


import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class DCIndividualModel {

    private Long IndividualId;

    public Long getIndividualId() {
        return IndividualId;
    }

    public void setIndividualId(Long value) {
        IndividualId = value;
    }

    private String AliasFirstName = "";

    public String getAliasFirstName() {
        return AliasFirstName;
    }

    public void setAliasFirstName(String value) {
        AliasFirstName = value;
    }

    private String AliasLastName = "";

    public String getAliasLastName() {
        return AliasLastName;
    }

    public void setAliasLastName(String value) {
        AliasLastName = value;
    }

    private String AppliedSSNVerificationCode = "";

    public String getAppliedSSNVerificationCode() {
        return AppliedSSNVerificationCode;
    }

    public void setAppliedSSNVerificationCode(String value) {
        AppliedSSNVerificationCode = value;
    }

    private LocalDateTime AppliedSSNVerificationDate;

    public LocalDateTime getAppliedSSNVerificationDate() {
        return AppliedSSNVerificationDate;
    }

    public void setAppliedSSNVerificationDate(LocalDateTime value) {
        AppliedSSNVerificationDate = value;
    }

    private LocalDateTime BirthDate;

    public LocalDateTime getBirthDate() {
        return BirthDate;
    }

    public void setBirthDate(LocalDateTime value) {
        BirthDate = value;
    }

    private Long ConversionIndividualId;

    public Long getConversionIndividualId() {
        return ConversionIndividualId;
    }

    public void setConversionIndividualId(Long value) {
        ConversionIndividualId = value;
    }

    private String ConvertedIndividual = "";

    public String getConvertedIndividual() {
        return ConvertedIndividual;
    }

    public void setConvertedIndividual(String value) {
        ConvertedIndividual = value;
    }

    private LocalDateTime CreateDate;

    public LocalDateTime getCreateDate() {
        return CreateDate;
    }

    public void setCreateDate(LocalDateTime value) {
        CreateDate = value;
    }

    private String CreateUserId = "";

    public String getCreateUserId() {
        return CreateUserId;
    }

    public void setCreateUserId(String value) {
        CreateUserId = value;
    }

    private LocalDateTime DateOfBirthVerificationDate;

    public LocalDateTime getDateOfBirthVerificationDate() {
        return DateOfBirthVerificationDate;
    }

    public void setDateOfBirthVerificationDate(LocalDateTime value) {
        DateOfBirthVerificationDate = value;
    }

    private String DateOfBirthVerifiedCode = "";

    public String getDateOfBirthVerifiedCode() {
        return DateOfBirthVerifiedCode;
    }

    public void setDateOfBirthVerifiedCode(String value) {
        DateOfBirthVerifiedCode = value;
    }

    private LocalDateTime DeathDate;

    public LocalDateTime getDeathDate() {
        return DeathDate;
    }

    public void setDeathDate(LocalDateTime value) {
        DeathDate = value;
    }

    private String DeathDateVerificationCode = "";

    public String getDeathDateVerificationCode() {
        return DeathDateVerificationCode;
    }

    public void setDeathDateVerificationCode(String value) {
        DeathDateVerificationCode = value;
    }

    private LocalDateTime DeathDateVerificationDate;

    public LocalDateTime getDeathDateVerificationDate() {
        return DeathDateVerificationDate;
    }

    public void setDeathDateVerificationDate(LocalDateTime value) {
        DeathDateVerificationDate = value;
    }

    private String DeemedEligible = "";

    public String getDeemedEligible() {
        return DeemedEligible;
    }

    public void setDeemedEligible(String value) {
        DeemedEligible = value;
    }

    private String DhsIdentification = "";

    public String getDhsIdentification() {
        return DhsIdentification;
    }

    public void setDhsIdentification(String value) {
        DhsIdentification = value;
    }

    private String EthnicityCode = "";

    public String getEthnicityCode() {
        return EthnicityCode;
    }

    public void setEthnicityCode(String value) {
        EthnicityCode = value;
    }

    private String FederalRecognizedTribeVerificationCode = "";

    public String getFederalRecognizedTribeVerificationCode() {
        return FederalRecognizedTribeVerificationCode;
    }

    public void setFederalRecognizedTribeVerificationCode(String value) {
        FederalRecognizedTribeVerificationCode = value;
    }

    private LocalDateTime FederalRecognizedTribeVerificationDate;

    public LocalDateTime getFederalRecognizedTribeVerificationDate() {
        return FederalRecognizedTribeVerificationDate;
    }

    public void setFederalRecognizedTribeVerificationDate(LocalDateTime value) {
        FederalRecognizedTribeVerificationDate = value;
    }

    private String FirstName = "";

    public String getFirstName() {
        return FirstName;
    }

    public void setFirstName(String value) {
        FirstName = value;
    }

    private String GenderCode = "";

    public String getGenderCode() {
        return GenderCode;
    }

    public void setGenderCode(String value) {
        GenderCode = value;
    }

    private String HasAppliedForSSN = "";

    public String getHasAppliedForSSN() {
        return HasAppliedForSSN;
    }

    public void setHasAppliedForSSN(String value) {
        HasAppliedForSSN = value;
    }

    private String IndianTribeCode = "";

    public String getIndianTribeCode() {
        return IndianTribeCode;
    }

    public void setIndianTribeCode(String value) {
        IndianTribeCode = value;
    }

    private String IsActive = "";

    public String getIsActive() {
        return IsActive;
    }

    public void setIsActive(String value) {
        IsActive = value;
    }

    private String IsCategoricallyEligible = "";

    public String getIsCategoricallyEligible() {
        return IsCategoricallyEligible;
    }

    public void setIsCategoricallyEligible(String value) {
        IsCategoricallyEligible = value;
    }

    private String IsContactInformationSameForAllHouseholdMember = "";

    public String getIsContactInformationSameForAllHouseholdMember() {
        return IsContactInformationSameForAllHouseholdMember;
    }

    public void setIsContactInformationSameForAllHouseholdMember(String value) {
        IsContactInformationSameForAllHouseholdMember = value;
    }

    private String IsDateOfBirthValidated = "";

    public String getIsDateOfBirthValidated() {
        return IsDateOfBirthValidated;
    }

    public void setIsDateOfBirthValidated(String value) {
        IsDateOfBirthValidated = value;
    }

    private String IsDateOfDeathValidated = "";

    public String getIsDateOfDeathValidated() {
        return IsDateOfDeathValidated;
    }

    public void setIsDateOfDeathValidated(String value) {
        IsDateOfDeathValidated = value;
    }

    private String IsDelete = "";

    public String getIsDelete() {
        return IsDelete;
    }

    public void setIsDelete(String value) {
        IsDelete = value;
    }

    private String IsEDRSTriggerred = "";

    public String getIsEDRSTriggerred() {
        return IsEDRSTriggerred;
    }

    public void setIsEDRSTriggerred(String value) {
        IsEDRSTriggerred = value;
    }

    private String IsEmployerSponsorGroup = "";

    public String getIsEmployerSponsorGroup() {
        return IsEmployerSponsorGroup;
    }

    public void setIsEmployerSponsorGroup(String value) {
        IsEmployerSponsorGroup = value;
    }

    private String IsFederalHubVerified = "";

    public String getIsFederalHubVerified() {
        return IsFederalHubVerified;
    }

    public void setIsFederalHubVerified(String value) {
        IsFederalHubVerified = value;
    }

    private String IsFederalRecognizedIndianTribe = "";

    public String getIsFederalRecognizedIndianTribe() {
        return IsFederalRecognizedIndianTribe;
    }

    public void setIsFederalRecognizedIndianTribe(String value) {
        IsFederalRecognizedIndianTribe = value;
    }

    private String IsFileCleared = "";

    public String getIsFileCleared() {
        return IsFileCleared;
    }

    public void setIsFileCleared(String value) {
        IsFileCleared = value;
    }

    private String IsFixedAddress = "";

    public String getIsFixedAddress() {
        return IsFixedAddress;
    }

    public void setIsFixedAddress(String value) {
        IsFixedAddress = value;
    }

    private String IsHomeless = "";

    public String getIsHomeless() {
        return IsHomeless;
    }

    public void setIsHomeless(String value) {
        IsHomeless = value;
    }

    private String IsRequestForCoverage = "";

    public String getIsRequestForCoverage() {
        return IsRequestForCoverage;
    }

    public void setIsRequestForCoverage(String value) {
        IsRequestForCoverage = value;
    }

    private String IsSingleParentAdoption = "";

    public String getIsSingleParentAdoption() {
        return IsSingleParentAdoption;
    }

    public void setIsSingleParentAdoption(String value) {
        IsSingleParentAdoption = value;
    }

    private String IsSingleParentAdoptionAudit = "";

    public String getIsSingleParentAdoptionAudit() {
        return IsSingleParentAdoptionAudit;
    }

    public void setIsSingleParentAdoptionAudit(String value) {
        IsSingleParentAdoptionAudit = value;
    }

    private String IsSpecialNeedRequired = "";

    public String getIsSpecialNeedRequired() {
        return IsSpecialNeedRequired;
    }

    public void setIsSpecialNeedRequired(String value) {
        IsSpecialNeedRequired = value;
    }

    private String IsSsaValidated = "";

    public String getIsSsaValidated() {
        return IsSsaValidated;
    }

    public void setIsSsaValidated(String value) {
        IsSsaValidated = value;
    }

    private String IsSsnNameDifferent = "";

    public String getIsSsnNameDifferent() {
        return IsSsnNameDifferent;
    }

    public void setIsSsnNameDifferent(String value) {
        IsSsnNameDifferent = value;
    }

    private String IsSsnValidated = "";

    public String getIsSsnValidated() {
        return IsSsnValidated;
    }

    public void setIsSsnValidated(String value) {
        IsSsnValidated = value;
    }

    private String LastName = "";

    public String getLastName() {
        return LastName;
    }

    public void setLastName(String value) {
        LastName = value;
    }

    private String MaidCardNumber = "";

    public String getMaidCardNumber() {
        return MaidCardNumber;
    }

    public void setMaidCardNumber(String value) {
        MaidCardNumber = value;
    }

    private Integer MciId;

    public Integer getMciId() {
        return MciId;
    }

    public void setMciId(Integer value) {
        MciId = value;
    }

    private String MCIMaidCardUpdateStatusCode = "";

    public String getMCIMaidCardUpdateStatusCode() {
        return MCIMaidCardUpdateStatusCode;
    }

    public void setMCIMaidCardUpdateStatusCode(String value) {
        MCIMaidCardUpdateStatusCode = value;
    }

    private String MergeSeparateIndicator = "";

    public String getMergeSeparateIndicator() {
        return MergeSeparateIndicator;
    }

    public void setMergeSeparateIndicator(String value) {
        MergeSeparateIndicator = value;
    }

    private String MiddleInitial = "";

    public String getMiddleInitial() {
        return MiddleInitial;
    }

    public void setMiddleInitial(String value) {
        MiddleInitial = value;
    }

    private String NativeVerificationCode = "";

    public String getNativeVerificationCode() {
        return NativeVerificationCode;
    }

    public void setNativeVerificationCode(String value) {
        NativeVerificationCode = value;
    }

    private String NoReasonSsnCode = "";

    public String getNoReasonSsnCode() {
        return NoReasonSsnCode;
    }

    public void setNoReasonSsnCode(String value) {
        NoReasonSsnCode = value;
    }

    private String OtherRaceCode = "";

    public String getOtherRaceCode() {
        return OtherRaceCode;
    }

    public void setOtherRaceCode(String value) {
        OtherRaceCode = value;
    }

    private String PreferredSpokenLanguageCode = "";

    public String getPreferredSpokenLanguageCode() {
        return PreferredSpokenLanguageCode;
    }

    public void setPreferredSpokenLanguageCode(String value) {
        PreferredSpokenLanguageCode = value;
    }

    private String PreferredWrittenLanguageCode = "";

    public String getPreferredWrittenLanguageCode() {
        return PreferredWrittenLanguageCode;
    }

    public void setPreferredWrittenLanguageCode(String value) {
        PreferredWrittenLanguageCode = value;
    }

    private Integer PrimaryOfficeId;

    public Integer getPrimaryOfficeId() {
        return PrimaryOfficeId;
    }

    public void setPrimaryOfficeId(Integer value) {
        PrimaryOfficeId = value;
    }

    private String PseudoSsn = "";

    public String getPseudoSsn() {
        return PseudoSsn;
    }

    public void setPseudoSsn(String value) {
        PseudoSsn = value;
    }

    private Long R4BConversionIndividualId;

    public Long getR4BConversionIndividualId() {
        return R4BConversionIndividualId;
    }

    public void setR4BConversionIndividualId(Long value) {
        R4BConversionIndividualId = value;
    }

    private Long R5ConversionIndividualId;

    public Long getR5ConversionIndividualId() {
        return R5ConversionIndividualId;
    }

    public void setR5ConversionIndividualId(Long value) {
        R5ConversionIndividualId = value;
    }

    private Long R5ConversionIndividualIdCCAP;

    public Long getR5ConversionIndividualIdCCAP() {
        return R5ConversionIndividualIdCCAP;
    }

    public void setR5ConversionIndividualIdCCAP(Long value) {
        R5ConversionIndividualIdCCAP = value;
    }

    private Long R5ConversionIndividualIdCCAPOld;

    public Long getR5ConversionIndividualIdCCAPOld() {
        return R5ConversionIndividualIdCCAPOld;
    }

    public void setR5ConversionIndividualIdCCAPOld(Long value) {
        R5ConversionIndividualIdCCAPOld = value;
    }

    private Long R5ConversionIndividualIdOld;

    public Long getR5ConversionIndividualIdOld() {
        return R5ConversionIndividualIdOld;
    }

    public void setR5ConversionIndividualIdOld(Long value) {
        R5ConversionIndividualIdOld = value;
    }

    private String RaceCode = "";

    public String getRaceCode() {
        return RaceCode;
    }

    public void setRaceCode(String value) {
        RaceCode = value;
    }

    private String ReportedSsn = "";

    public String getReportedSsn() {
        return ReportedSsn;
    }

    public void setReportedSsn(String value) {
        ReportedSsn = value;
    }

    private byte[] RowVersionStamp;

    public byte[] getRowVersionStamp() {
        return RowVersionStamp;
    }

    public void setRowVersionStamp(byte[] value) {
        RowVersionStamp = value;
    }

    private LocalDateTime SevisDate;

    public LocalDateTime getSevisDate() {
        return SevisDate;
    }

    public void setSevisDate(LocalDateTime value) {
        SevisDate = value;
    }

    private String SevisId = "";

    public String getSevisId() {
        return SevisId;
    }

    public void setSevisId(String value) {
        SevisId = value;
    }

    private String SingleParentVerificationCode = "";

    public String getSingleParentVerificationCode() {
        return SingleParentVerificationCode;
    }

    public void setSingleParentVerificationCode(String value) {
        SingleParentVerificationCode = value;
    }

    private String SingleParentVerificationCodeAudit = "";

    public String getSingleParentVerificationCodeAudit() {
        return SingleParentVerificationCodeAudit;
    }

    public void setSingleParentVerificationCodeAudit(String value) {
        SingleParentVerificationCodeAudit = value;
    }

    private LocalDateTime SingleParentVerifiedDate;

    public LocalDateTime getSingleParentVerifiedDate() {
        return SingleParentVerifiedDate;
    }

    public void setSingleParentVerifiedDate(LocalDateTime value) {
        SingleParentVerifiedDate = value;
    }

    private LocalDateTime SingleParentVerifiedDateAudit;

    public LocalDateTime getSingleParentVerifiedDateAudit() {
        return SingleParentVerifiedDateAudit;
    }

    public void setSingleParentVerifiedDateAudit(LocalDateTime value) {
        SingleParentVerifiedDateAudit = value;
    }

    private LocalDateTime SpecialNeedVerificationDate;

    public LocalDateTime getSpecialNeedVerificationDate() {
        return SpecialNeedVerificationDate;
    }

    public void setSpecialNeedVerificationDate(LocalDateTime value) {
        SpecialNeedVerificationDate = value;
    }

    private String SpecialNeedVrf = "";

    public String getSpecialNeedVrf() {
        return SpecialNeedVrf;
    }

    public void setSpecialNeedVrf(String value) {
        SpecialNeedVrf = value;
    }

    private LocalDateTime SS5ApplicationDate;

    public LocalDateTime getSS5ApplicationDate() {
        return SS5ApplicationDate;
    }

    public void setSS5ApplicationDate(LocalDateTime value) {
        SS5ApplicationDate = value;
    }

    private String SsaVerificationCode = "";

    public String getSsaVerificationCode() {
        return SsaVerificationCode;
    }

    public void setSsaVerificationCode(String value) {
        SsaVerificationCode = value;
    }

    private String Ssn = "";

    public String getSsn() {
        return Ssn;
    }

    public void setSsn(String value) {
        Ssn = value;
    }

    private String SsnFirstName = "";

    public String getSsnFirstName() {
        return SsnFirstName;
    }

    public void setSsnFirstName(String value) {
        SsnFirstName = value;
    }

    private String SsnLastName = "";

    public String getSsnLastName() {
        return SsnLastName;
    }

    public void setSsnLastName(String value) {
        SsnLastName = value;
    }

    private String SsnMiddleName = "";

    public String getSsnMiddleName() {
        return SsnMiddleName;
    }

    public void setSsnMiddleName(String value) {
        SsnMiddleName = value;
    }

    private String SsnSuffixCode = "";

    public String getSsnSuffixCode() {
        return SsnSuffixCode;
    }

    public void setSsnSuffixCode(String value) {
        SsnSuffixCode = value;
    }

    private String SSNVerificationCode = "";

    public String getSSNVerificationCode() {
        return SSNVerificationCode;
    }

    public void setSSNVerificationCode(String value) {
        SSNVerificationCode = value;
    }

    private LocalDateTime SSNVerificationDate;

    public LocalDateTime getSSNVerificationDate() {
        return SSNVerificationDate;
    }

    public void setSSNVerificationDate(LocalDateTime value) {
        SSNVerificationDate = value;
    }

    private String SuffixCode = "";

    public String getSuffixCode() {
        return SuffixCode;
    }

    public void setSuffixCode(String value) {
        SuffixCode = value;
    }

    private LocalDateTime SVESActionDate;

    public LocalDateTime getSVESActionDate() {
        return SVESActionDate;
    }

    public void setSVESActionDate(LocalDateTime value) {
        SVESActionDate = value;
    }

    private String TaxFileCode = "";

    public String getTaxFileCode() {
        return TaxFileCode;
    }

    public void setTaxFileCode(String value) {
        TaxFileCode = value;
    }

    private Integer TaxIdentificationNumber;

    public Integer getTaxIdentificationNumber() {
        return TaxIdentificationNumber;
    }

    public void setTaxIdentificationNumber(Integer value) {
        TaxIdentificationNumber = value;
    }

    private String TribeStateCode = "";

    public String getTribeStateCode() {
        return TribeStateCode;
    }

    public void setTribeStateCode(String value) {
        TribeStateCode = value;
    }

    private LocalDateTime UpdateDate;

    public LocalDateTime getUpdateDate() {
        return UpdateDate;
    }

    public void setUpdateDate(LocalDateTime value) {
        UpdateDate = value;
    }

    private String UpdateUserId = "";

    public String getUpdateUserId() {
        return UpdateUserId;
    }

    public void setUpdateUserId(String value) {
        UpdateUserId = value;
    }

    private Integer UserId;

    public Integer getUserId() {
        return UserId;
    }

    public void setUserId(Integer value) {
        UserId = value;
    }

    private String isMADenied;

    public String getIsMADenied() {
        return isMADenied;
    }

    public void setIsMADenied(String value) {
        isMADenied = value;
    }

    private Boolean isSMA;

    public Boolean getisSMA() {
        return isSMA;
    }

    public void setisSMA(Boolean value) {
        isSMA = value;
    }

    private String isFullTimeStudent;

    public String getIsFullTimeStudent() {
        return isFullTimeStudent;
    }

    public void setIsFullTimeStudent(String isFullTimeStudent) {
        this.isFullTimeStudent = isFullTimeStudent;
    }

    private String wasInFosterCare;

    public String getWasInFosterCare() {
        return wasInFosterCare;
    }

    public void setWasInFosterCare(String wasInFosterCare) {
        this.wasInFosterCare = wasInFosterCare;
    }
    private String applyingState;

    public String getApplyingState() {
        return applyingState;
    }

    public void setApplyingState(String applyingState) {
        this.applyingState = applyingState;
    }
    private String wasReceivingMedicaid;

    public String getWasReceivingMedicaid() {
        return wasReceivingMedicaid;
    }

    public void setWasReceivingMedicaid(String wasReceivingMedicaid) {
        this.wasReceivingMedicaid = wasReceivingMedicaid;
    }

    private Boolean isTaxCompliant;

    public Boolean getTaxCompliant() {
        return isTaxCompliant;
    }

    public void setTaxCompliant(Boolean taxCompliant) {
        isTaxCompliant = taxCompliant;
    }
}
