//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:26 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class DCIndividualAlienSponsorRelationshipModel {

	private int DCIndividualAlienSponsorRelationshipId;

	public int getDCIndividualAlienSponsorRelationshipId() {
		return DCIndividualAlienSponsorRelationshipId;
	}

	public void setDCIndividualAlienSponsorRelationshipId(int value) {
		DCIndividualAlienSponsorRelationshipId = value;
	}

	private int DCIndividualAlienSponsorId;

	public int getDCIndividualAlienSponsorId() {
		return DCIndividualAlienSponsorId;
	}

	public void setDCIndividualAlienSponsorId(int value) {
		DCIndividualAlienSponsorId = value;
	}

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private LocalDateTime AffidavitSignedDate;

	public LocalDateTime getAffidavitSignedDate() {
		return AffidavitSignedDate;
	}

	public void setAffidavitSignedDate(LocalDateTime value) {
		AffidavitSignedDate = value;
	}

	private Double ContributionAmount;

	public Double getContributionAmount() {
		return ContributionAmount;
	}

	public void setContributionAmount(Double value) {
		ContributionAmount = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String Frequency = "";

	public String getFrequency() {
		return Frequency;
	}

	public void setFrequency(String value) {
		Frequency = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime SponsorRelationshipEndDate;

	public LocalDateTime getSponsorRelationshipEndDate() {
		return SponsorRelationshipEndDate;
	}

	public void setSponsorRelationshipEndDate(LocalDateTime value) {
		SponsorRelationshipEndDate = value;
	}

	private String SponsorTypeCode = "";

	public String getSponsorTypeCode() {
		return SponsorTypeCode;
	}

	public void setSponsorTypeCode(String value) {
		SponsorTypeCode = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

	private String VerificationCode = "";

	public String getVerificationCode() {
		return VerificationCode;
	}

	public void setVerificationCode(String value) {
		VerificationCode = value;
	}

	private LocalDateTime VerifiedOnDate;

	public LocalDateTime getVerifiedOnDate() {
		return VerifiedOnDate;
	}

	public void setVerifiedOnDate(LocalDateTime value) {
		VerifiedOnDate = value;
	}

}
