//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:26 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class DCIndividualAlienSponsorInformationModel {

	private int DCIndividualAlienSponsorInformationId;

	public int getDCIndividualAlienSponsorInformationId() {
		return DCIndividualAlienSponsorInformationId;
	}

	public void setDCIndividualAlienSponsorInformationId(int value) {
		DCIndividualAlienSponsorInformationId = value;
	}

	private int DCIndividualAlienSponsorId;

	public int getDCIndividualAlienSponsorId() {
		return DCIndividualAlienSponsorId;
	}

	public void setDCIndividualAlienSponsorId(int value) {
		DCIndividualAlienSponsorId = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String IsReceivingSNAP = "";

	public String getIsReceivingSNAP() {
		return IsReceivingSNAP;
	}

	public void setIsReceivingSNAP(String value) {
		IsReceivingSNAP = value;
	}

	private Integer NumberOfIndividualsSponsored;

	public Integer getNumberOfIndividualsSponsored() {
		return NumberOfIndividualsSponsored;
	}

	public void setNumberOfIndividualsSponsored(Integer value) {
		NumberOfIndividualsSponsored = value;
	}

	private Integer NumberOfTaxDependents;

	public Integer getNumberOfTaxDependents() {
		return NumberOfTaxDependents;
	}

	public void setNumberOfTaxDependents(Integer value) {
		NumberOfTaxDependents = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	 private LocalDateTime SponsorInformationBeginDate;

	public LocalDateTime getSponsorInformationBeginDate() {
		return SponsorInformationBeginDate;
	}

	public void setSponsorInformationBeginDate(LocalDateTime value) {
		SponsorInformationBeginDate = value;
	}

	 private LocalDateTime SponsorInformationEndDate;

	public LocalDateTime getSponsorInformationEndDate() {
		return SponsorInformationEndDate;
	}

	public void setSponsorInformationEndDate(LocalDateTime value) {
		SponsorInformationEndDate = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
