//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:26 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class DSNAPResourceModel {

	private int DSNAPResourceId;

	public int getDSNAPResourceId() {
		return DSNAPResourceId;
	}

	public void setDSNAPResourceId(int value) {
		DSNAPResourceId = value;
	}

	private Integer CaseNumber;

	public Integer getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Integer value) {
		CaseNumber = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String DSNAPResourceType = "";

	public String getDSNAPResourceType() {
		return DSNAPResourceType;
	}

	public void setDSNAPResourceType(String value) {
		DSNAPResourceType = value;
	}

	private Double ResourceAmount;

	public Double getResourceAmount() {
		return ResourceAmount;
	}

	public void setResourceAmount(Double value) {
		ResourceAmount = value;
	}

	private String ResourceVerificationCode = "";

	public String getResourceVerificationCode() {
		return ResourceVerificationCode;
	}

	public void setResourceVerificationCode(String value) {
		ResourceVerificationCode = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
