//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:26 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class EDBCConversionBenefitMatchModel {

	private int EDBCConversionBenefitMatchId;

	public int getEDBCConversionBenefitMatchId() {
		return EDBCConversionBenefitMatchId;
	}

	public void setEDBCConversionBenefitMatchId(int value) {
		EDBCConversionBenefitMatchId = value;
	}

	private Long CaseNumber;

	public Long getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Long value) {
		CaseNumber = value;
	}

	private Integer ConversionCGSize;

	public Integer getConversionCGSize() {
		return ConversionCGSize;
	}

	public void setConversionCGSize(Integer value) {
		ConversionCGSize = value;
	}

	private Integer ConversionEdgNumber;

	public Integer getConversionEdgNumber() {
		return ConversionEdgNumber;
	}

	public void setConversionEdgNumber(Integer value) {
		ConversionEdgNumber = value;
	}

	private Integer ConversionEdgTraceId;

	public Integer getConversionEdgTraceId() {
		return ConversionEdgTraceId;
	}

	public void setConversionEdgTraceId(Integer value) {
		ConversionEdgTraceId = value;
	}

	private String ConversionProgramCode = "";

	public String getConversionProgramCode() {
		return ConversionProgramCode;
	}

	public void setConversionProgramCode(String value) {
		ConversionProgramCode = value;
	}

	private String ConversionTOA = "";

	public String getConversionTOA() {
		return ConversionTOA;
	}

	public void setConversionTOA(String value) {
		ConversionTOA = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String ExceptionMessage = "";

	public String getExceptionMessage() {
		return ExceptionMessage;
	}

	public void setExceptionMessage(String value) {
		ExceptionMessage = value;
	}

	private Long IndividualId;

	public Long getIndividualId() {
		return IndividualId;
	}

	public void setIndividualId(Long value) {
		IndividualId = value;
	}

	private String IsBenefitAmountMatch = "";

	public String getIsBenefitAmountMatch() {
		return IsBenefitAmountMatch;
	}

	public void setIsBenefitAmountMatch(String value) {
		IsBenefitAmountMatch = value;
	}

	private String IsBenefitMatch = "";

	public String getIsBenefitMatch() {
		return IsBenefitMatch;
	}

	public void setIsBenefitMatch(String value) {
		IsBenefitMatch = value;
	}

	private String IsDeprivationReasonCodeMatch = "";

	public String getIsDeprivationReasonCodeMatch() {
		return IsDeprivationReasonCodeMatch;
	}

	public void setIsDeprivationReasonCodeMatch(String value) {
		IsDeprivationReasonCodeMatch = value;
	}

	private String IsDisabilityCatergoryCodeMatch = "";

	public String getIsDisabilityCatergoryCodeMatch() {
		return IsDisabilityCatergoryCodeMatch;
	}

	public void setIsDisabilityCatergoryCodeMatch(String value) {
		IsDisabilityCatergoryCodeMatch = value;
	}

	private String IsEdgIncomeMatch = "";

	public String getIsEdgIncomeMatch() {
		return IsEdgIncomeMatch;
	}

	public void setIsEdgIncomeMatch(String value) {
		IsEdgIncomeMatch = value;
	}

	private String IsEdgNumberMatch = "";

	public String getIsEdgNumberMatch() {
		return IsEdgNumberMatch;
	}

	public void setIsEdgNumberMatch(String value) {
		IsEdgNumberMatch = value;
	}

	private String IsEdgResourceMatch = "";

	public String getIsEdgResourceMatch() {
		return IsEdgResourceMatch;
	}

	public void setIsEdgResourceMatch(String value) {
		IsEdgResourceMatch = value;
	}

	private String IsHouseholdCategoryCodeMatch = "";

	public String getIsHouseholdCategoryCodeMatch() {
		return IsHouseholdCategoryCodeMatch;
	}

	public void setIsHouseholdCategoryCodeMatch(String value) {
		IsHouseholdCategoryCodeMatch = value;
	}

	private String IsMemberMatch = "";

	public String getIsMemberMatch() {
		return IsMemberMatch;
	}

	public void setIsMemberMatch(String value) {
		IsMemberMatch = value;
	}

	private String IsPatientLiabilityMatch = "";

	public String getIsPatientLiabilityMatch() {
		return IsPatientLiabilityMatch;
	}

	public void setIsPatientLiabilityMatch(String value) {
		IsPatientLiabilityMatch = value;
	}

	private String IsPenaltyAmountMatch = "";

	public String getIsPenaltyAmountMatch() {
		return IsPenaltyAmountMatch;
	}

	public void setIsPenaltyAmountMatch(String value) {
		IsPenaltyAmountMatch = value;
	}

	private String IsTOAMatch = "";

	public String getIsTOAMatch() {
		return IsTOAMatch;
	}

	public void setIsTOAMatch(String value) {
		IsTOAMatch = value;
	}

	private String OtherSystemEdgStatusCode = "";

	public String getOtherSystemEdgStatusCode() {
		return OtherSystemEdgStatusCode;
	}

	public void setOtherSystemEdgStatusCode(String value) {
		OtherSystemEdgStatusCode = value;
	}

	private Double OtherSystemNetIssuanceAmount;

	public Double getOtherSystemNetIssuanceAmount() {
		return OtherSystemNetIssuanceAmount;
	}

	public void setOtherSystemNetIssuanceAmount(Double value) {
		OtherSystemNetIssuanceAmount = value;
	}

	private Integer HealthChoiceCGSize;

	public Integer getHealthChoiceCGSize() {
		return HealthChoiceCGSize;
	}

	public void setHealthChoiceCGSize(Integer value) {
		HealthChoiceCGSize = value;
	}

	private String HealthChoiceEdgStatusCode = "";

	public String getHealthChoiceEdgStatusCode() {
		return HealthChoiceEdgStatusCode;
	}

	public void setHealthChoiceEdgStatusCode(String value) {
		HealthChoiceEdgStatusCode = value;
	}

	private Integer HealthChoiceEdgTraceId;

	public Integer getHealthChoiceEdgTraceId() {
		return HealthChoiceEdgTraceId;
	}

	public void setHealthChoiceEdgTraceId(Integer value) {
		HealthChoiceEdgTraceId = value;
	}

	private String HealthChoiceTOA = "";

	public String getHealthChoiceTOA() {
		return HealthChoiceTOA;
	}

	public void setHealthChoiceTOA(String value) {
		HealthChoiceTOA = value;
	}

	private Integer HealthChoiceEdgNumber;

	public Integer getHealthChoiceEdgNumber() {
		return HealthChoiceEdgNumber;
	}

	public void setHealthChoiceEdgNumber(Integer value) {
		HealthChoiceEdgNumber = value;
	}

	private Double NetIssuanceAmount;

	public Double getNetIssuanceAmount() {
		return NetIssuanceAmount;
	}

	public void setNetIssuanceAmount(Double value) {
		NetIssuanceAmount = value;
	}

	private Double PatientLiabilityAmount;

	public Double getPatientLiabilityAmount() {
		return PatientLiabilityAmount;
	}

	public void setPatientLiabilityAmount(Double value) {
		PatientLiabilityAmount = value;
	}

	private String ProgramCode = "";

	public String getProgramCode() {
		return ProgramCode;
	}

	public void setProgramCode(String value) {
		ProgramCode = value;
	}

	private LocalDateTime ReviewDueDate;

	public LocalDateTime getReviewDueDate() {
		return ReviewDueDate;
	}

	public void setReviewDueDate(LocalDateTime value) {
		ReviewDueDate = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
