//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:26 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class EDBCLogModel {

	private int EDBCLogId;

	public int getEDBCLogId() {
		return EDBCLogId;
	}

	public void setEDBCLogId(int value) {
		EDBCLogId = value;
	}

	private Integer CaseNumber;

	public Integer getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Integer value) {
		CaseNumber = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private Integer EdgTraceId;

	public Integer getEdgTraceId() {
		return EdgTraceId;
	}

	public void setEdgTraceId(Integer value) {
		EdgTraceId = value;
	}

	 private LocalDateTime EDMMonth;

	public LocalDateTime getEDMMonth() {
		return EDMMonth;
	}

	public void setEDMMonth(LocalDateTime value) {
		EDMMonth = value;
	}

	private Integer EligibilityTransactionId;

	public Integer getEligibilityTransactionId() {
		return EligibilityTransactionId;
	}

	public void setEligibilityTransactionId(Integer value) {
		EligibilityTransactionId = value;
	}

	private String ExceptionDetails = "";

	public String getExceptionDetails() {
		return ExceptionDetails;
	}

	public void setExceptionDetails(String value) {
		ExceptionDetails = value;
	}

	private String ModuleName = "";

	public String getModuleName() {
		return ModuleName;
	}

	public void setModuleName(String value) {
		ModuleName = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	 private LocalDateTime RunTime;

	public LocalDateTime getRunTime() {
		return RunTime;
	}

	public void setRunTime(LocalDateTime value) {
		RunTime = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

	private String XMLData = "";

	public String getXMLData() {
		return XMLData;
	}

	public void setXMLData(String value) {
		XMLData = value;
	}

	private String XMLIndicator = "";

	public String getXMLIndicator() {
		return XMLIndicator;
	}

	public void setXMLIndicator(String value) {
		XMLIndicator = value;
	}

}
