//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:26 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class EDBCAddtionalNoticeRequestModel {

	private int EDBCAddtionalNoticeRequestId;

	public int getEDBCAddtionalNoticeRequestId() {
		return EDBCAddtionalNoticeRequestId;
	}

	public void setEDBCAddtionalNoticeRequestId(int value) {
		EDBCAddtionalNoticeRequestId = value;
	}

	private Long CaseNumber;

	public Long getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Long value) {
		CaseNumber = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String DispositionStatus = "";

	public String getDispositionStatus() {
		return DispositionStatus;
	}

	public void setDispositionStatus(String value) {
		DispositionStatus = value;
	}

	 private LocalDateTime EdbcRunDate;

	public LocalDateTime getEdbcRunDate() {
		return EdbcRunDate;
	}

	public void setEdbcRunDate(LocalDateTime value) {
		EdbcRunDate = value;
	}

	private String EDBCStatus = "";

	public String getEDBCStatus() {
		return EDBCStatus;
	}

	public void setEDBCStatus(String value) {
		EDBCStatus = value;
	}

	private Integer EdgNumber;

	public Integer getEdgNumber() {
		return EdgNumber;
	}

	public void setEdgNumber(Integer value) {
		EdgNumber = value;
	}

	private Integer EdgTraceId;

	public Integer getEdgTraceId() {
		return EdgTraceId;
	}

	public void setEdgTraceId(Integer value) {
		EdgTraceId = value;
	}

	private Integer EDMMonth;

	public Integer getEDMMonth() {
		return EDMMonth;
	}

	public void setEDMMonth(Integer value) {
		EDMMonth = value;
	}

	private String IsDelete = "";

	public String getIsDelete() {
		return IsDelete;
	}

	public void setIsDelete(String value) {
		IsDelete = value;
	}

	private String NoticeReasonCode = "";

	public String getNoticeReasonCode() {
		return NoticeReasonCode;
	}

	public void setNoticeReasonCode(String value) {
		NoticeReasonCode = value;
	}

	private String RequestReason = "";

	public String getRequestReason() {
		return RequestReason;
	}

	public void setRequestReason(String value) {
		RequestReason = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
