//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:26 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class EDProgramCategoryModel {

	private int EDProgramCategoryId;

	public int getEDProgramCategoryId() {
		return EDProgramCategoryId;
	}

	public void setEDProgramCategoryId(int value) {
		EDProgramCategoryId = value;
	}

	private String CorrespondenceRequired = "";

	public String getCorrespondenceRequired() {
		return CorrespondenceRequired;
	}

	public void setCorrespondenceRequired(String value) {
		CorrespondenceRequired = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String EDVCLMapper = "";

	public String getEDVCLMapper() {
		return EDVCLMapper;
	}

	public void setEDVCLMapper(String value) {
		EDVCLMapper = value;
	}

	private String ExpansionTypeCode = "";

	public String getExpansionTypeCode() {
		return ExpansionTypeCode;
	}

	public void setExpansionTypeCode(String value) {
		ExpansionTypeCode = value;
	}

	private String InstitutionalStatusCode = "";

	public String getInstitutionalStatusCode() {
		return InstitutionalStatusCode;
	}

	public void setInstitutionalStatusCode(String value) {
		InstitutionalStatusCode = value;
	}

	private String IsDisenrollmentToBeTriggered = "";

	public String getIsDisenrollmentToBeTriggered() {
		return IsDisenrollmentToBeTriggered;
	}

	public void setIsDisenrollmentToBeTriggered(String value) {
		IsDisenrollmentToBeTriggered = value;
	}

	private String ISKHIPPEligible = "";

	public String getISKHIPPEligible() {
		return ISKHIPPEligible;
	}

	public void setISKHIPPEligible(String value) {
		ISKHIPPEligible = value;
	}

	private String IsSpecialCircumstanceApplicable = "";

	public String getIsSpecialCircumstanceApplicable() {
		return IsSpecialCircumstanceApplicable;
	}

	public void setIsSpecialCircumstanceApplicable(String value) {
		IsSpecialCircumstanceApplicable = value;
	}

	private String IsWaiverEligible = "";

	public String getIsWaiverEligible() {
		return IsWaiverEligible;
	}

	public void setIsWaiverEligible(String value) {
		IsWaiverEligible = value;
	}

	private String HBEHealthIndicator = "";

	public String getHBEHealthIndicator() {
		return HBEHealthIndicator;
	}

	public void setHBEHealthIndicator(String value) {
		HBEHealthIndicator = value;
	}

	private String HBEProgramCategory = "";

	public String getHBEProgramCategory() {
		return HBEProgramCategory;
	}

	public void setHBEProgramCategory(String value) {
		HBEProgramCategory = value;
	}

	private String HBEProgramCode = "";

	public String getHBEProgramCode() {
		return HBEProgramCode;
	}

	public void setHBEProgramCode(String value) {
		HBEProgramCode = value;
	}

	private String MC_FFSIndicator = "";

	public String getMC_FFSIndicator() {
		return MC_FFSIndicator;
	}

	public void setMC_FFSIndicator(String value) {
		MC_FFSIndicator = value;
	}

	private String NOETOAGroup = "";

	public String getNOETOAGroup() {
		return NOETOAGroup;
	}

	public void setNOETOAGroup(String value) {
		NOETOAGroup = value;
	}

	private String PriortyNumber = "";

	public String getPriortyNumber() {
		return PriortyNumber;
	}

	public void setPriortyNumber(String value) {
		PriortyNumber = value;
	}

	private String RecertificationMonth = "";

	public String getRecertificationMonth() {
		return RecertificationMonth;
	}

	public void setRecertificationMonth(String value) {
		RecertificationMonth = value;
	}

	private String RFIRequiredFlag = "";

	public String getRFIRequiredFlag() {
		return RFIRequiredFlag;
	}

	public void setRFIRequiredFlag(String value) {
		RFIRequiredFlag = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private String SSPDispositionFlag = "";

	public String getSSPDispositionFlag() {
		return SSPDispositionFlag;
	}

	public void setSSPDispositionFlag(String value) {
		SSPDispositionFlag = value;
	}

	private String TypeOfAssistanceCode = "";

	public String getTypeOfAssistanceCode() {
		return TypeOfAssistanceCode;
	}

	public void setTypeOfAssistanceCode(String value) {
		TypeOfAssistanceCode = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
