//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class EligibilityVerificationChecklistDetailModel {

	private Long CaseNumber;

	public Long getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Long value) {
		CaseNumber = value;
	}

	private int EligibilityVerificationChecklistDetailId;

	public int getEligibilityVerificationChecklistDetailId() {
		return EligibilityVerificationChecklistDetailId;
	}

	public void setEligibilityVerificationChecklistDetailId(int value) {
		EligibilityVerificationChecklistDetailId = value;
	}

	private String AdditionalDetails = "";

	public String getAdditionalDetails() {
		return AdditionalDetails;
	}

	public void setAdditionalDetails(String value) {
		AdditionalDetails = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private Integer DataCollectionId;

	public Integer getDataCollectionId() {
		return DataCollectionId;
	}

	public void setDataCollectionId(Integer value) {
		DataCollectionId = value;
	}

	 private LocalDateTime DCUpdateDate;

	public LocalDateTime getDCUpdateDate() {
		return DCUpdateDate;
	}

	public void setDCUpdateDate(LocalDateTime value) {
		DCUpdateDate = value;
	}

	private Integer EdgTraceId;

	public Integer getEdgTraceId() {
		return EdgTraceId;
	}

	public void setEdgTraceId(Integer value) {
		EdgTraceId = value;
	}

	 private LocalDateTime EDMDate;

	public LocalDateTime getEDMDate() {
		return EDMDate;
	}

	public void setEDMDate(LocalDateTime value) {
		EDMDate = value;
	}

	private Integer EligibilityTransactionId;

	public Integer getEligibilityTransactionId() {
		return EligibilityTransactionId;
	}

	public void setEligibilityTransactionId(Integer value) {
		EligibilityTransactionId = value;
	}

	private Integer EligibilityVerificationChecklistId;

	public Integer getEligibilityVerificationChecklistId() {
		return EligibilityVerificationChecklistId;
	}

	public void setEligibilityVerificationChecklistId(Integer value) {
		EligibilityVerificationChecklistId = value;
	}

	private String IsDelete = "";

	public String getIsDelete() {
		return IsDelete;
	}

	public void setIsDelete(String value) {
		IsDelete = value;
	}

	private String IsRecent = "";

	public String getIsRecent() {
		return IsRecent;
	}

	public void setIsRecent(String value) {
		IsRecent = value;
	}

	private Integer ParentId;

	public Integer getParentId() {
		return ParentId;
	}

	public void setParentId(Integer value) {
		ParentId = value;
	}

	private byte[] RowVersionTimeStamp;

	public byte[] getRowVersionTimeStamp() {
		return RowVersionTimeStamp;
	}

	public void setRowVersionTimeStamp(byte[] value) {
		RowVersionTimeStamp = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

	private Integer VCLReferenceNumber;

	public Integer getVCLReferenceNumber() {
		return VCLReferenceNumber;
	}

	public void setVCLReferenceNumber(Integer value) {
		VCLReferenceNumber = value;
	}

	 private LocalDateTime VerificationDate;

	public LocalDateTime getVerificationDate() {
		return VerificationDate;
	}

	public void setVerificationDate(LocalDateTime value) {
		VerificationDate = value;
	}

	private String VerificationSourceValue = "";

	public String getVerificationSourceValue() {
		return VerificationSourceValue;
	}

	public void setVerificationSourceValue(String value) {
		VerificationSourceValue = value;
	}

	private String VerificationStatus = "";

	public String getVerificationStatus() {
		return VerificationStatus;
	}

	public void setVerificationStatus(String value) {
		VerificationStatus = value;
	}

}
