//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:26 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class EligibilityIndividualTMADetailModel {

	private Long CaseNumber;

	public Long getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Long value) {
		CaseNumber = value;
	}

	private int EligibilityIndividualTMADetailsId;

	public int getEligibilityIndividualTMADetailsId() {
		return EligibilityIndividualTMADetailsId;
	}

	public void setEligibilityIndividualTMADetailsId(int value) {
		EligibilityIndividualTMADetailsId = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private Integer DispositionTransactionId;

	public Integer getDispositionTransactionId() {
		return DispositionTransactionId;
	}

	public void setDispositionTransactionId(Integer value) {
		DispositionTransactionId = value;
	}

	private Integer EdgNumber;

	public Integer getEdgNumber() {
		return EdgNumber;
	}

	public void setEdgNumber(Integer value) {
		EdgNumber = value;
	}

	private LocalDateTime EffectiveBeginDate;

	public LocalDateTime getEffectiveBeginDate() {
		return EffectiveBeginDate;
	}

	public void setEffectiveBeginDate(LocalDateTime value) {
		EffectiveBeginDate = value;
	}

	private LocalDateTime EffectiveEndDate;

	public LocalDateTime getEffectiveEndDate() {
		return EffectiveEndDate;
	}

	public void setEffectiveEndDate(LocalDateTime value) {
		EffectiveEndDate = value;
	}

	private Long IndividualId;

	public Long getIndividualId() {
		return IndividualId;
	}

	public void setIndividualId(Long value) {
		IndividualId = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime TMABeginDate;

	public LocalDateTime getTMABeginDate() {
		return TMABeginDate;
	}

	public void setTMABeginDate(LocalDateTime value) {
		TMABeginDate = value;
	}

	private LocalDateTime TMAEndDate;

	public LocalDateTime getTMAEndDate() {
		return TMAEndDate;
	}

	public void setTMAEndDate(LocalDateTime value) {
		TMAEndDate = value;
	}

	private Double TMASequenceNumber;

	public Double getTMASequenceNumber() {
		return TMASequenceNumber;
	}

	public void setTMASequenceNumber(Double value) {
		TMASequenceNumber = value;
	}

	private String TMATypeCode = "";

	public String getTMATypeCode() {
		return TMATypeCode;
	}

	public void setTMATypeCode(String value) {
		TMATypeCode = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
