//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class EligibilityNonMAGIIndividualResourceDetailModel {

	private Long CaseNumber;

	public Long getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Long value) {
		CaseNumber = value;
	}

	private int EdgTraceId;

	public int getEdgTraceId() {
		return EdgTraceId;
	}

	public void setEdgTraceId(int value) {
		EdgTraceId = value;
	}

	private int EligibilityMedicaidIndividualResourceDetailId;

	public int getEligibilityMedicaidIndividualResourceDetailId() {
		return EligibilityMedicaidIndividualResourceDetailId;
	}

	public void setEligibilityMedicaidIndividualResourceDetailId(int value) {
		EligibilityMedicaidIndividualResourceDetailId = value;
	}

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private Double ClientContributionAmount;

	public Double getClientContributionAmount() {
		return ClientContributionAmount;
	}

	public void setClientContributionAmount(Double value) {
		ClientContributionAmount = value;
	}

	private Double CountablePercentage;

	public Double getCountablePercentage() {
		return CountablePercentage;
	}

	public void setCountablePercentage(Double value) {
		CountablePercentage = value;
	}

	private Double CountableResourceAmount;

	public Double getCountableResourceAmount() {
		return CountableResourceAmount;
	}

	public void setCountableResourceAmount(Double value) {
		CountableResourceAmount = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private LocalDateTime ExemptionBeginDate;

	public LocalDateTime getExemptionBeginDate() {
		return ExemptionBeginDate;
	}

	public void setExemptionBeginDate(LocalDateTime value) {
		ExemptionBeginDate = value;
	}

	private Double ExemptionCount;

	public Double getExemptionCount() {
		return ExemptionCount;
	}

	public void setExemptionCount(Double value) {
		ExemptionCount = value;
	}

	private LocalDateTime ExemptionEndDate;

	public LocalDateTime getExemptionEndDate() {
		return ExemptionEndDate;
	}

	public void setExemptionEndDate(LocalDateTime value) {
		ExemptionEndDate = value;
	}

	private String ExemptRsnCode = "";

	public String getExemptRsnCode() {
		return ExemptRsnCode;
	}

	public void setExemptRsnCode(String value) {
		ExemptRsnCode = value;
	}

	private String HasTamperedWith = "";

	public String getHasTamperedWith() {
		return HasTamperedWith;
	}

	public void setHasTamperedWith(String value) {
		HasTamperedWith = value;
	}

	private String PreStrikeIndicator = "";

	public String getPreStrikeIndicator() {
		return PreStrikeIndicator;
	}

	public void setPreStrikeIndicator(String value) {
		PreStrikeIndicator = value;
	}

	private Double ResourceAmount;

	public Double getResourceAmount() {
		return ResourceAmount;
	}

	public void setResourceAmount(Double value) {
		ResourceAmount = value;
	}

	private String ResourceCategoryCode = "";

	public String getResourceCategoryCode() {
		return ResourceCategoryCode;
	}

	public void setResourceCategoryCode(String value) {
		ResourceCategoryCode = value;
	}

	private String ResourceDescText = "";

	public String getResourceDescText() {
		return ResourceDescText;
	}

	public void setResourceDescText(String value) {
		ResourceDescText = value;
	}

	private String ResourceDetailRef = "";

	public String getResourceDetailRef() {
		return ResourceDetailRef;
	}

	public void setResourceDetailRef(String value) {
		ResourceDetailRef = value;
	}

	private Double ResourceExemptAmount;

	public Double getResourceExemptAmount() {
		return ResourceExemptAmount;
	}

	public void setResourceExemptAmount(Double value) {
		ResourceExemptAmount = value;
	}

	private String ResourceTypeCode = "";

	public String getResourceTypeCode() {
		return ResourceTypeCode;
	}

	public void setResourceTypeCode(String value) {
		ResourceTypeCode = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private String TimeLimitedExmptRscAmt = "";

	public String getTimeLimitedExmptRscAmt() {
		return TimeLimitedExmptRscAmt;
	}

	public void setTimeLimitedExmptRscAmt(String value) {
		TimeLimitedExmptRscAmt = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
