//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class EligibilityNonMAGIIndividualBudgetModel {

	private Long CaseNumber;

	public Long getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Long value) {
		CaseNumber = value;
	}

	private int EdgTraceId;

	public int getEdgTraceId() {
		return EdgTraceId;
	}

	public void setEdgTraceId(int value) {
		EdgTraceId = value;
	}

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private Double AllocationAmount;

	public Double getAllocationAmount() {
		return AllocationAmount;
	}

	public void setAllocationAmount(Double value) {
		AllocationAmount = value;
	}

	private Double BlindWorkExpenseAmount;

	public Double getBlindWorkExpenseAmount() {
		return BlindWorkExpenseAmount;
	}

	public void setBlindWorkExpenseAmount(Double value) {
		BlindWorkExpenseAmount = value;
	}

	private Double ChildSupportIncome;

	public Double getChildSupportIncome() {
		return ChildSupportIncome;
	}

	public void setChildSupportIncome(Double value) {
		ChildSupportIncome = value;
	}

	private Double ChildSupportIncomeForPatientLiability;

	public Double getChildSupportIncomeForPatientLiability() {
		return ChildSupportIncomeForPatientLiability;
	}

	public void setChildSupportIncomeForPatientLiability(Double value) {
		ChildSupportIncomeForPatientLiability = value;
	}

	private Double COLAExclusionAmount;

	public Double getCOLAExclusionAmount() {
		return COLAExclusionAmount;
	}

	public void setCOLAExclusionAmount(Double value) {
		COLAExclusionAmount = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private Double ExclusionEarnedIncomeAmount;

	public Double getExclusionEarnedIncomeAmount() {
		return ExclusionEarnedIncomeAmount;
	}

	public void setExclusionEarnedIncomeAmount(Double value) {
		ExclusionEarnedIncomeAmount = value;
	}

	private Double FarmLossAmount;

	public Double getFarmLossAmount() {
		return FarmLossAmount;
	}

	public void setFarmLossAmount(Double value) {
		FarmLossAmount = value;
	}

	private Double GrossEarnedIncome;

	public Double getGrossEarnedIncome() {
		return GrossEarnedIncome;
	}

	public void setGrossEarnedIncome(Double value) {
		GrossEarnedIncome = value;
	}

	private Double GrossEmploymentIncome;

	public Double getGrossEmploymentIncome() {
		return GrossEmploymentIncome;
	}

	public void setGrossEmploymentIncome(Double value) {
		GrossEmploymentIncome = value;
	}

	private Double GrossSelfEmploymentFarmIncome;

	public Double getGrossSelfEmploymentFarmIncome() {
		return GrossSelfEmploymentFarmIncome;
	}

	public void setGrossSelfEmploymentFarmIncome(Double value) {
		GrossSelfEmploymentFarmIncome = value;
	}

	private Double GrossSelfEmploymentOtherIncome;

	public Double getGrossSelfEmploymentOtherIncome() {
		return GrossSelfEmploymentOtherIncome;
	}

	public void setGrossSelfEmploymentOtherIncome(Double value) {
		GrossSelfEmploymentOtherIncome = value;
	}

	private Double GrossUnearnedIncome;

	public Double getGrossUnearnedIncome() {
		return GrossUnearnedIncome;
	}

	public void setGrossUnearnedIncome(Double value) {
		GrossUnearnedIncome = value;
	}

	private Double IncurredMedicalExpenseAmount;

	public Double getIncurredMedicalExpenseAmount() {
		return IncurredMedicalExpenseAmount;
	}

	public void setIncurredMedicalExpenseAmount(Double value) {
		IncurredMedicalExpenseAmount = value;
	}

	private Double InKindIncome;

	public Double getInKindIncome() {
		return InKindIncome;
	}

	public void setInKindIncome(Double value) {
		InKindIncome = value;
	}

	private Double InsurancePremiumAmount;

	public Double getInsurancePremiumAmount() {
		return InsurancePremiumAmount;
	}

	public void setInsurancePremiumAmount(Double value) {
		InsurancePremiumAmount = value;
	}

	private Double IRWExpenseAmount;

	public Double getIRWExpenseAmount() {
		return IRWExpenseAmount;
	}

	public void setIRWExpenseAmount(Double value) {
		IRWExpenseAmount = value;
	}

	private Double MedicalExpenseAmount;

	public Double getMedicalExpenseAmount() {
		return MedicalExpenseAmount;
	}

	public void setMedicalExpenseAmount(Double value) {
		MedicalExpenseAmount = value;
	}

	private Double MedicarePartBPremiumAmount;

	public Double getMedicarePartBPremiumAmount() {
		return MedicarePartBPremiumAmount;
	}

	public void setMedicarePartBPremiumAmount(Double value) {
		MedicarePartBPremiumAmount = value;
	}

	private Double NetEarnIncomeAmount;

	public Double getNetEarnIncomeAmount() {
		return NetEarnIncomeAmount;
	}

	public void setNetEarnIncomeAmount(Double value) {
		NetEarnIncomeAmount = value;
	}

	private Double NetIncomeAmount;

	public Double getNetIncomeAmount() {
		return NetIncomeAmount;
	}

	public void setNetIncomeAmount(Double value) {
		NetIncomeAmount = value;
	}

	private Double NumberOfParents;

	public Double getNumberOfParents() {
		return NumberOfParents;
	}

	public void setNumberOfParents(Double value) {
		NumberOfParents = value;
	}

	private Double OtherUnearnedIncome;

	public Double getOtherUnearnedIncome() {
		return OtherUnearnedIncome;
	}

	public void setOtherUnearnedIncome(Double value) {
		OtherUnearnedIncome = value;
	}

	private Double PersonalNeedsAllowanceAmount;

	public Double getPersonalNeedsAllowanceAmount() {
		return PersonalNeedsAllowanceAmount;
	}

	public void setPersonalNeedsAllowanceAmount(Double value) {
		PersonalNeedsAllowanceAmount = value;
	}

	private Double RailRoadRetirementIncome;

	public Double getRailRoadRetirementIncome() {
		return RailRoadRetirementIncome;
	}

	public void setRailRoadRetirementIncome(Double value) {
		RailRoadRetirementIncome = value;
	}

	private Double ResourceIncomeAmount;

	public Double getResourceIncomeAmount() {
		return ResourceIncomeAmount;
	}

	public void setResourceIncomeAmount(Double value) {
		ResourceIncomeAmount = value;
	}

	private Double ResourceProducedIncome;

	public Double getResourceProducedIncome() {
		return ResourceProducedIncome;
	}

	public void setResourceProducedIncome(Double value) {
		ResourceProducedIncome = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private Double RSDIIncome;

	public Double getRSDIIncome() {
		return RSDIIncome;
	}

	public void setRSDIIncome(Double value) {
		RSDIIncome = value;
	}

	private Double ShelterExpenseAmount;

	public Double getShelterExpenseAmount() {
		return ShelterExpenseAmount;
	}

	public void setShelterExpenseAmount(Double value) {
		ShelterExpenseAmount = value;
	}

	private Double SSIIncome;

	public Double getSSIIncome() {
		return SSIIncome;
	}

	public void setSSIIncome(Double value) {
		SSIIncome = value;
	}

	private Double ThirdPartyIncomeAmount;

	public Double getThirdPartyIncomeAmount() {
		return ThirdPartyIncomeAmount;
	}

	public void setThirdPartyIncomeAmount(Double value) {
		ThirdPartyIncomeAmount = value;
	}

	private Double TotalIncomeDepositedInQIT;

	public Double getTotalIncomeDepositedInQIT() {
		return TotalIncomeDepositedInQIT;
	}

	public void setTotalIncomeDepositedInQIT(Double value) {
		TotalIncomeDepositedInQIT = value;
	}

	private Double UnemploymentInsuranceBenefitIncome;

	public Double getUnemploymentInsuranceBenefitIncome() {
		return UnemploymentInsuranceBenefitIncome;
	}

	public void setUnemploymentInsuranceBenefitIncome(Double value) {
		UnemploymentInsuranceBenefitIncome = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

	private Double UtilityExpenseAmount;

	public Double getUtilityExpenseAmount() {
		return UtilityExpenseAmount;
	}

	public void setUtilityExpenseAmount(Double value) {
		UtilityExpenseAmount = value;
	}

	private Double VeteranCompensationIncome;

	public Double getVeteranCompensationIncome() {
		return VeteranCompensationIncome;
	}

	public void setVeteranCompensationIncome(Double value) {
		VeteranCompensationIncome = value;
	}

	private Double VeteranPensionIncome;

	public Double getVeteranPensionIncome() {
		return VeteranPensionIncome;
	}

	public void setVeteranPensionIncome(Double value) {
		VeteranPensionIncome = value;
	}

	private Double WorkersCompensationIncome;

	public Double getWorkersCompensationIncome() {
		return WorkersCompensationIncome;
	}

	public void setWorkersCompensationIncome(Double value) {
		WorkersCompensationIncome = value;
	}

}
