//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class EligibilityVerificationChecklistModel {

	private Long CaseNumber;

	public Long getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Long value) {
		CaseNumber = value;
	}

	private int EdgNumber;

	public int getEdgNumber() {
		return EdgNumber;
	}

	public void setEdgNumber(int value) {
		EdgNumber = value;
	}

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private String VerificationCheckListDetailReference = "";

	public String getVerificationCheckListDetailReference() {
		return VerificationCheckListDetailReference;
	}

	public void setVerificationCheckListDetailReference(String value) {
		VerificationCheckListDetailReference = value;
	}

	private String VerificationCheckListTypeCode = "";

	public String getVerificationCheckListTypeCode() {
		return VerificationCheckListTypeCode;
	}

	public void setVerificationCheckListTypeCode(String value) {
		VerificationCheckListTypeCode = value;
	}

	private LocalDateTime EffectiveBeginDate;

	public LocalDateTime getEffectiveBeginDate() {
		return EffectiveBeginDate;
	}

	public void setEffectiveBeginDate(LocalDateTime value) {
		EffectiveBeginDate = value;
	}

	private String ActivityType = "";

	public String getActivityType() {
		return ActivityType;
	}

	public void setActivityType(String value) {
		ActivityType = value;
	}

	private String AdditionalParameters = "";

	public String getAdditionalParameters() {
		return AdditionalParameters;
	}

	public void setAdditionalParameters(String value) {
		AdditionalParameters = value;
	}

	private String AdditionalReason = "";

	public String getAdditionalReason() {
		return AdditionalReason;
	}

	public void setAdditionalReason(String value) {
		AdditionalReason = value;
	}

	private LocalDateTime ArchiveDate;

	public LocalDateTime getArchiveDate() {
		return ArchiveDate;
	}

	public void setArchiveDate(LocalDateTime value) {
		ArchiveDate = value;
	}

	private LocalDateTime BusinessVCLDueDate;

	public LocalDateTime getBusinessVCLDueDate() {
		return BusinessVCLDueDate;
	}

	public void setBusinessVCLDueDate(LocalDateTime value) {
		BusinessVCLDueDate = value;
	}

	private LocalDateTime CooperationDate;

	public LocalDateTime getCooperationDate() {
		return CooperationDate;
	}

	public void setCooperationDate(LocalDateTime value) {
		CooperationDate = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String DataCollectionId = "";

	public String getDataCollectionId() {
		return DataCollectionId;
	}

	public void setDataCollectionId(String value) {
		DataCollectionId = value;
	}

	private LocalDateTime DataCollectionRecordBeginDate;

	public LocalDateTime getDataCollectionRecordBeginDate() {
		return DataCollectionRecordBeginDate;
	}

	public void setDataCollectionRecordBeginDate(LocalDateTime value) {
		DataCollectionRecordBeginDate = value;
	}

	private LocalDateTime DataCollectionRecordEndDate;

	public LocalDateTime getDataCollectionRecordEndDate() {
		return DataCollectionRecordEndDate;
	}

	public void setDataCollectionRecordEndDate(LocalDateTime value) {
		DataCollectionRecordEndDate = value;
	}

	private LocalDateTime DataCollectionUpdateDate;

	public LocalDateTime getDataCollectionUpdateDate() {
		return DataCollectionUpdateDate;
	}

	public void setDataCollectionUpdateDate(LocalDateTime value) {
		DataCollectionUpdateDate = value;
	}

	private LocalDateTime DateLastUpdated;

	public LocalDateTime getDateLastUpdated() {
		return DateLastUpdated;
	}

	public void setDateLastUpdated(LocalDateTime value) {
		DateLastUpdated = value;
	}

	private String DeleteBySupervisorIndicator = "";

	public String getDeleteBySupervisorIndicator() {
		return DeleteBySupervisorIndicator;
	}

	public void setDeleteBySupervisorIndicator(String value) {
		DeleteBySupervisorIndicator = value;
	}

	private String DisplayItemCode = "";

	public String getDisplayItemCode() {
		return DisplayItemCode;
	}

	public void setDisplayItemCode(String value) {
		DisplayItemCode = value;
	}

	private String DisplayReferenceTableName = "";

	public String getDisplayReferenceTableName() {
		return DisplayReferenceTableName;
	}

	public void setDisplayReferenceTableName(String value) {
		DisplayReferenceTableName = value;
	}

	private LocalDateTime DispositionDate;

	public LocalDateTime getDispositionDate() {
		return DispositionDate;
	}

	public void setDispositionDate(LocalDateTime value) {
		DispositionDate = value;
	}

	private Integer DispositionTransactionId;

	public Integer getDispositionTransactionId() {
		return DispositionTransactionId;
	}

	public void setDispositionTransactionId(Integer value) {
		DispositionTransactionId = value;
	}

	private String DueDateReason = "";

	public String getDueDateReason() {
		return DueDateReason;
	}

	public void setDueDateReason(String value) {
		DueDateReason = value;
	}

	private LocalDateTime EffectiveEndDate;

	public LocalDateTime getEffectiveEndDate() {
		return EffectiveEndDate;
	}

	public void setEffectiveEndDate(LocalDateTime value) {
		EffectiveEndDate = value;
	}

	private Integer EligibilityTransactionId;

	public Integer getEligibilityTransactionId() {
		return EligibilityTransactionId;
	}

	public void setEligibilityTransactionId(Integer value) {
		EligibilityTransactionId = value;
	}

	private Integer EligibilityVerificationChecklistId;

	public Integer getEligibilityVerificationChecklistId() {
		return EligibilityVerificationChecklistId;
	}

	public void setEligibilityVerificationChecklistId(Integer value) {
		EligibilityVerificationChecklistId = value;
	}

	private String ExcludeForRFIDenial = "";

	public String getExcludeForRFIDenial() {
		return ExcludeForRFIDenial;
	}

	public void setExcludeForRFIDenial(String value) {
		ExcludeForRFIDenial = value;
	}

	private String ExtensionReasonCode = "";

	public String getExtensionReasonCode() {
		return ExtensionReasonCode;
	}

	public void setExtensionReasonCode(String value) {
		ExtensionReasonCode = value;
	}

	private String GroupIndicator = "";

	public String getGroupIndicator() {
		return GroupIndicator;
	}

	public void setGroupIndicator(String value) {
		GroupIndicator = value;
	}

	private String HistoryNavigatorIndicator = "";

	public String getHistoryNavigatorIndicator() {
		return HistoryNavigatorIndicator;
	}

	public void setHistoryNavigatorIndicator(String value) {
		HistoryNavigatorIndicator = value;
	}

	private double HistorySequence;

	public double getHistorySequence() {
		return HistorySequence;
	}

	public void setHistorySequence(double value) {
		HistorySequence = value;
	}

	private String HubVerificationStatus = "";

	public String getHubVerificationStatus() {
		return HubVerificationStatus;
	}

	public void setHubVerificationStatus(String value) {
		HubVerificationStatus = value;
	}

	private String IsCertifiable = "";

	public String getIsCertifiable() {
		return IsCertifiable;
	}

	public void setIsCertifiable(String value) {
		IsCertifiable = value;
	}

	private String IsComputerMatchRFI = "";

	public String getIsComputerMatchRFI() {
		return IsComputerMatchRFI;
	}

	public void setIsComputerMatchRFI(String value) {
		IsComputerMatchRFI = value;
	}

	private String IsDelete = "";

	public String getIsDelete() {
		return IsDelete;
	}

	public void setIsDelete(String value) {
		IsDelete = value;
	}

	private String IsDisplayType = "";

	public String getIsDisplayType() {
		return IsDisplayType;
	}

	public void setIsDisplayType(String value) {
		IsDisplayType = value;
	}

	private String IsGeneratedForExemptedIncome = "";

	public String getIsGeneratedForExemptedIncome() {
		return IsGeneratedForExemptedIncome;
	}

	public void setIsGeneratedForExemptedIncome(String value) {
		IsGeneratedForExemptedIncome = value;
	}

	private String IsRenewalPeriodVCL = "";

	public String getIsRenewalPeriodVCL() {
		return IsRenewalPeriodVCL;
	}

	public void setIsRenewalPeriodVCL(String value) {
		IsRenewalPeriodVCL = value;
	}

	private String IsUntimelyRFI = "";

	public String getIsUntimelyRFI() {
		return IsUntimelyRFI;
	}

	public void setIsUntimelyRFI(String value) {
		IsUntimelyRFI = value;
	}

	private String IsVLPCascade = "";

	public String getIsVLPCascade() {
		return IsVLPCascade;
	}

	public void setIsVLPCascade(String value) {
		IsVLPCascade = value;
	}

	private String ParticipantsStatusCode = "";

	public String getParticipantsStatusCode() {
		return ParticipantsStatusCode;
	}

	public void setParticipantsStatusCode(String value) {
		ParticipantsStatusCode = value;
	}

	private String ProcessId = "";

	public String getProcessId() {
		return ProcessId;
	}

	public void setProcessId(String value) {
		ProcessId = value;
	}

	private String ProgramCode = "";

	public String getProgramCode() {
		return ProgramCode;
	}

	public void setProgramCode(String value) {
		ProgramCode = value;
	}

	private LocalDateTime ProgramRequestDate;

	public LocalDateTime getProgramRequestDate() {
		return ProgramRequestDate;
	}

	public void setProgramRequestDate(LocalDateTime value) {
		ProgramRequestDate = value;
	}

	private String ReferenceTableName = "";

	public String getReferenceTableName() {
		return ReferenceTableName;
	}

	public void setReferenceTableName(String value) {
		ReferenceTableName = value;
	}

	private LocalDateTime RFIActionDate;

	public LocalDateTime getRFIActionDate() {
		return RFIActionDate;
	}

	public void setRFIActionDate(LocalDateTime value) {
		RFIActionDate = value;
	}

	private String RFIIgnoreFlag = "";

	public String getRFIIgnoreFlag() {
		return RFIIgnoreFlag;
	}

	public void setRFIIgnoreFlag(String value) {
		RFIIgnoreFlag = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private String SourceReceiveType = "";

	public String getSourceReceiveType() {
		return SourceReceiveType;
	}

	public void setSourceReceiveType(String value) {
		SourceReceiveType = value;
	}

	private String SourceReferenceId = "";

	public String getSourceReferenceId() {
		return SourceReferenceId;
	}

	public void setSourceReferenceId(String value) {
		SourceReferenceId = value;
	}

	private String TypeOfAssistance = "";

	public String getTypeOfAssistance() {
		return TypeOfAssistance;
	}

	public void setTypeOfAssistance(String value) {
		TypeOfAssistance = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

	private LocalDateTime ValidSourceReceivedDate;

	public LocalDateTime getValidSourceReceivedDate() {
		return ValidSourceReceivedDate;
	}

	public void setValidSourceReceivedDate(LocalDateTime value) {
		ValidSourceReceivedDate = value;
	}

	private String ValidVerificationList = "";

	public String getValidVerificationList() {
		return ValidVerificationList;
	}

	public void setValidVerificationList(String value) {
		ValidVerificationList = value;
	}

	private String VCLDeleteReason = "";

	public String getVCLDeleteReason() {
		return VCLDeleteReason;
	}

	public void setVCLDeleteReason(String value) {
		VCLDeleteReason = value;
	}

	private String VCLDueDays = "";

	public String getVCLDueDays() {
		return VCLDueDays;
	}

	public void setVCLDueDays(String value) {
		VCLDueDays = value;
	}

	private Integer VCLReferenceNumber;

	public Integer getVCLReferenceNumber() {
		return VCLReferenceNumber;
	}

	public void setVCLReferenceNumber(Integer value) {
		VCLReferenceNumber = value;
	}

	private LocalDateTime VerificationCheckListDueDate;

	public LocalDateTime getVerificationCheckListDueDate() {
		return VerificationCheckListDueDate;
	}

	public void setVerificationCheckListDueDate(LocalDateTime value) {
		VerificationCheckListDueDate = value;
	}

	private LocalDateTime VerificationCheckListInitialDueDate;

	public LocalDateTime getVerificationCheckListInitialDueDate() {
		return VerificationCheckListInitialDueDate;
	}

	public void setVerificationCheckListInitialDueDate(LocalDateTime value) {
		VerificationCheckListInitialDueDate = value;
	}

	private LocalDateTime VerificationCheckListRequestDate;

	public LocalDateTime getVerificationCheckListRequestDate() {
		return VerificationCheckListRequestDate;
	}

	public void setVerificationCheckListRequestDate(LocalDateTime value) {
		VerificationCheckListRequestDate = value;
	}

	private String VerificationCheckListRiskLevelCode = "";

	public String getVerificationCheckListRiskLevelCode() {
		return VerificationCheckListRiskLevelCode;
	}

	public void setVerificationCheckListRiskLevelCode(String value) {
		VerificationCheckListRiskLevelCode = value;
	}

}
