//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class EmploymentDetailModel {

	private int EmploymentDetailId;

	public int getEmploymentDetailId() {
		return EmploymentDetailId;
	}

	public void setEmploymentDetailId(int value) {
		EmploymentDetailId = value;
	}

	private Integer AddressId;

	public Integer getAddressId() {
		return AddressId;
	}

	public void setAddressId(Integer value) {
		AddressId = value;
	}

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private LocalDateTime ClientBecameAwareDate;

	public LocalDateTime getClientBecameAwareDate() {
		return ClientBecameAwareDate;
	}

	public void setClientBecameAwareDate(LocalDateTime value) {
		ClientBecameAwareDate = value;
	}

	private LocalDateTime ClientReportedDate;

	public LocalDateTime getClientReportedDate() {
		return ClientReportedDate;
	}

	public void setClientReportedDate(LocalDateTime value) {
		ClientReportedDate = value;
	}

	private Integer ConversionEmploymentDetailId;

	public Integer getConversionEmploymentDetailId() {
		return ConversionEmploymentDetailId;
	}

	public void setConversionEmploymentDetailId(Integer value) {
		ConversionEmploymentDetailId = value;
	}

	private LocalDateTime ConversionIncomeDate;

	public LocalDateTime getConversionIncomeDate() {
		return ConversionIncomeDate;
	}

	public void setConversionIncomeDate(LocalDateTime value) {
		ConversionIncomeDate = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String EarnedIncomeTypeCode = "";

	public String getEarnedIncomeTypeCode() {
		return EarnedIncomeTypeCode;
	}

	public void setEarnedIncomeTypeCode(String value) {
		EarnedIncomeTypeCode = value;
	}

	private Integer Ein;

	public Integer getEin() {
		return Ein;
	}

	public void setEin(Integer value) {
		Ein = value;
	}

	private Double EmployeePremiumContribution;

	public Double getEmployeePremiumContribution() {
		return EmployeePremiumContribution;
	}

	public void setEmployeePremiumContribution(Double value) {
		EmployeePremiumContribution = value;
	}

	private String EmployerContactEmail = "";

	public String getEmployerContactEmail() {
		return EmployerContactEmail;
	}

	public void setEmployerContactEmail(String value) {
		EmployerContactEmail = value;
	}

	private String EmployerContactFirstName = "";

	public String getEmployerContactFirstName() {
		return EmployerContactFirstName;
	}

	public void setEmployerContactFirstName(String value) {
		EmployerContactFirstName = value;
	}

	private String EmployerContactLastName = "";

	public String getEmployerContactLastName() {
		return EmployerContactLastName;
	}

	public void setEmployerContactLastName(String value) {
		EmployerContactLastName = value;
	}

	private String EmployerContactMiddleName = "";

	public String getEmployerContactMiddleName() {
		return EmployerContactMiddleName;
	}

	public void setEmployerContactMiddleName(String value) {
		EmployerContactMiddleName = value;
	}

	private String EmployerContactName = "";

	public String getEmployerContactName() {
		return EmployerContactName;
	}

	public void setEmployerContactName(String value) {
		EmployerContactName = value;
	}

	private String EmployerContactPhoneExtension = "";

	public String getEmployerContactPhoneExtension() {
		return EmployerContactPhoneExtension;
	}

	public void setEmployerContactPhoneExtension(String value) {
		EmployerContactPhoneExtension = value;
	}

	private String EmployerContactPhoneNumber = "";

	public String getEmployerContactPhoneNumber() {
		return EmployerContactPhoneNumber;
	}

	public void setEmployerContactPhoneNumber(String value) {
		EmployerContactPhoneNumber = value;
	}

	private String EmployerName = "";

	public String getEmployerName() {
		return EmployerName;
	}

	public void setEmployerName(String value) {
		EmployerName = value;
	}

	private LocalDateTime EmploymentEndDate;

	public LocalDateTime getEmploymentEndDate() {
		return EmploymentEndDate;
	}

	public void setEmploymentEndDate(LocalDateTime value) {
		EmploymentEndDate = value;
	}

	private LocalDateTime EmploymentStartDate;

	public LocalDateTime getEmploymentStartDate() {
		return EmploymentStartDate;
	}

	public void setEmploymentStartDate(LocalDateTime value) {
		EmploymentStartDate = value;
	}

	private String EmploymentTypeCode = "";

	public String getEmploymentTypeCode() {
		return EmploymentTypeCode;
	}

	public void setEmploymentTypeCode(String value) {
		EmploymentTypeCode = value;
	}

	private String ExcludeForTwoMonths = "";

	public String getExcludeForTwoMonths() {
		return ExcludeForTwoMonths;
	}

	public void setExcludeForTwoMonths(String value) {
		ExcludeForTwoMonths = value;
	}

	private LocalDateTime ExpectedDateOfReturn;

	public LocalDateTime getExpectedDateOfReturn() {
		return ExpectedDateOfReturn;
	}

	public void setExpectedDateOfReturn(LocalDateTime value) {
		ExpectedDateOfReturn = value;
	}

	private Double FinalAmount;

	public Double getFinalAmount() {
		return FinalAmount;
	}

	public void setFinalAmount(Double value) {
		FinalAmount = value;
	}

	private LocalDateTime FinalPayDate;

	public LocalDateTime getFinalPayDate() {
		return FinalPayDate;
	}

	public void setFinalPayDate(LocalDateTime value) {
		FinalPayDate = value;
	}

	private LocalDateTime FirstPayDate;

	public LocalDateTime getFirstPayDate() {
		return FirstPayDate;
	}

	public void setFirstPayDate(LocalDateTime value) {
		FirstPayDate = value;
	}

	private String FrequencyCode = "";

	public String getFrequencyCode() {
		return FrequencyCode;
	}

	public void setFrequencyCode(String value) {
		FrequencyCode = value;
	}

	private LocalDateTime FutureEnrollmentDate;

	public LocalDateTime getFutureEnrollmentDate() {
		return FutureEnrollmentDate;
	}

	public void setFutureEnrollmentDate(LocalDateTime value) {
		FutureEnrollmentDate = value;
	}

	private String GoodCauseCode = "";

	public String getGoodCauseCode() {
		return GoodCauseCode;
	}

	public void setGoodCauseCode(String value) {
		GoodCauseCode = value;
	}

	private String GoodCauseVerificationCode = "";

	public String getGoodCauseVerificationCode() {
		return GoodCauseVerificationCode;
	}

	public void setGoodCauseVerificationCode(String value) {
		GoodCauseVerificationCode = value;
	}

	private String HasLostEmployment = "";

	public String getHasLostEmployment() {
		return HasLostEmployment;
	}

	public void setHasLostEmployment(String value) {
		HasLostEmployment = value;
	}

	private Byte HoursWorkedPerWeek;

	public Byte getHoursWorkedPerWeek() {
		return HoursWorkedPerWeek;
	}

	public void setHoursWorkedPerWeek(Byte value) {
		HoursWorkedPerWeek = value;
	}

	private LocalDateTime IncomeEndVerifiedDate;

	public LocalDateTime getIncomeEndVerifiedDate() {
		return IncomeEndVerifiedDate;
	}

	public void setIncomeEndVerifiedDate(LocalDateTime value) {
		IncomeEndVerifiedDate = value;
	}

	private LocalDateTime IncomeEndVerifiedOn;

	public LocalDateTime getIncomeEndVerifiedOn() {
		return IncomeEndVerifiedOn;
	}

	public void setIncomeEndVerifiedOn(LocalDateTime value) {
		IncomeEndVerifiedOn = value;
	}

	private Double IndividualContribution;

	public Double getIndividualContribution() {
		return IndividualContribution;
	}

	public void setIndividualContribution(Double value) {
		IndividualContribution = value;
	}

	private Integer IndividualReceivingCare;

	public Integer getIndividualReceivingCare() {
		return IndividualReceivingCare;
	}

	public void setIndividualReceivingCare(Integer value) {
		IndividualReceivingCare = value;
	}

	private String IsChangeReportedVerifiedTimely = "";

	public String getIsChangeReportedVerifiedTimely() {
		return IsChangeReportedVerifiedTimely;
	}

	public void setIsChangeReportedVerifiedTimely(String value) {
		IsChangeReportedVerifiedTimely = value;
	}

	private Boolean IsConversionIncome;

	public Boolean getIsConversionIncome() {
		return IsConversionIncome;
	}

	public void setIsConversionIncome(Boolean value) {
		IsConversionIncome = value;
	}

	private String IsCoveredNextYear = "";

	public String getIsCoveredNextYear() {
		return IsCoveredNextYear;
	}

	public void setIsCoveredNextYear(String value) {
		IsCoveredNextYear = value;
	}

	private String IsDependentCovered = "";

	public String getIsDependentCovered() {
		return IsDependentCovered;
	}

	public void setIsDependentCovered(String value) {
		IsDependentCovered = value;
	}

	private String IsEnrolled = "";

	public String getIsEnrolled() {
		return IsEnrolled;
	}

	public void setIsEnrolled(String value) {
		IsEnrolled = value;
	}

	private String IsHealthCoverage = "";

	public String getIsHealthCoverage() {
		return IsHealthCoverage;
	}

	public void setIsHealthCoverage(String value) {
		IsHealthCoverage = value;
	}

	private String IsIncomeReceivedForMember = "";

	public String getIsIncomeReceivedForMember() {
		return IsIncomeReceivedForMember;
	}

	public void setIsIncomeReceivedForMember(String value) {
		IsIncomeReceivedForMember = value;
	}

	private String IsIncomeSubsidized = "";

	public String getIsIncomeSubsidized() {
		return IsIncomeSubsidized;
	}

	public void setIsIncomeSubsidized(String value) {
		IsIncomeSubsidized = value;
	}

	private String IsIndividualOnStrike = "";

	public String getIsIndividualOnStrike() {
		return IsIndividualOnStrike;
	}

	public void setIsIndividualOnStrike(String value) {
		IsIndividualOnStrike = value;
	}

	private String IsNDNHSource = "";

	public String getIsNDNHSource() {
		return IsNDNHSource;
	}

	public void setIsNDNHSource(String value) {
		IsNDNHSource = value;
	}

	private String IsSourceBatchMatch = "";

	public String getIsSourceBatchMatch() {
		return IsSourceBatchMatch;
	}

	public void setIsSourceBatchMatch(String value) {
		IsSourceBatchMatch = value;
	}

	private String IsTemporarilyOnLeave = "";

	public String getIsTemporarilyOnLeave() {
		return IsTemporarilyOnLeave;
	}

	public void setIsTemporarilyOnLeave(String value) {
		IsTemporarilyOnLeave = value;
	}

	private String IsTimely = "";

	public String getIsTimely() {
		return IsTimely;
	}

	public void setIsTimely(String value) {
		IsTimely = value;
	}

	private LocalDateTime LastPayDate;

	public LocalDateTime getLastPayDate() {
		return LastPayDate;
	}

	public void setLastPayDate(LocalDateTime value) {
		LastPayDate = value;
	}

	private String LeaveReasonCode = "";

	public String getLeaveReasonCode() {
		return LeaveReasonCode;
	}

	public void setLeaveReasonCode(String value) {
		LeaveReasonCode = value;
	}

	private String LeaveVerificationCode = "";

	public String getLeaveVerificationCode() {
		return LeaveVerificationCode;
	}

	public void setLeaveVerificationCode(String value) {
		LeaveVerificationCode = value;
	}

	private String LossOfEmploymentReasonCode = "";

	public String getLossOfEmploymentReasonCode() {
		return LossOfEmploymentReasonCode;
	}

	public void setLossOfEmploymentReasonCode(String value) {
		LossOfEmploymentReasonCode = value;
	}

	private String LossOfEmploymentVerificationCode = "";

	public String getLossOfEmploymentVerificationCode() {
		return LossOfEmploymentVerificationCode;
	}

	public void setLossOfEmploymentVerificationCode(String value) {
		LossOfEmploymentVerificationCode = value;
	}

	private String LowestCostPlan = "";

	public String getLowestCostPlan() {
		return LowestCostPlan;
	}

	public void setLowestCostPlan(String value) {
		LowestCostPlan = value;
	}

	private String MecCd = "";

	public String getMecCd() {
		return MecCd;
	}

	public void setMecCd(String value) {
		MecCd = value;
	}

	private LocalDateTime NDNHChangeDate;

	public LocalDateTime getNDNHChangeDate() {
		return NDNHChangeDate;
	}

	public void setNDNHChangeDate(LocalDateTime value) {
		NDNHChangeDate = value;
	}

	private String PhoneExtension = "";

	public String getPhoneExtension() {
		return PhoneExtension;
	}

	public void setPhoneExtension(String value) {
		PhoneExtension = value;
	}

	private String PhoneNumber = "";

	public String getPhoneNumber() {
		return PhoneNumber;
	}

	public void setPhoneNumber(String value) {
		PhoneNumber = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private Double ThirtyAndOneThirdDeductionAmount;

	public Double getThirtyAndOneThirdDeductionAmount() {
		return ThirtyAndOneThirdDeductionAmount;
	}

	public void setThirtyAndOneThirdDeductionAmount(Double value) {
		ThirtyAndOneThirdDeductionAmount = value;
	}

	private LocalDateTime ThirtyAndOneThirdDeductionEndDate;

	public LocalDateTime getThirtyAndOneThirdDeductionEndDate() {
		return ThirtyAndOneThirdDeductionEndDate;
	}

	public void setThirtyAndOneThirdDeductionEndDate(LocalDateTime value) {
		ThirtyAndOneThirdDeductionEndDate = value;
	}

	private LocalDateTime ThirtyAndOneThirdDeductionStartDate;

	public LocalDateTime getThirtyAndOneThirdDeductionStartDate() {
		return ThirtyAndOneThirdDeductionStartDate;
	}

	public void setThirtyAndOneThirdDeductionStartDate(LocalDateTime value) {
		ThirtyAndOneThirdDeductionStartDate = value;
	}

	private Double ThirtyDollarDeductionAmount;

	public Double getThirtyDollarDeductionAmount() {
		return ThirtyDollarDeductionAmount;
	}

	public void setThirtyDollarDeductionAmount(Double value) {
		ThirtyDollarDeductionAmount = value;
	}

	private LocalDateTime ThirtyDollarDeductionEndDate;

	public LocalDateTime getThirtyDollarDeductionEndDate() {
		return ThirtyDollarDeductionEndDate;
	}

	public void setThirtyDollarDeductionEndDate(LocalDateTime value) {
		ThirtyDollarDeductionEndDate = value;
	}

	private LocalDateTime TwoMonthKtapExclusionStartDate;

	public LocalDateTime getTwoMonthKtapExclusionStartDate() {
		return TwoMonthKtapExclusionStartDate;
	}

	public void setTwoMonthKtapExclusionStartDate(LocalDateTime value) {
		TwoMonthKtapExclusionStartDate = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

	private LocalDateTime VerificationReceivedDate;

	public LocalDateTime getVerificationReceivedDate() {
		return VerificationReceivedDate;
	}

	public void setVerificationReceivedDate(LocalDateTime value) {
		VerificationReceivedDate = value;
	}

}
