//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class ESICoverageDetailModel {

	private int ESICoverageDetailId;

	public int getESICoverageDetailId() {
		return ESICoverageDetailId;
	}

	public void setESICoverageDetailId(int value) {
		ESICoverageDetailId = value;
	}

	private Integer EmployerId;

	public Integer getEmployerId() {
		return EmployerId;
	}

	public void setEmployerId(Integer value) {
		EmployerId = value;
	}

	private Integer HealthInsurancePolicyDetailId;

	public Integer getHealthInsurancePolicyDetailId() {
		return HealthInsurancePolicyDetailId;
	}

	public void setHealthInsurancePolicyDetailId(Integer value) {
		HealthInsurancePolicyDetailId = value;
	}

	private Long PotentialCoveredIndividualId;

	public Long getPotentialCoveredIndividualId() {
		return PotentialCoveredIndividualId;
	}

	public void setPotentialCoveredIndividualId(Long value) {
		PotentialCoveredIndividualId = value;
	}

	private Long PotentialPolicyHolderIndividualId;

	public Long getPotentialPolicyHolderIndividualId() {
		return PotentialPolicyHolderIndividualId;
	}

	public void setPotentialPolicyHolderIndividualId(Long value) {
		PotentialPolicyHolderIndividualId = value;
	}

	private LocalDateTime ChangeEffectiveDate;

	public LocalDateTime getChangeEffectiveDate() {
		return ChangeEffectiveDate;
	}

	public void setChangeEffectiveDate(LocalDateTime value) {
		ChangeEffectiveDate = value;
	}

	private LocalDateTime CoverageEndDate;

	public LocalDateTime getCoverageEndDate() {
		return CoverageEndDate;
	}

	public void setCoverageEndDate(LocalDateTime value) {
		CoverageEndDate = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private LocalDateTime EsiLastDayCoverageDate;

	public LocalDateTime getEsiLastDayCoverageDate() {
		return EsiLastDayCoverageDate;
	}

	public void setEsiLastDayCoverageDate(LocalDateTime value) {
		EsiLastDayCoverageDate = value;
	}

	private LocalDateTime ExpectedCoverageDate;

	public LocalDateTime getExpectedCoverageDate() {
		return ExpectedCoverageDate;
	}

	public void setExpectedCoverageDate(LocalDateTime value) {
		ExpectedCoverageDate = value;
	}

	private String ExpectingChangeInCoverageCode = "";

	public String getExpectingChangeInCoverageCode() {
		return ExpectingChangeInCoverageCode;
	}

	public void setExpectingChangeInCoverageCode(String value) {
		ExpectingChangeInCoverageCode = value;
	}

	private Integer InsuranceExternalPolicyHolderId;

	public Integer getInsuranceExternalPolicyHolderId() {
		return InsuranceExternalPolicyHolderId;
	}

	public void setInsuranceExternalPolicyHolderId(Integer value) {
		InsuranceExternalPolicyHolderId = value;
	}

	private String IsExpectingDropEsiCoverage = "";

	public String getIsExpectingDropEsiCoverage() {
		return IsExpectingDropEsiCoverage;
	}

	public void setIsExpectingDropEsiCoverage(String value) {
		IsExpectingDropEsiCoverage = value;
	}

	private String IsPlanningToEnrollInHealthPlan = "";

	public String getIsPlanningToEnrollInHealthPlan() {
		return IsPlanningToEnrollInHealthPlan;
	}

	public void setIsPlanningToEnrollInHealthPlan(String value) {
		IsPlanningToEnrollInHealthPlan = value;
	}

	private Integer KHIPPCNX;

	public Integer getKHIPPCNX() {
		return KHIPPCNX;
	}

	public void setKHIPPCNX(Integer value) {
		KHIPPCNX = value;
	}

	private String NewPayFrequencyCode = "";

	public String getNewPayFrequencyCode() {
		return NewPayFrequencyCode;
	}

	public void setNewPayFrequencyCode(String value) {
		NewPayFrequencyCode = value;
	}

	private Double NewPremiumAmount;

	public Double getNewPremiumAmount() {
		return NewPremiumAmount;
	}

	public void setNewPremiumAmount(Double value) {
		NewPremiumAmount = value;
	}

	private String PayFrequencyCode = "";

	public String getPayFrequencyCode() {
		return PayFrequencyCode;
	}

	public void setPayFrequencyCode(String value) {
		PayFrequencyCode = value;
	}

	private Double PremiumAmount;

	public Double getPremiumAmount() {
		return PremiumAmount;
	}

	public void setPremiumAmount(Double value) {
		PremiumAmount = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
