//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class ETPAbawdEffectiveDateModel {

	private int ETPAbawdEffectiveDatesId;

	public int getETPAbawdEffectiveDatesId() {
		return ETPAbawdEffectiveDatesId;
	}

	public void setETPAbawdEffectiveDatesId(int value) {
		ETPAbawdEffectiveDatesId = value;
	}

	private String CountyType = "";

	public String getCountyType() {
		return CountyType;
	}

	public void setCountyType(String value) {
		CountyType = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	 private LocalDateTime EffectiveBeginDate;

	public LocalDateTime getEffectiveBeginDate() {
		return EffectiveBeginDate;
	}

	public void setEffectiveBeginDate(LocalDateTime value) {
		EffectiveBeginDate = value;
	}

	 private LocalDateTime EffectiveEndDate;

	public LocalDateTime getEffectiveEndDate() {
		return EffectiveEndDate;
	}

	public void setEffectiveEndDate(LocalDateTime value) {
		EffectiveEndDate = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
