//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class ETPCureModel {

	private int ETPCureId;

	public int getETPCureId() {
		return ETPCureId;
	}

	public void setETPCureId(int value) {
		ETPCureId = value;
	}

	private Integer ABAWDMonthTrackingId;

	public Integer getABAWDMonthTrackingId() {
		return ABAWDMonthTrackingId;
	}

	public void setABAWDMonthTrackingId(Integer value) {
		ABAWDMonthTrackingId = value;
	}

	private Long IndividualId;

	public Long getIndividualId() {
		return IndividualId;
	}

	public void setIndividualId(Long value) {
		IndividualId = value;
	}

	private String Comment = "";

	public String getComment() {
		return Comment;
	}

	public void setComment(String value) {
		Comment = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private LocalDateTime CureDate;

	public LocalDateTime getCureDate() {
		return CureDate;
	}

	public void setCureDate(LocalDateTime value) {
		CureDate = value;
	}

	private String CureType = "";

	public String getCureType() {
		return CureType;
	}

	public void setCureType(String value) {
		CureType = value;
	}

	private String CureVerification = "";

	public String getCureVerification() {
		return CureVerification;
	}

	public void setCureVerification(String value) {
		CureVerification = value;
	}

	private LocalDateTime DiscontinuanceEndDate;

	public LocalDateTime getDiscontinuanceEndDate() {
		return DiscontinuanceEndDate;
	}

	public void setDiscontinuanceEndDate(LocalDateTime value) {
		DiscontinuanceEndDate = value;
	}

	private LocalDateTime DiscontinuanceStartDate;

	public LocalDateTime getDiscontinuanceStartDate() {
		return DiscontinuanceStartDate;
	}

	public void setDiscontinuanceStartDate(LocalDateTime value) {
		DiscontinuanceStartDate = value;
	}

	private Integer DisqualificationId;

	public Integer getDisqualificationId() {
		return DisqualificationId;
	}

	public void setDisqualificationId(Integer value) {
		DisqualificationId = value;
	}

	private LocalDateTime InitiateContactMadeDate;

	public LocalDateTime getInitiateContactMadeDate() {
		return InitiateContactMadeDate;
	}

	public void setInitiateContactMadeDate(LocalDateTime value) {
		InitiateContactMadeDate = value;
	}

	private String Is30DayActivityCompleted = "";

	public String getIs30DayActivityCompleted() {
		return Is30DayActivityCompleted;
	}

	public void setIs30DayActivityCompleted(String value) {
		Is30DayActivityCompleted = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
