//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class ExpansionPenaltyDetailModel {

	private int ExpansionPenaltyDetailId;

	public int getExpansionPenaltyDetailId() {
		return ExpansionPenaltyDetailId;
	}

	public void setExpansionPenaltyDetailId(int value) {
		ExpansionPenaltyDetailId = value;
	}

	private Integer BenefitMonth;

	public Integer getBenefitMonth() {
		return BenefitMonth;
	}

	public void setBenefitMonth(Integer value) {
		BenefitMonth = value;
	}

	private LocalDateTime CEHoursCompletedDate;

	public LocalDateTime getCEHoursCompletedDate() {
		return CEHoursCompletedDate;
	}

	public void setCEHoursCompletedDate(LocalDateTime value) {
		CEHoursCompletedDate = value;
	}

	private String CEHoursCompletionStatus = "";

	public String getCEHoursCompletionStatus() {
		return CEHoursCompletionStatus;
	}

	public void setCEHoursCompletionStatus(String value) {
		CEHoursCompletionStatus = value;
	}

	private LocalDateTime CourseCompletionDate;

	public LocalDateTime getCourseCompletionDate() {
		return CourseCompletionDate;
	}

	public void setCourseCompletionDate(LocalDateTime value) {
		CourseCompletionDate = value;
	}

	private String CourseDetail = "";

	public String getCourseDetail() {
		return CourseDetail;
	}

	public void setCourseDetail(String value) {
		CourseDetail = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private LocalDateTime CureDate;

	public LocalDateTime getCureDate() {
		return CureDate;
	}

	public void setCureDate(LocalDateTime value) {
		CureDate = value;
	}

	private String CureReason = "";

	public String getCureReason() {
		return CureReason;
	}

	public void setCureReason(String value) {
		CureReason = value;
	}

	private LocalDateTime DebtClearedDate;

	public LocalDateTime getDebtClearedDate() {
		return DebtClearedDate;
	}

	public void setDebtClearedDate(LocalDateTime value) {
		DebtClearedDate = value;
	}

	private String DueMonths = "";

	public String getDueMonths() {
		return DueMonths;
	}

	public void setDueMonths(String value) {
		DueMonths = value;
	}

	private LocalDateTime EffectiveBeginDate;

	public LocalDateTime getEffectiveBeginDate() {
		return EffectiveBeginDate;
	}

	public void setEffectiveBeginDate(LocalDateTime value) {
		EffectiveBeginDate = value;
	}

	private LocalDateTime EffectiveEndDate;

	public LocalDateTime getEffectiveEndDate() {
		return EffectiveEndDate;
	}

	public void setEffectiveEndDate(LocalDateTime value) {
		EffectiveEndDate = value;
	}

	private String GoodCauseReasonCode = "";

	public String getGoodCauseReasonCode() {
		return GoodCauseReasonCode;
	}

	public void setGoodCauseReasonCode(String value) {
		GoodCauseReasonCode = value;
	}

	private String GoodCauseVerificationCode = "";

	public String getGoodCauseVerificationCode() {
		return GoodCauseVerificationCode;
	}

	public void setGoodCauseVerificationCode(String value) {
		GoodCauseVerificationCode = value;
	}

	private Double HoursCompleted;

	public Double getHoursCompleted() {
		return HoursCompleted;
	}

	public void setHoursCompleted(Double value) {
		HoursCompleted = value;
	}

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private String IsDebtCleared = "";

	public String getIsDebtCleared() {
		return IsDebtCleared;
	}

	public void setIsDebtCleared(String value) {
		IsDebtCleared = value;
	}

	private String IsDelete = "";

	public String getIsDelete() {
		return IsDelete;
	}

	public void setIsDelete(String value) {
		IsDelete = value;
	}

	private String IsPotentialPenalty = "";

	public String getIsPotentialPenalty() {
		return IsPotentialPenalty;
	}

	public void setIsPotentialPenalty(String value) {
		IsPotentialPenalty = value;
	}

	private String Isvalid = "";

	public String getIsvalid() {
		return Isvalid;
	}

	public void setIsvalid(String value) {
		Isvalid = value;
	}

	private Long HBEHealthTransactionId;

	public Long getHBEHealthTransactionId() {
		return HBEHealthTransactionId;
	}

	public void setHBEHealthTransactionId(Long value) {
		HBEHealthTransactionId = value;
	}

	private Integer PaymentTrackingId;

	public Integer getPaymentTrackingId() {
		return PaymentTrackingId;
	}

	public void setPaymentTrackingId(Integer value) {
		PaymentTrackingId = value;
	}

	private LocalDateTime PenaltyCureActionDate;

	public LocalDateTime getPenaltyCureActionDate() {
		return PenaltyCureActionDate;
	}

	public void setPenaltyCureActionDate(LocalDateTime value) {
		PenaltyCureActionDate = value;
	}

	private String PenaltyDeductionCode = "";

	public String getPenaltyDeductionCode() {
		return PenaltyDeductionCode;
	}

	public void setPenaltyDeductionCode(String value) {
		PenaltyDeductionCode = value;
	}

	private int PenaltyId;

	public int getPenaltyId() {
		return PenaltyId;
	}

	public void setPenaltyId(int value) {
		PenaltyId = value;
	}

	private String PenaltyType = "";

	public String getPenaltyType() {
		return PenaltyType;
	}

	public void setPenaltyType(String value) {
		PenaltyType = value;
	}

	private String ReferenceIncomeList = "";

	public String getReferenceIncomeList() {
		return ReferenceIncomeList;
	}

	public void setReferenceIncomeList(String value) {
		ReferenceIncomeList = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private String StatusIndicator = "";

	public String getStatusIndicator() {
		return StatusIndicator;
	}

	public void setStatusIndicator(String value) {
		StatusIndicator = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
