//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class IncomePayDetailModel {

	private int IncomePayDetailId;

	public int getIncomePayDetailId() {
		return IncomePayDetailId;
	}

	public void setIncomePayDetailId(int value) {
		IncomePayDetailId = value;
	}

	private String Comments = "";

	public String getComments() {
		return Comments;
	}

	public void setComments(String value) {
		Comments = value;
	}

	private Double Commission;

	public Double getCommission() {
		return Commission;
	}

	public void setCommission(Double value) {
		Commission = value;
	}

	 private LocalDateTime ContractEndDate;

	public LocalDateTime getContractEndDate() {
		return ContractEndDate;
	}

	public void setContractEndDate(LocalDateTime value) {
		ContractEndDate = value;
	}

	 private LocalDateTime ContractStartDate;

	public LocalDateTime getContractStartDate() {
		return ContractStartDate;
	}

	public void setContractStartDate(LocalDateTime value) {
		ContractStartDate = value;
	}

	private Integer ConversionIncomePayDetailId;

	public Integer getConversionIncomePayDetailId() {
		return ConversionIncomePayDetailId;
	}

	public void setConversionIncomePayDetailId(Integer value) {
		ConversionIncomePayDetailId = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private Double ExcludedPayAmount;

	public Double getExcludedPayAmount() {
		return ExcludedPayAmount;
	}

	public void setExcludedPayAmount(Double value) {
		ExcludedPayAmount = value;
	}

	private String ExcludedPayReasonCode = "";

	public String getExcludedPayReasonCode() {
		return ExcludedPayReasonCode;
	}

	public void setExcludedPayReasonCode(String value) {
		ExcludedPayReasonCode = value;
	}

	private String ExclusionReasonVerificationCode = "";

	public String getExclusionReasonVerificationCode() {
		return ExclusionReasonVerificationCode;
	}

	public void setExclusionReasonVerificationCode(String value) {
		ExclusionReasonVerificationCode = value;
	}

	private Double ExpenseAmoutPerFrequency;

	public Double getExpenseAmoutPerFrequency() {
		return ExpenseAmoutPerFrequency;
	}

	public void setExpenseAmoutPerFrequency(Double value) {
		ExpenseAmoutPerFrequency = value;
	}

	private Double GrossPaymentAmount;

	public Double getGrossPaymentAmount() {
		return GrossPaymentAmount;
	}

	public void setGrossPaymentAmount(Double value) {
		GrossPaymentAmount = value;
	}

	private Double GrossUnearnedIncomeAmount;

	public Double getGrossUnearnedIncomeAmount() {
		return GrossUnearnedIncomeAmount;
	}

	public void setGrossUnearnedIncomeAmount(Double value) {
		GrossUnearnedIncomeAmount = value;
	}

	private Double HourlyPayRate;

	public Double getHourlyPayRate() {
		return HourlyPayRate;
	}

	public void setHourlyPayRate(Double value) {
		HourlyPayRate = value;
	}

	private Double HoursPaidFor;

	public Double getHoursPaidFor() {
		return HoursPaidFor;
	}

	public void setHoursPaidFor(Double value) {
		HoursPaidFor = value;
	}

	private Double HoursPerWeek;

	public Double getHoursPerWeek() {
		return HoursPerWeek;
	}

	public void setHoursPerWeek(Double value) {
		HoursPerWeek = value;
	}

	private String IncludeInProjections = "";

	public String getIncludeInProjections() {
		return IncludeInProjections;
	}

	public void setIncludeInProjections(String value) {
		IncludeInProjections = value;
	}

	private String IncomePayTypeCode = "";

	public String getIncomePayTypeCode() {
		return IncomePayTypeCode;
	}

	public void setIncomePayTypeCode(String value) {
		IncomePayTypeCode = value;
	}

	private String IsActive = "";

	public String getIsActive() {
		return IsActive;
	}

	public void setIsActive(String value) {
		IsActive = value;
	}

	private Boolean IsAnticipatedPayStub;

	public Boolean getIsAnticipatedPayStub() {
		return IsAnticipatedPayStub;
	}

	public void setIsAnticipatedPayStub(Boolean value) {
		IsAnticipatedPayStub = value;
	}

	private String IsFederalVerified = "";

	public String getIsFederalVerified() {
		return IsFederalVerified;
	}

	public void setIsFederalVerified(String value) {
		IsFederalVerified = value;
	}

	private String IsManuallyVerified = "";

	public String getIsManuallyVerified() {
		return IsManuallyVerified;
	}

	public void setIsManuallyVerified(String value) {
		IsManuallyVerified = value;
	}

	private String IsPayForPartialAmount = "";

	public String getIsPayForPartialAmount() {
		return IsPayForPartialAmount;
	}

	public void setIsPayForPartialAmount(String value) {
		IsPayForPartialAmount = value;
	}

	private Double KtapGrossPaymentAmount;

	public Double getKtapGrossPaymentAmount() {
		return KtapGrossPaymentAmount;
	}

	public void setKtapGrossPaymentAmount(Double value) {
		KtapGrossPaymentAmount = value;
	}

	 private LocalDateTime LastMonthForIncome;

	public LocalDateTime getLastMonthForIncome() {
		return LastMonthForIncome;
	}

	public void setLastMonthForIncome(LocalDateTime value) {
		LastMonthForIncome = value;
	}

	private Double MagiGrossPaymentAmount;

	public Double getMagiGrossPaymentAmount() {
		return MagiGrossPaymentAmount;
	}

	public void setMagiGrossPaymentAmount(Double value) {
		MagiGrossPaymentAmount = value;
	}

	private Double NetAmountPerFrequency;

	public Double getNetAmountPerFrequency() {
		return NetAmountPerFrequency;
	}

	public void setNetAmountPerFrequency(Double value) {
		NetAmountPerFrequency = value;
	}

	private Double NonMagiAdultMaGrossPaymentAmount;

	public Double getNonMagiAdultMaGrossPaymentAmount() {
		return NonMagiAdultMaGrossPaymentAmount;
	}

	public void setNonMagiAdultMaGrossPaymentAmount(Double value) {
		NonMagiAdultMaGrossPaymentAmount = value;
	}

	private Double NonMagiFamilyGrossPaymentAmount;

	public Double getNonMagiFamilyGrossPaymentAmount() {
		return NonMagiFamilyGrossPaymentAmount;
	}

	public void setNonMagiFamilyGrossPaymentAmount(Double value) {
		NonMagiFamilyGrossPaymentAmount = value;
	}

	private Byte NumberOfMonthsIntended;

	public Byte getNumberOfMonthsIntended() {
		return NumberOfMonthsIntended;
	}

	public void setNumberOfMonthsIntended(Byte value) {
		NumberOfMonthsIntended = value;
	}

	private Double OtherPayAmount;

	public Double getOtherPayAmount() {
		return OtherPayAmount;
	}

	public void setOtherPayAmount(Double value) {
		OtherPayAmount = value;
	}

	 private LocalDateTime PayDate;

	public LocalDateTime getPayDate() {
		return PayDate;
	}

	public void setPayDate(LocalDateTime value) {
		PayDate = value;
	}

	private String PayFrequency = "";

	public String getPayFrequency() {
		return PayFrequency;
	}

	public void setPayFrequency(String value) {
		PayFrequency = value;
	}

	private String PayIndicator = "";

	public String getPayIndicator() {
		return PayIndicator;
	}

	public void setPayIndicator(String value) {
		PayIndicator = value;
	}

	private String PaystubExclusionReason = "";

	public String getPaystubExclusionReason() {
		return PaystubExclusionReason;
	}

	public void setPaystubExclusionReason(String value) {
		PaystubExclusionReason = value;
	}

	private String PayVerificationCode = "";

	public String getPayVerificationCode() {
		return PayVerificationCode;
	}

	public void setPayVerificationCode(String value) {
		PayVerificationCode = value;
	}

	 private LocalDateTime PayVerificationDate;

	public LocalDateTime getPayVerificationDate() {
		return PayVerificationDate;
	}

	public void setPayVerificationDate(LocalDateTime value) {
		PayVerificationDate = value;
	}

	private String R4PayVerificationCode = "";

	public String getR4PayVerificationCode() {
		return R4PayVerificationCode;
	}

	public void setR4PayVerificationCode(String value) {
		R4PayVerificationCode = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private Integer SelfEmploymentScheduleDetailId;

	public Integer getSelfEmploymentScheduleDetailId() {
		return SelfEmploymentScheduleDetailId;
	}

	public void setSelfEmploymentScheduleDetailId(Integer value) {
		SelfEmploymentScheduleDetailId = value;
	}

	private Double SnapGrossPaymentAmount;

	public Double getSnapGrossPaymentAmount() {
		return SnapGrossPaymentAmount;
	}

	public void setSnapGrossPaymentAmount(Double value) {
		SnapGrossPaymentAmount = value;
	}

	private Double TipsPerFrequency;

	public Double getTipsPerFrequency() {
		return TipsPerFrequency;
	}

	public void setTipsPerFrequency(Double value) {
		TipsPerFrequency = value;
	}

	private Double TotalGrossAmount;

	public Double getTotalGrossAmount() {
		return TotalGrossAmount;
	}

	public void setTotalGrossAmount(Double value) {
		TotalGrossAmount = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
