//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class IncreaseCommunitySpouseIncomeModel {

	private int IncreaseCommunitySpouseIncomeId;

	public int getIncreaseCommunitySpouseIncomeId() {
		return IncreaseCommunitySpouseIncomeId;
	}

	public void setIncreaseCommunitySpouseIncomeId(int value) {
		IncreaseCommunitySpouseIncomeId = value;
	}

	private Long CaseNumber;

	public Long getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Long value) {
		CaseNumber = value;
	}

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String IncomeVerificationCode = "";

	public String getIncomeVerificationCode() {
		return IncomeVerificationCode;
	}

	public void setIncomeVerificationCode(String value) {
		IncomeVerificationCode = value;
	}

	private double IncreasedAmount;

	public double getIncreasedAmount() {
		return IncreasedAmount;
	}

	public void setIncreasedAmount(double value) {
		IncreasedAmount = value;
	}

	private LocalDateTime IncreaseEndDate;

	public LocalDateTime getIncreaseEndDate() {
		return IncreaseEndDate;
	}

	public void setIncreaseEndDate(LocalDateTime value) {
		IncreaseEndDate = value;
	}

	private LocalDateTime IncreaseStartDate;

	public LocalDateTime getIncreaseStartDate() {
		return IncreaseStartDate;
	}

	public void setIncreaseStartDate(LocalDateTime value) {
		IncreaseStartDate = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
