//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class IndividualLowestCostEmployerPlanModel {

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private String EmployerId = "";

	public String getEmployerId() {
		return EmployerId;
	}

	public void setEmployerId(String value) {
		EmployerId = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String IsPlanOffered = "";

	public String getIsPlanOffered() {
		return IsPlanOffered;
	}

	public void setIsPlanOffered(String value) {
		IsPlanOffered = value;
	}

	private Double LowestPlanPreimumAmount;

	public Double getLowestPlanPreimumAmount() {
		return LowestPlanPreimumAmount;
	}

	public void setLowestPlanPreimumAmount(Double value) {
		LowestPlanPreimumAmount = value;
	}

	private Integer PlanIssuerId;

	public Integer getPlanIssuerId() {
		return PlanIssuerId;
	}

	public void setPlanIssuerId(Integer value) {
		PlanIssuerId = value;
	}

	private String PlanIssuerName = "";

	public String getPlanIssuerName() {
		return PlanIssuerName;
	}

	public void setPlanIssuerName(String value) {
		PlanIssuerName = value;
	}

	private String PlanName = "";

	public String getPlanName() {
		return PlanName;
	}

	public void setPlanName(String value) {
		PlanName = value;
	}

	private String PlanType = "";

	public String getPlanType() {
		return PlanType;
	}

	public void setPlanType(String value) {
		PlanType = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
