//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class IndividualLivingArrangementModel {

	private int IndividualLivingArrangementId;

	public int getIndividualLivingArrangementId() {
		return IndividualLivingArrangementId;
	}

	public void setIndividualLivingArrangementId(int value) {
		IndividualLivingArrangementId = value;
	}

	private Integer DCIndividualLongTermCareId;

	public Integer getDCIndividualLongTermCareId() {
		return DCIndividualLongTermCareId;
	}

	public void setDCIndividualLongTermCareId(Integer value) {
		DCIndividualLongTermCareId = value;
	}

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private LocalDateTime AbsentStartDate;

	public LocalDateTime getAbsentStartDate() {
		return AbsentStartDate;
	}

	public void setAbsentStartDate(LocalDateTime value) {
		AbsentStartDate = value;
	}

	private LocalDateTime ConvictedDate;

	public LocalDateTime getConvictedDate() {
		return ConvictedDate;
	}

	public void setConvictedDate(LocalDateTime value) {
		ConvictedDate = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private LocalDateTime DiscoveryDate;

	public LocalDateTime getDiscoveryDate() {
		return DiscoveryDate;
	}

	public void setDiscoveryDate(LocalDateTime value) {
		DiscoveryDate = value;
	}

	private LocalDateTime ExpectedReturnDate;

	public LocalDateTime getExpectedReturnDate() {
		return ExpectedReturnDate;
	}

	public void setExpectedReturnDate(LocalDateTime value) {
		ExpectedReturnDate = value;
	}

	private LocalDateTime FacilityContactDate;

	public LocalDateTime getFacilityContactDate() {
		return FacilityContactDate;
	}

	public void setFacilityContactDate(LocalDateTime value) {
		FacilityContactDate = value;
	}

	private String HadMedicaidEligibilityJustPriorToEmergencyShelterAdmittance = "";

	public String getHadMedicaidEligibilityJustPriorToEmergencyShelterAdmittance() {
		return HadMedicaidEligibilityJustPriorToEmergencyShelterAdmittance;
	}

	public void setHadMedicaidEligibilityJustPriorToEmergencyShelterAdmittance(String value) {
		HadMedicaidEligibilityJustPriorToEmergencyShelterAdmittance = value;
	}

	private String HasCourtWard = "";

	public String getHasCourtWard() {
		return HasCourtWard;
	}

	public void setHasCourtWard(String value) {
		HasCourtWard = value;
	}

	private String HasPhysicianVerifiedTemporaryInstitutionalization = "";

	public String getHasPhysicianVerifiedTemporaryInstitutionalization() {
		return HasPhysicianVerifiedTemporaryInstitutionalization;
	}

	public void setHasPhysicianVerifiedTemporaryInstitutionalization(String value) {
		HasPhysicianVerifiedTemporaryInstitutionalization = value;
	}

	private String HasRecievedHalfMealsFrmInst = "";

	public String getHasRecievedHalfMealsFrmInst() {
		return HasRecievedHalfMealsFrmInst;
	}

	public void setHasRecievedHalfMealsFrmInst(String value) {
		HasRecievedHalfMealsFrmInst = value;
	}

	private String HasRelocated = "";

	public String getHasRelocated() {
		return HasRelocated;
	}

	public void setHasRelocated(String value) {
		HasRelocated = value;
	}

	private String HasReturnParentsHome = "";

	public String getHasReturnParentsHome() {
		return HasReturnParentsHome;
	}

	public void setHasReturnParentsHome(String value) {
		HasReturnParentsHome = value;
	}

	private String HomelessReasonCode = "";

	public String getHomelessReasonCode() {
		return HomelessReasonCode;
	}

	public void setHomelessReasonCode(String value) {
		HomelessReasonCode = value;
	}

	private String IncarcerationStatusTypeCode = "";

	public String getIncarcerationStatusTypeCode() {
		return IncarcerationStatusTypeCode;
	}

	public void setIncarcerationStatusTypeCode(String value) {
		IncarcerationStatusTypeCode = value;
	}

	private String IncarcerationVerificationTypeCode = "";

	public String getIncarcerationVerificationTypeCode() {
		return IncarcerationVerificationTypeCode;
	}

	public void setIncarcerationVerificationTypeCode(String value) {
		IncarcerationVerificationTypeCode = value;
	}

	private LocalDateTime IndividualLivingArrangementEndDate;

	public LocalDateTime getIndividualLivingArrangementEndDate() {
		return IndividualLivingArrangementEndDate;
	}

	public void setIndividualLivingArrangementEndDate(LocalDateTime value) {
		IndividualLivingArrangementEndDate = value;
	}

	private LocalDateTime IndividualLivingArrangementStartDate;

	public LocalDateTime getIndividualLivingArrangementStartDate() {
		return IndividualLivingArrangementStartDate;
	}

	public void setIndividualLivingArrangementStartDate(LocalDateTime value) {
		IndividualLivingArrangementStartDate = value;
	}

	private String InEmergencyShelterDueToDelinquentOrStatusOffense = "";

	public String getInEmergencyShelterDueToDelinquentOrStatusOffense() {
		return InEmergencyShelterDueToDelinquentOrStatusOffense;
	}

	public void setInEmergencyShelterDueToDelinquentOrStatusOffense(String value) {
		InEmergencyShelterDueToDelinquentOrStatusOffense = value;
	}

	private String InHomeCareTypeCode = "";

	public String getInHomeCareTypeCode() {
		return InHomeCareTypeCode;
	}

	public void setInHomeCareTypeCode(String value) {
		InHomeCareTypeCode = value;
	}

	private String InstituteCertifiedByStateCode = "";

	public String getInstituteCertifiedByStateCode() {
		return InstituteCertifiedByStateCode;
	}

	public void setInstituteCertifiedByStateCode(String value) {
		InstituteCertifiedByStateCode = value;
	}

	private String InstOrganizationName = "";

	public String getInstOrganizationName() {
		return InstOrganizationName;
	}

	public void setInstOrganizationName(String value) {
		InstOrganizationName = value;
	}

	private String IsExpectedToReturnHome = "";

	public String getIsExpectedToReturnHome() {
		return IsExpectedToReturnHome;
	}

	public void setIsExpectedToReturnHome(String value) {
		IsExpectedToReturnHome = value;
	}

	private String IsHospitalized = "";

	public String getIsHospitalized() {
		return IsHospitalized;
	}

	public void setIsHospitalized(String value) {
		IsHospitalized = value;
	}

	private String IsIneligibleFacility = "";

	public String getIsIneligibleFacility() {
		return IsIneligibleFacility;
	}

	public void setIsIneligibleFacility(String value) {
		IsIneligibleFacility = value;
	}

	private String IsInEmergencyShelter = "";

	public String getIsInEmergencyShelter() {
		return IsInEmergencyShelter;
	}

	public void setIsInEmergencyShelter(String value) {
		IsInEmergencyShelter = value;
	}

	private String IsInstitutionalizationLessThan3Month = "";

	public String getIsInstitutionalizationLessThan3Month() {
		return IsInstitutionalizationLessThan3Month;
	}

	public void setIsInstitutionalizationLessThan3Month(String value) {
		IsInstitutionalizationLessThan3Month = value;
	}

	private String IsMaintainingLivingArrangementTemporaryAdmission = "";

	public String getIsMaintainingLivingArrangementTemporaryAdmission() {
		return IsMaintainingLivingArrangementTemporaryAdmission;
	}

	public void setIsMaintainingLivingArrangementTemporaryAdmission(String value) {
		IsMaintainingLivingArrangementTemporaryAdmission = value;
	}

	private String IsReceivingCaretakerServiceToPreventInstitutionalization = "";

	public String getIsReceivingCaretakerServiceToPreventInstitutionalization() {
		return IsReceivingCaretakerServiceToPreventInstitutionalization;
	}

	public void setIsReceivingCaretakerServiceToPreventInstitutionalization(String value) {
		IsReceivingCaretakerServiceToPreventInstitutionalization = value;
	}

	private String IsReceivingCISDueToMentalIllness = "";

	public String getIsReceivingCISDueToMentalIllness() {
		return IsReceivingCISDueToMentalIllness;
	}

	public void setIsReceivingCISDueToMentalIllness(String value) {
		IsReceivingCISDueToMentalIllness = value;
	}

	private String IsRecievingDomiciliaryCare = "";

	public String getIsRecievingDomiciliaryCare() {
		return IsRecievingDomiciliaryCare;
	}

	public void setIsRecievingDomiciliaryCare(String value) {
		IsRecievingDomiciliaryCare = value;
	}

	private String IsRecievingRemedialSrvcs = "";

	public String getIsRecievingRemedialSrvcs() {
		return IsRecievingRemedialSrvcs;
	}

	public void setIsRecievingRemedialSrvcs(String value) {
		IsRecievingRemedialSrvcs = value;
	}

	private String IsServingSentenceOrAwaitingTrial = "";

	public String getIsServingSentenceOrAwaitingTrial() {
		return IsServingSentenceOrAwaitingTrial;
	}

	public void setIsServingSentenceOrAwaitingTrial(String value) {
		IsServingSentenceOrAwaitingTrial = value;
	}

	private String LaTypeCode = "";

	public String getLaTypeCode() {
		return LaTypeCode;
	}

	public void setLaTypeCode(String value) {
		LaTypeCode = value;
	}

	private String LevelOfCareCode = "";

	public String getLevelOfCareCode() {
		return LevelOfCareCode;
	}

	public void setLevelOfCareCode(String value) {
		LevelOfCareCode = value;
	}

	private String MinorParentTanfVrfCode = "";

	public String getMinorParentTanfVrfCode() {
		return MinorParentTanfVrfCode;
	}

	public void setMinorParentTanfVrfCode(String value) {
		MinorParentTanfVrfCode = value;
	}

	private Integer ProviderId;

	public Integer getProviderId() {
		return ProviderId;
	}

	public void setProviderId(Integer value) {
		ProviderId = value;
	}

	private Integer ProviderServiceSeqNumber;

	public Integer getProviderServiceSeqNumber() {
		return ProviderServiceSeqNumber;
	}

	public void setProviderServiceSeqNumber(Integer value) {
		ProviderServiceSeqNumber = value;
	}

	private LocalDateTime ReportDate;

	public LocalDateTime getReportDate() {
		return ReportDate;
	}

	public void setReportDate(LocalDateTime value) {
		ReportDate = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

	private LocalDateTime VerficationRecievedDate;

	public LocalDateTime getVerficationRecievedDate() {
		return VerficationRecievedDate;
	}

	public void setVerficationRecievedDate(LocalDateTime value) {
		VerficationRecievedDate = value;
	}

	private String VerificationCode = "";

	public String getVerificationCode() {
		return VerificationCode;
	}

	public void setVerificationCode(String value) {
		VerificationCode = value;
	}

}
