//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:27 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class KTAPIneligibilityModel {

	private int KTAPIneligibilityId;

	public int getKTAPIneligibilityId() {
		return KTAPIneligibilityId;
	}

	public void setKTAPIneligibilityId(int value) {
		KTAPIneligibilityId = value;
	}

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private LocalDateTime FADApprovalDate;

	public LocalDateTime getFADApprovalDate() {
		return FADApprovalDate;
	}

	public void setFADApprovalDate(LocalDateTime value) {
		FADApprovalDate = value;
	}

	private String GoodCauseReason = "";

	public String getGoodCauseReason() {
		return GoodCauseReason;
	}

	public void setGoodCauseReason(String value) {
		GoodCauseReason = value;
	}

	private String GoodCauseVerification = "";

	public String getGoodCauseVerification() {
		return GoodCauseVerification;
	}

	public void setGoodCauseVerification(String value) {
		GoodCauseVerification = value;
	}

	private String HasGoodCauseForReceivingKTAP = "";

	public String getHasGoodCauseForReceivingKTAP() {
		return HasGoodCauseForReceivingKTAP;
	}

	public void setHasGoodCauseForReceivingKTAP(String value) {
		HasGoodCauseForReceivingKTAP = value;
	}

	private String IsUnableToCareForChildDueToJobLoss = "";

	public String getIsUnableToCareForChildDueToJobLoss() {
		return IsUnableToCareForChildDueToJobLoss;
	}

	public void setIsUnableToCareForChildDueToJobLoss(String value) {
		IsUnableToCareForChildDueToJobLoss = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
