//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:28 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class MassChangeTriggerModel {

	private Long CaseNumber;

	public Long getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Long value) {
		CaseNumber = value;
	}

	private int MassChangeTriggerId;

	public int getMassChangeTriggerId() {
		return MassChangeTriggerId;
	}

	public void setMassChangeTriggerId(int value) {
		MassChangeTriggerId = value;
	}

	 private LocalDateTime ScheduledRunDate;

	public LocalDateTime getScheduledRunDate() {
		return ScheduledRunDate;
	}

	public void setScheduledRunDate(LocalDateTime value) {
		ScheduledRunDate = value;
	}

	private String TriggerCode = "";

	public String getTriggerCode() {
		return TriggerCode;
	}

	public void setTriggerCode(String value) {
		TriggerCode = value;
	}

	 private LocalDateTime BeginDate;

	public LocalDateTime getBeginDate() {
		return BeginDate;
	}

	public void setBeginDate(LocalDateTime value) {
		BeginDate = value;
	}

	private Double CaseProcessOrder;

	public Double getCaseProcessOrder() {
		return CaseProcessOrder;
	}

	public void setCaseProcessOrder(Double value) {
		CaseProcessOrder = value;
	}

	private String CashExceptionDetails = "";

	public String getCashExceptionDetails() {
		return CashExceptionDetails;
	}

	public void setCashExceptionDetails(String value) {
		CashExceptionDetails = value;
	}

	private String ChildDayCareExceptionDetails = "";

	public String getChildDayCareExceptionDetails() {
		return ChildDayCareExceptionDetails;
	}

	public void setChildDayCareExceptionDetails(String value) {
		ChildDayCareExceptionDetails = value;
	}

	private Integer CombinedCaseSequenceNumber;

	public Integer getCombinedCaseSequenceNumber() {
		return CombinedCaseSequenceNumber;
	}

	public void setCombinedCaseSequenceNumber(Integer value) {
		CombinedCaseSequenceNumber = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private Integer EDBCMURunDetailsId;

	public Integer getEDBCMURunDetailsId() {
		return EDBCMURunDetailsId;
	}

	public void setEDBCMURunDetailsId(Integer value) {
		EDBCMURunDetailsId = value;
	}

	private Integer EdgNumber;

	public Integer getEdgNumber() {
		return EdgNumber;
	}

	public void setEdgNumber(Integer value) {
		EdgNumber = value;
	}

	 private LocalDateTime EligibilityBeginDate;

	public LocalDateTime getEligibilityBeginDate() {
		return EligibilityBeginDate;
	}

	public void setEligibilityBeginDate(LocalDateTime value) {
		EligibilityBeginDate = value;
	}

	private Integer EligibilityTransactionId;

	public Integer getEligibilityTransactionId() {
		return EligibilityTransactionId;
	}

	public void setEligibilityTransactionId(Integer value) {
		EligibilityTransactionId = value;
	}

	 private LocalDateTime EndDate;

	public LocalDateTime getEndDate() {
		return EndDate;
	}

	public void setEndDate(LocalDateTime value) {
		EndDate = value;
	}

	private String ExceptionDetails = "";

	public String getExceptionDetails() {
		return ExceptionDetails;
	}

	public void setExceptionDetails(String value) {
		ExceptionDetails = value;
	}

	private String ExceptionReasonCode = "";

	public String getExceptionReasonCode() {
		return ExceptionReasonCode;
	}

	public void setExceptionReasonCode(String value) {
		ExceptionReasonCode = value;
	}

	private String FoodStampExceptionDetails = "";

	public String getFoodStampExceptionDetails() {
		return FoodStampExceptionDetails;
	}

	public void setFoodStampExceptionDetails(String value) {
		FoodStampExceptionDetails = value;
	}

	private String IsExceptionProcessed = "";

	public String getIsExceptionProcessed() {
		return IsExceptionProcessed;
	}

	public void setIsExceptionProcessed(String value) {
		IsExceptionProcessed = value;
	}

	 private LocalDateTime MassUpdateEdgBeginDate;

	public LocalDateTime getMassUpdateEdgBeginDate() {
		return MassUpdateEdgBeginDate;
	}

	public void setMassUpdateEdgBeginDate(LocalDateTime value) {
		MassUpdateEdgBeginDate = value;
	}

	private String MassUpdateStatusIndicator = "";

	public String getMassUpdateStatusIndicator() {
		return MassUpdateStatusIndicator;
	}

	public void setMassUpdateStatusIndicator(String value) {
		MassUpdateStatusIndicator = value;
	}

	private String MedicaidExceptionDetails = "";

	public String getMedicaidExceptionDetails() {
		return MedicaidExceptionDetails;
	}

	public void setMedicaidExceptionDetails(String value) {
		MedicaidExceptionDetails = value;
	}

	private String MuRunReason = "";

	public String getMuRunReason() {
		return MuRunReason;
	}

	public void setMuRunReason(String value) {
		MuRunReason = value;
	}

	private Integer RetryCount;

	public Integer getRetryCount() {
		return RetryCount;
	}

	public void setRetryCount(Integer value) {
		RetryCount = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private Integer SdxSequenceNumber;

	public Integer getSdxSequenceNumber() {
		return SdxSequenceNumber;
	}

	public void setSdxSequenceNumber(Integer value) {
		SdxSequenceNumber = value;
	}

	private Integer ServerNumber;

	public Integer getServerNumber() {
		return ServerNumber;
	}

	public void setServerNumber(Integer value) {
		ServerNumber = value;
	}

	private String StatusIndicator = "";

	public String getStatusIndicator() {
		return StatusIndicator;
	}

	public void setStatusIndicator(String value) {
		StatusIndicator = value;
	}

	private Integer ThreadNumber;

	public Integer getThreadNumber() {
		return ThreadNumber;
	}

	public void setThreadNumber(Integer value) {
		ThreadNumber = value;
	}

	private String TriggerType = "";

	public String getTriggerType() {
		return TriggerType;
	}

	public void setTriggerType(String value) {
		TriggerType = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
