//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:28 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class MFPShelterAllowanceModel {

	private int MoneyFollowsThePersonShelterAllowanceId;

	public int getMoneyFollowsThePersonShelterAllowanceId() {
		return MoneyFollowsThePersonShelterAllowanceId;
	}

	public void setMoneyFollowsThePersonShelterAllowanceId(int value) {
		MoneyFollowsThePersonShelterAllowanceId = value;
	}

	private int MoneyFollowsThePersonId;

	public int getMoneyFollowsThePersonId() {
		return MoneyFollowsThePersonId;
	}

	public void setMoneyFollowsThePersonId(int value) {
		MoneyFollowsThePersonId = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private Double ShelterAllowanceAmount;

	public Double getShelterAllowanceAmount() {
		return ShelterAllowanceAmount;
	}

	public void setShelterAllowanceAmount(Double value) {
		ShelterAllowanceAmount = value;
	}

	 private LocalDateTime ShelterAllowanceEndDate;

	public LocalDateTime getShelterAllowanceEndDate() {
		return ShelterAllowanceEndDate;
	}

	public void setShelterAllowanceEndDate(LocalDateTime value) {
		ShelterAllowanceEndDate = value;
	}

	 private LocalDateTime ShelterAllowanceStartDate;

	public LocalDateTime getShelterAllowanceStartDate() {
		return ShelterAllowanceStartDate;
	}

	public void setShelterAllowanceStartDate(LocalDateTime value) {
		ShelterAllowanceStartDate = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
