//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:28 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class NewBornModel {

	private int NewBornId;

	public int getNewBornId() {
		return NewBornId;
	}

	public void setNewBornId(int value) {
		NewBornId = value;
	}

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private LocalDateTime BeginDate;

	public LocalDateTime getBeginDate() {
		return BeginDate;
	}

	public void setBeginDate(LocalDateTime value) {
		BeginDate = value;
	}

	private String BirthCounty = "";

	public String getBirthCounty() {
		return BirthCounty;
	}

	public void setBirthCounty(String value) {
		BirthCounty = value;
	}

	private Double BirthWeight;

	public Double getBirthWeight() {
		return BirthWeight;
	}

	public void setBirthWeight(Double value) {
		BirthWeight = value;
	}

	private Integer CertificateNumber;

	public Integer getCertificateNumber() {
		return CertificateNumber;
	}

	public void setCertificateNumber(Integer value) {
		CertificateNumber = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private LocalDateTime DiscoveryDate;

	public LocalDateTime getDiscoveryDate() {
		return DiscoveryDate;
	}

	public void setDiscoveryDate(LocalDateTime value) {
		DiscoveryDate = value;
	}

	private LocalDateTime EndDate;

	public LocalDateTime getEndDate() {
		return EndDate;
	}

	public void setEndDate(LocalDateTime value) {
		EndDate = value;
	}

	private String HasLivedWithMother = "";

	public String getHasLivedWithMother() {
		return HasLivedWithMother;
	}

	public void setHasLivedWithMother(String value) {
		HasLivedWithMother = value;
	}

	private String HasMomRelinquishedParentRights = "";

	public String getHasMomRelinquishedParentRights() {
		return HasMomRelinquishedParentRights;
	}

	public void setHasMomRelinquishedParentRights(String value) {
		HasMomRelinquishedParentRights = value;
	}

	public String IsMotherMaEligible = "";

	public String getIsMotherMaEligible() {
		return IsMotherMaEligible;
	}

	public void setIsMotherMaEligible(String value) {
		IsMotherMaEligible = value;
	}

	private String MotherMaEligibleVerificationCode = "";

	public String getMotherMaEligibleVerificationCode() {
		return MotherMaEligibleVerificationCode;
	}

	public void setMotherMaEligibleVerificationCode(String value) {
		MotherMaEligibleVerificationCode = value;
	}

	private String MotherMedicalAidToaCode = "";

	public String getMotherMedicalAidToaCode() {
		return MotherMedicalAidToaCode;
	}

	public void setMotherMedicalAidToaCode(String value) {
		MotherMedicalAidToaCode = value;
	}

	private LocalDateTime RelinquishedDate;

	public LocalDateTime getRelinquishedDate() {
		return RelinquishedDate;
	}

	public void setRelinquishedDate(LocalDateTime value) {
		RelinquishedDate = value;
	}

	private LocalDateTime ReportDate;

	public LocalDateTime getReportDate() {
		return ReportDate;
	}

	public void setReportDate(LocalDateTime value) {
		ReportDate = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

	private LocalDateTime VerificationRecievedDate;

	public LocalDateTime getVerificationRecievedDate() {
		return VerificationRecievedDate;
	}

	public void setVerificationRecievedDate(LocalDateTime value) {
		VerificationRecievedDate = value;
	}

}
