//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:28 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class PayPeriodInformationModel {

	private int PayPeriodInformationId;

	public int getPayPeriodInformationId() {
		return PayPeriodInformationId;
	}

	public void setPayPeriodInformationId(int value) {
		PayPeriodInformationId = value;
	}

	private Integer VerifyCurrentIncomeId;

	public Integer getVerifyCurrentIncomeId() {
		return VerifyCurrentIncomeId;
	}

	public void setVerifyCurrentIncomeId(Integer value) {
		VerifyCurrentIncomeId = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	 private LocalDateTime PayPeriodEndDate;

	public LocalDateTime getPayPeriodEndDate() {
		return PayPeriodEndDate;
	}

	public void setPayPeriodEndDate(LocalDateTime value) {
		PayPeriodEndDate = value;
	}

	private Double PayPeriodIncomeAmount;

	public Double getPayPeriodIncomeAmount() {
		return PayPeriodIncomeAmount;
	}

	public void setPayPeriodIncomeAmount(Double value) {
		PayPeriodIncomeAmount = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
