//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:28 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class PregnancyModel {

	private int PregnancyId;

	public int getPregnancyId() {
		return PregnancyId;
	}

	public void setPregnancyId(int value) {
		PregnancyId = value;
	}

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private LocalDateTime ClientBecameAwareDate;

	public LocalDateTime getClientBecameAwareDate() {
		return ClientBecameAwareDate;
	}

	public void setClientBecameAwareDate(LocalDateTime value) {
		ClientBecameAwareDate = value;
	}

	private LocalDateTime ClientReportDate;

	public LocalDateTime getClientReportDate() {
		return ClientReportDate;
	}

	public void setClientReportDate(LocalDateTime value) {
		ClientReportDate = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private LocalDateTime DiscoveryDate;

	public LocalDateTime getDiscoveryDate() {
		return DiscoveryDate;
	}

	public void setDiscoveryDate(LocalDateTime value) {
		DiscoveryDate = value;
	}

	private LocalDateTime DueDate;

	public LocalDateTime getDueDate() {
		return DueDate;
	}

	public void setDueDate(LocalDateTime value) {
		DueDate = value;
	}

	private String ExemptForWorkingCode = "";

	public String getExemptForWorkingCode() {
		return ExemptForWorkingCode;
	}

	public void setExemptForWorkingCode(String value) {
		ExemptForWorkingCode = value;
	}

	private String HighRiskPregnancyVerificationCode = "";

	public String getHighRiskPregnancyVerificationCode() {
		return HighRiskPregnancyVerificationCode;
	}

	public void setHighRiskPregnancyVerificationCode(String value) {
		HighRiskPregnancyVerificationCode = value;
	}

	private LocalDateTime HighRiskPregnancyVerificationDate;

	public LocalDateTime getHighRiskPregnancyVerificationDate() {
		return HighRiskPregnancyVerificationDate;
	}

	public void setHighRiskPregnancyVerificationDate(LocalDateTime value) {
		HighRiskPregnancyVerificationDate = value;
	}

	private String IsHighRiskPregnancy = "";

	public String getIsHighRiskPregnancy() {
		return IsHighRiskPregnancy;
	}

	public void setIsHighRiskPregnancy(String value) {
		IsHighRiskPregnancy = value;
	}

	private String IsProblemPregnancy = "";

	public String getIsProblemPregnancy() {
		return IsProblemPregnancy;
	}

	public void setIsProblemPregnancy(String value) {
		IsProblemPregnancy = value;
	}

	private String IsTimely = "";

	public String getIsTimely() {
		return IsTimely;
	}

	public void setIsTimely(String value) {
		IsTimely = value;
	}

	private String IsVerifiedTimely = "";

	public String getIsVerifiedTimely() {
		return IsVerifiedTimely;
	}

	public void setIsVerifiedTimely(String value) {
		IsVerifiedTimely = value;
	}

	private String NumberOfBirthsExpectedCode = "";

	public String getNumberOfBirthsExpectedCode() {
		return NumberOfBirthsExpectedCode;
	}

	public void setNumberOfBirthsExpectedCode(String value) {
		NumberOfBirthsExpectedCode = value;
	}

	private LocalDateTime PregnancyBeginDate;

	public LocalDateTime getPregnancyBeginDate() {
		return PregnancyBeginDate;
	}

	public void setPregnancyBeginDate(LocalDateTime value) {
		PregnancyBeginDate = value;
	}

	private LocalDateTime PregnancyEndDate;

	public LocalDateTime getPregnancyEndDate() {
		return PregnancyEndDate;
	}

	public void setPregnancyEndDate(LocalDateTime value) {
		PregnancyEndDate = value;
	}

	private String PregnancyVerificationCode = "";

	public String getPregnancyVerificationCode() {
		return PregnancyVerificationCode;
	}

	public void setPregnancyVerificationCode(String value) {
		PregnancyVerificationCode = value;
	}

	private LocalDateTime ReportDate;

	public LocalDateTime getReportDate() {
		return ReportDate;
	}

	public void setReportDate(LocalDateTime value) {
		ReportDate = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime TerminationDate;

	public LocalDateTime getTerminationDate() {
		return TerminationDate;
	}

	public void setTerminationDate(LocalDateTime value) {
		TerminationDate = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

	private LocalDateTime VerificationRecievedDate;

	public LocalDateTime getVerificationRecievedDate() {
		return VerificationRecievedDate;
	}

	public void setVerificationRecievedDate(LocalDateTime value) {
		VerificationRecievedDate = value;
	}

}
