//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:28 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class QualifiedIncomeTrustModel {

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private int QualifiedIncomeTrustId;

	public int getQualifiedIncomeTrustId() {
		return QualifiedIncomeTrustId;
	}

	public void setQualifiedIncomeTrustId(int value) {
		QualifiedIncomeTrustId = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String HasExcessFundsPostDeduction = "";

	public String getHasExcessFundsPostDeduction() {
		return HasExcessFundsPostDeduction;
	}

	public void setHasExcessFundsPostDeduction(String value) {
		HasExcessFundsPostDeduction = value;
	}

	private String IsDisbursementsApprovedByDMS = "";

	public String getIsDisbursementsApprovedByDMS() {
		return IsDisbursementsApprovedByDMS;
	}

	public void setIsDisbursementsApprovedByDMS(String value) {
		IsDisbursementsApprovedByDMS = value;
	}

	private String IsDMSReceivingBalanceAmountUponDeath = "";

	public String getIsDMSReceivingBalanceAmountUponDeath() {
		return IsDMSReceivingBalanceAmountUponDeath;
	}

	public void setIsDMSReceivingBalanceAmountUponDeath(String value) {
		IsDMSReceivingBalanceAmountUponDeath = value;
	}

	private String IsIncomeDistributionRequired = "";

	public String getIsIncomeDistributionRequired() {
		return IsIncomeDistributionRequired;
	}

	public void setIsIncomeDistributionRequired(String value) {
		IsIncomeDistributionRequired = value;
	}

	private String IsMeetingQITCriteria = "";

	public String getIsMeetingQITCriteria() {
		return IsMeetingQITCriteria;
	}

	public void setIsMeetingQITCriteria(String value) {
		IsMeetingQITCriteria = value;
	}

	private String IsQITEstablished = "";

	public String getIsQITEstablished() {
		return IsQITEstablished;
	}

	public void setIsQITEstablished(String value) {
		IsQITEstablished = value;
	}

	private String IsQITStatement = "";

	public String getIsQITStatement() {
		return IsQITStatement;
	}

	public void setIsQITStatement(String value) {
		IsQITStatement = value;
	}

	private String IsQITTerminateAtDeath = "";

	public String getIsQITTerminateAtDeath() {
		return IsQITTerminateAtDeath;
	}

	public void setIsQITTerminateAtDeath(String value) {
		IsQITTerminateAtDeath = value;
	}

	private String IsTrustBenefitIndividual = "";

	public String getIsTrustBenefitIndividual() {
		return IsTrustBenefitIndividual;
	}

	public void setIsTrustBenefitIndividual(String value) {
		IsTrustBenefitIndividual = value;
	}

	private String IsTrustComposeOnlyIncome = "";

	public String getIsTrustComposeOnlyIncome() {
		return IsTrustComposeOnlyIncome;
	}

	public void setIsTrustComposeOnlyIncome(String value) {
		IsTrustComposeOnlyIncome = value;
	}

	private Double MonthlyAmountInQualifiedIncomeTrust;

	public Double getMonthlyAmountInQualifiedIncomeTrust() {
		return MonthlyAmountInQualifiedIncomeTrust;
	}

	public void setMonthlyAmountInQualifiedIncomeTrust(Double value) {
		MonthlyAmountInQualifiedIncomeTrust = value;
	}

	private String QITVerificationCode = "";

	public String getQITVerificationCode() {
		return QITVerificationCode;
	}

	public void setQITVerificationCode(String value) {
		QITVerificationCode = value;
	}

	private LocalDateTime QualifiedIncomeTrustEstablishedDate;

	public LocalDateTime getQualifiedIncomeTrustEstablishedDate() {
		return QualifiedIncomeTrustEstablishedDate;
	}

	public void setQualifiedIncomeTrustEstablishedDate(LocalDateTime value) {
		QualifiedIncomeTrustEstablishedDate = value;
	}

	private LocalDateTime ReviewDate;

	public LocalDateTime getReviewDate() {
		return ReviewDate;
	}

	public void setReviewDate(LocalDateTime value) {
		ReviewDate = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
