//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:28 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class RelationshipModel {

	private int RelationshipId;

	public int getRelationshipId() {
		return RelationshipId;
	}

	public void setRelationshipId(int value) {
		RelationshipId = value;
	}

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private LocalDateTime AdoptionDate;

	public LocalDateTime getAdoptionDate() {
		return AdoptionDate;
	}

	public void setAdoptionDate(LocalDateTime value) {
		AdoptionDate = value;
	}

	private LocalDateTime BeginDate;

	public LocalDateTime getBeginDate() {
		return BeginDate;
	}

	public void setBeginDate(LocalDateTime value) {
		BeginDate = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private LocalDateTime DiscoveryDate;

	public LocalDateTime getDiscoveryDate() {
		return DiscoveryDate;
	}

	public void setDiscoveryDate(LocalDateTime value) {
		DiscoveryDate = value;
	}

	private LocalDateTime EndDate;

	public LocalDateTime getEndDate() {
		return EndDate;
	}

	public void setEndDate(LocalDateTime value) {
		EndDate = value;
	}

	private String HasFilledParentalRole = "";

	public String getHasFilledParentalRole() {
		return HasFilledParentalRole;
	}

	public void setHasFilledParentalRole(String value) {
		HasFilledParentalRole = value;
	}

	private String HasProvidedCareFor = "";

	public String getHasProvidedCareFor() {
		return HasProvidedCareFor;
	}

	public void setHasProvidedCareFor(String value) {
		HasProvidedCareFor = value;
	}

	private String InLocoParentis = "";

	public String getInLocoParentis() {
		return InLocoParentis;
	}

	public void setInLocoParentis(String value) {
		InLocoParentis = value;
	}

	private String IntentLegalGuard = "";

	public String getIntentLegalGuard() {
		return IntentLegalGuard;
	}

	public void setIntentLegalGuard(String value) {
		IntentLegalGuard = value;
	}

	private String IsAdopted = "";

	public String getIsAdopted() {
		return IsAdopted;
	}

	public void setIsAdopted(String value) {
		IsAdopted = value;
	}

	private String IsCaretaker = "";

	public String getIsCaretaker() {
		return IsCaretaker;
	}

	public void setIsCaretaker(String value) {
		IsCaretaker = value;
	}

	private String IsPhysicallyAbleToPurchasePrepare = "";

	public String getIsPhysicallyAbleToPurchasePrepare() {
		return IsPhysicallyAbleToPurchasePrepare;
	}

	public void setIsPhysicallyAbleToPurchasePrepare(String value) {
		IsPhysicallyAbleToPurchasePrepare = value;
	}

	private String IsPrepareAndPurchases = "";

	public String getIsPrepareAndPurchases() {
		return IsPrepareAndPurchases;
	}

	public void setIsPrepareAndPurchases(String value) {
		IsPrepareAndPurchases = value;
	}

	private String IsProvidingSupportFor = "";

	public String getIsProvidingSupportFor() {
		return IsProvidingSupportFor;
	}

	public void setIsProvidingSupportFor(String value) {
		IsProvidingSupportFor = value;
	}

	private String IsTimely = "";

	public String getIsTimely() {
		return IsTimely;
	}

	public void setIsTimely(String value) {
		IsTimely = value;
	}

	private LocalDateTime MarriageDate;

	public LocalDateTime getMarriageDate() {
		return MarriageDate;
	}

	public void setMarriageDate(LocalDateTime value) {
		MarriageDate = value;
	}

	private Long RelatedIndividualId;

	public Long getRelatedIndividualId() {
		return RelatedIndividualId;
	}

	public void setRelatedIndividualId(Long value) {
		RelatedIndividualId = value;
	}

	private String RelationshipTypeCode = "";

	public String getRelationshipTypeCode() {
		return RelationshipTypeCode;
	}

	public void setRelationshipTypeCode(String value) {
		RelationshipTypeCode = value;
	}

	private String RelationshipVerificationCode = "";

	public String getRelationshipVerificationCode() {
		return RelationshipVerificationCode;
	}

	public void setRelationshipVerificationCode(String value) {
		RelationshipVerificationCode = value;
	}

	private LocalDateTime ReportDate;

	public LocalDateTime getReportDate() {
		return ReportDate;
	}

	public void setReportDate(LocalDateTime value) {
		ReportDate = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

	private LocalDateTime VerificationReceivedDate;

	public LocalDateTime getVerificationReceivedDate() {
		return VerificationReceivedDate;
	}

	public void setVerificationReceivedDate(LocalDateTime value) {
		VerificationReceivedDate = value;
	}

}
