//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:28 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class SDXAddressModel {

	private int SDXSequenceNumber;

	public int getSDXSequenceNumber() {
		return SDXSequenceNumber;
	}

	public void setSDXSequenceNumber(int value) {
		SDXSequenceNumber = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String RecipientAddressName = "";

	public String getRecipientAddressName() {
		return RecipientAddressName;
	}

	public void setRecipientAddressName(String value) {
		RecipientAddressName = value;
	}

	private String RecipientMailingAddressLine1 = "";

	public String getRecipientMailingAddressLine1() {
		return RecipientMailingAddressLine1;
	}

	public void setRecipientMailingAddressLine1(String value) {
		RecipientMailingAddressLine1 = value;
	}

	private String RecipientMailingAddressLine2 = "";

	public String getRecipientMailingAddressLine2() {
		return RecipientMailingAddressLine2;
	}

	public void setRecipientMailingAddressLine2(String value) {
		RecipientMailingAddressLine2 = value;
	}

	private String RecipientMailingCity = "";

	public String getRecipientMailingCity() {
		return RecipientMailingCity;
	}

	public void setRecipientMailingCity(String value) {
		RecipientMailingCity = value;
	}

	private String RecipientZIP4Code = "";

	public String getRecipientZIP4Code() {
		return RecipientZIP4Code;
	}

	public void setRecipientZIP4Code(String value) {
		RecipientZIP4Code = value;
	}

	private String RecipientZIPCode = "";

	public String getRecipientZIPCode() {
		return RecipientZIPCode;
	}

	public void setRecipientZIPCode(String value) {
		RecipientZIPCode = value;
	}

	 private LocalDateTime RecordEndDate;

	public LocalDateTime getRecordEndDate() {
		return RecordEndDate;
	}

	public void setRecordEndDate(LocalDateTime value) {
		RecordEndDate = value;
	}

	private Integer RecordId;

	public Integer getRecordId() {
		return RecordId;
	}

	public void setRecordId(Integer value) {
		RecordId = value;
	}

	private String ResidenceAddressCity = "";

	public String getResidenceAddressCity() {
		return ResidenceAddressCity;
	}

	public void setResidenceAddressCity(String value) {
		ResidenceAddressCity = value;
	}

	private String ResidenceAddressLine1 = "";

	public String getResidenceAddressLine1() {
		return ResidenceAddressLine1;
	}

	public void setResidenceAddressLine1(String value) {
		ResidenceAddressLine1 = value;
	}

	private String ResidenceAddressLine2 = "";

	public String getResidenceAddressLine2() {
		return ResidenceAddressLine2;
	}

	public void setResidenceAddressLine2(String value) {
		ResidenceAddressLine2 = value;
	}

	private String ResidenceZIP4Code = "";

	public String getResidenceZIP4Code() {
		return ResidenceZIP4Code;
	}

	public void setResidenceZIP4Code(String value) {
		ResidenceZIP4Code = value;
	}

	private String ResidenceZIPCode = "";

	public String getResidenceZIPCode() {
		return ResidenceZIPCode;
	}

	public void setResidenceZIPCode(String value) {
		ResidenceZIPCode = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private String SSN = "";

	public String getSSN() {
		return SSN;
	}

	public void setSSN(String value) {
		SSN = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
