//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:28 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class SelfEmploymentIncomeBudgetModel {

	private int SelfEmploymentIncomeBudgetId;

	public int getSelfEmploymentIncomeBudgetId() {
		return SelfEmploymentIncomeBudgetId;
	}

	public void setSelfEmploymentIncomeBudgetId(int value) {
		SelfEmploymentIncomeBudgetId = value;
	}

	private int SelfEmploymentIncomeId;

	public int getSelfEmploymentIncomeId() {
		return SelfEmploymentIncomeId;
	}

	public void setSelfEmploymentIncomeId(int value) {
		SelfEmploymentIncomeId = value;
	}

	private LocalDateTime BudgetBeginDate;

	public LocalDateTime getBudgetBeginDate() {
		return BudgetBeginDate;
	}

	public void setBudgetBeginDate(LocalDateTime value) {
		BudgetBeginDate = value;
	}

	private LocalDateTime BudgetEndDate;

	public LocalDateTime getBudgetEndDate() {
		return BudgetEndDate;
	}

	public void setBudgetEndDate(LocalDateTime value) {
		BudgetEndDate = value;
	}

	private String BudgetTypeCode = "";

	public String getBudgetTypeCode() {
		return BudgetTypeCode;
	}

	public void setBudgetTypeCode(String value) {
		BudgetTypeCode = value;
	}

	private Double CcBudgetedAmount;

	public Double getCcBudgetedAmount() {
		return CcBudgetedAmount;
	}

	public void setCcBudgetedAmount(Double value) {
		CcBudgetedAmount = value;
	}

	private Double ChangeAverage;

	public Double getChangeAverage() {
		return ChangeAverage;
	}

	public void setChangeAverage(Double value) {
		ChangeAverage = value;
	}

	private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private LocalDateTime FirstPayForBudgetMonthDate;

	public LocalDateTime getFirstPayForBudgetMonthDate() {
		return FirstPayForBudgetMonthDate;
	}

	public void setFirstPayForBudgetMonthDate(LocalDateTime value) {
		FirstPayForBudgetMonthDate = value;
	}

	private LocalDateTime FirstPayForCertificationDate;

	public LocalDateTime getFirstPayForCertificationDate() {
		return FirstPayForCertificationDate;
	}

	public void setFirstPayForCertificationDate(LocalDateTime value) {
		FirstPayForCertificationDate = value;
	}

	private Long individualId;

	public Long getIndividualId() {
		return individualId;
	}

	public void setIndividualId(Long value) {
		individualId = value;
	}

	private Double KTAPBudgetedAmount;

	public Double getKTAPBudgetedAmount() {
		return KTAPBudgetedAmount;
	}

	public void setKTAPBudgetedAmount(Double value) {
		KTAPBudgetedAmount = value;
	}

	private LocalDateTime LastPayForBudgetMonthDate;

	public LocalDateTime getLastPayForBudgetMonthDate() {
		return LastPayForBudgetMonthDate;
	}

	public void setLastPayForBudgetMonthDate(LocalDateTime value) {
		LastPayForBudgetMonthDate = value;
	}

	private LocalDateTime LastPayForCertificationDate;

	public LocalDateTime getLastPayForCertificationDate() {
		return LastPayForCertificationDate;
	}

	public void setLastPayForCertificationDate(LocalDateTime value) {
		LastPayForCertificationDate = value;
	}

	private Double MAGIBudgetedAmount;

	public Double getMAGIBudgetedAmount() {
		return MAGIBudgetedAmount;
	}

	public void setMAGIBudgetedAmount(Double value) {
		MAGIBudgetedAmount = value;
	}

	private Double MaProjectedAmount;

	public Double getMaProjectedAmount() {
		return MaProjectedAmount;
	}

	public void setMaProjectedAmount(Double value) {
		MaProjectedAmount = value;
	}

	private Double MonthlyHours;

	public Double getMonthlyHours() {
		return MonthlyHours;
	}

	public void setMonthlyHours(Double value) {
		MonthlyHours = value;
	}

	private Double NetIncomeHoursPerMinimumWage;

	public Double getNetIncomeHoursPerMinimumWage() {
		return NetIncomeHoursPerMinimumWage;
	}

	public void setNetIncomeHoursPerMinimumWage(Double value) {
		NetIncomeHoursPerMinimumWage = value;
	}

	private Double NonMagiAdultMABudgetAmount;

	public Double getNonMagiAdultMABudgetAmount() {
		return NonMagiAdultMABudgetAmount;
	}

	public void setNonMagiAdultMABudgetAmount(Double value) {
		NonMagiAdultMABudgetAmount = value;
	}

	private Double NonMagiFamilyMABudgetAmount;

	public Double getNonMagiFamilyMABudgetAmount() {
		return NonMagiFamilyMABudgetAmount;
	}

	public void setNonMagiFamilyMABudgetAmount(Double value) {
		NonMagiFamilyMABudgetAmount = value;
	}

	private Double PaymentsExpected;

	public Double getPaymentsExpected() {
		return PaymentsExpected;
	}

	public void setPaymentsExpected(Double value) {
		PaymentsExpected = value;
	}

	private Double PaymentsReceived;

	public Double getPaymentsReceived() {
		return PaymentsReceived;
	}

	public void setPaymentsReceived(Double value) {
		PaymentsReceived = value;
	}

	private Double PriorMaBudgetedAmount;

	public Double getPriorMaBudgetedAmount() {
		return PriorMaBudgetedAmount;
	}

	public void setPriorMaBudgetedAmount(Double value) {
		PriorMaBudgetedAmount = value;
	}

	private Double PriorMaPaymentsExpected;

	public Double getPriorMaPaymentsExpected() {
		return PriorMaPaymentsExpected;
	}

	public void setPriorMaPaymentsExpected(Double value) {
		PriorMaPaymentsExpected = value;
	}

	private Double PriorMaPaymentsReceived;

	public Double getPriorMaPaymentsReceived() {
		return PriorMaPaymentsReceived;
	}

	public void setPriorMaPaymentsReceived(Double value) {
		PriorMaPaymentsReceived = value;
	}

	private Double PriorMaTotalExpenseAmount;

	public Double getPriorMaTotalExpenseAmount() {
		return PriorMaTotalExpenseAmount;
	}

	public void setPriorMaTotalExpenseAmount(Double value) {
		PriorMaTotalExpenseAmount = value;
	}

	private Double ProjectionAmount;

	public Double getProjectionAmount() {
		return ProjectionAmount;
	}

	public void setProjectionAmount(Double value) {
		ProjectionAmount = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private Double SNAPBudgetAmount;

	public Double getSNAPBudgetAmount() {
		return SNAPBudgetAmount;
	}

	public void setSNAPBudgetAmount(Double value) {
		SNAPBudgetAmount = value;
	}

	private String Source = "";

	public String getSource() {
		return Source;
	}

	public void setSource(String value) {
		Source = value;
	}

	private Double TotalExpenseAmount;

	public Double getTotalExpenseAmount() {
		return TotalExpenseAmount;
	}

	public void setTotalExpenseAmount(Double value) {
		TotalExpenseAmount = value;
	}

	private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
