//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:28 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class StatusOfMFPModel {

	private int StatusOfMFPId;

	public int getStatusOfMFPId() {
		return StatusOfMFPId;
	}

	public void setStatusOfMFPId(int value) {
		StatusOfMFPId = value;
	}

	private int MoneyFollowsThePersonId;

	public int getMoneyFollowsThePersonId() {
		return MoneyFollowsThePersonId;
	}

	public void setMoneyFollowsThePersonId(int value) {
		MoneyFollowsThePersonId = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private String MFPStatusCode = "";

	public String getMFPStatusCode() {
		return MFPStatusCode;
	}

	public void setMFPStatusCode(String value) {
		MFPStatusCode = value;
	}

	 private LocalDateTime MFPStatusDate;

	public LocalDateTime getMFPStatusDate() {
		return MFPStatusDate;
	}

	public void setMFPStatusDate(LocalDateTime value) {
		MFPStatusDate = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
