//
// Translated by CS2J (http://www.cs2j.com): 12/14/2020 11:46:28 AM
//

package com.deloitteinnovation.us.hbx.edbc.eligibility.driver.model;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



//------------------------------------------------------------------------------// <auto-generated>//    This code was generated from a template.////    Manual changes to this file may cause unexpected behavior in your application.//    Manual changes to this file will be overwritten if the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public class StatusOfHouseholdCompositionSummaryModel {

	private int StatusOfHouseholdCompositionSummaryId;

	public int getStatusOfHouseholdCompositionSummaryId() {
		return StatusOfHouseholdCompositionSummaryId;
	}

	public void setStatusOfHouseholdCompositionSummaryId(int value) {
		StatusOfHouseholdCompositionSummaryId = value;
	}

	private Integer CaseNumber;

	public Integer getCaseNumber() {
		return CaseNumber;
	}

	public void setCaseNumber(Integer value) {
		CaseNumber = value;
	}

	 private LocalDateTime CreateDate;

	public LocalDateTime getCreateDate() {
		return CreateDate;
	}

	public void setCreateDate(LocalDateTime value) {
		CreateDate = value;
	}

	private String CreateUserId = "";

	public String getCreateUserId() {
		return CreateUserId;
	}

	public void setCreateUserId(String value) {
		CreateUserId = value;
	}

	private byte[] RowVersionStamp;

	public byte[] getRowVersionStamp() {
		return RowVersionStamp;
	}

	public void setRowVersionStamp(byte[] value) {
		RowVersionStamp = value;
	}

	private String StatusOfHouseholdCompositionVerificationCode = "";

	public String getStatusOfHouseholdCompositionVerificationCode() {
		return StatusOfHouseholdCompositionVerificationCode;
	}

	public void setStatusOfHouseholdCompositionVerificationCode(String value) {
		StatusOfHouseholdCompositionVerificationCode = value;
	}

	 private LocalDateTime StatusOfHouseholdCompositionVerificationDate;

	public LocalDateTime getStatusOfHouseholdCompositionVerificationDate() {
		return StatusOfHouseholdCompositionVerificationDate;
	}

	public void setStatusOfHouseholdCompositionVerificationDate(LocalDateTime value) {
		StatusOfHouseholdCompositionVerificationDate = value;
	}

	 private LocalDateTime UpdateDate;

	public LocalDateTime getUpdateDate() {
		return UpdateDate;
	}

	public void setUpdateDate(LocalDateTime value) {
		UpdateDate = value;
	}

	private String UpdateUserId = "";

	public String getUpdateUserId() {
		return UpdateUserId;
	}

	public void setUpdateUserId(String value) {
		UpdateUserId = value;
	}

}
