//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.01 at 11:05:18 PM IST 
//


package com.deloitteinnovation.us.hbx.enrollment.specialenrollment.driver.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for entity_individualInstanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entity_individualInstanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="in_boolean_individual_enrolled_QHP" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}booleanAttributeType" minOccurs="0"/>
 *         &lt;element name="in_number_individual_newEligibilityEnumValue" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}numberAttributeType" minOccurs="0"/>
 *         &lt;element name="in_number_individual_oldEligibilityEnumValue" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}numberAttributeType" minOccurs="0"/>
 *         &lt;element name="in_number_individual_randomNumber" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}numberAttributeType" minOccurs="0"/>
 *         &lt;element name="in_text_individual_dentalEligibility" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}textAttributeType" minOccurs="0"/>
 *         &lt;element name="in_text_individual_name" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}textAttributeType" minOccurs="0"/>
 *         &lt;element name="in_text_individual_newEligibility" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}textAttributeType" minOccurs="0"/>
 *         &lt;element name="in_text_individual_oldEligibility" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}textAttributeType" minOccurs="0"/>
 *         &lt;element name="out_boolean_individual_disenrollmentDeterminedBy23rdRule" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}booleanAttributeType" minOccurs="0"/>
 *         &lt;element name="out_boolean_individual_enrollmentDeterminedBy23rdRule" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}booleanAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_APTCDisenrollment" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_APTCEnrollment" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_dentalEligibilityEndDate" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_dentalEligibilityEndDateHousehold" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_dentalEligibilityStartDate" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_dentalEligibilityStartDateHousehold" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_disenrollmentDateIfDifferentPlanIsSelected" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_disenrollmentDateIfDifferentPlanIsSelectedHousehold" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_disenrollmentDateIfNoPlanIsSelected" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_disenrollmentDateIfNoPlanIsSelectedHousehold" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_disenrollmentDateIfSamePlanIsSelected" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_disenrollmentDateIfSamePlanIsSelectedHousehold" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_earliestEligibleEventChange" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_enrollmentDateIfDifferentPlanIsSelected" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_enrollmentDateIfDifferentPlanIsSelectedHousehold" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_enrollmentDateIfNoPlanIsSelected" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_enrollmentDateIfNoPlanIsSelectedHousehold" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_enrollmentDateIfSamePlanIsSelected" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_enrollmentDateIfSamePlanIsSelectedHousehold" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_latestEventChangeDateWithinEligibleTimeframe" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_lifeEventChangeCategory" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}textAttributeType" minOccurs="0"/>
 *         &lt;element name="out_date_individual_lifeEventChangeDate" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}dateAttributeType" minOccurs="0"/>
 *         &lt;element name="out_text_individual_APTCEligibilityDate" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}textAttributeType" minOccurs="0"/>
 *         &lt;element name="out_text_individual_QHPEligibilityDate" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}textAttributeType" minOccurs="0"/>
 *         &lt;element name="out_text_individual_lifeEventChange" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}textAttributeType" minOccurs="0"/>
 *         &lt;element name="out_text_individual_lifeEventChangeBasis" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}textAttributeType" minOccurs="0"/>
 *         &lt;element name="relationships" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="list-lifeeventchange" type="{http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema}lifeeventchangeEntityListType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entity_individualInstanceType", propOrder = {

})
public class EntityIndividualInstanceType {

    @XmlElement(name = "in_boolean_individual_enrolled_QHP")
    protected BooleanAttributeType inBooleanIndividualEnrolledQHP;
    @XmlElement(name = "in_number_individual_newEligibilityEnumValue")
    protected NumberAttributeType inNumberIndividualNewEligibilityEnumValue;
    @XmlElement(name = "in_number_individual_oldEligibilityEnumValue")
    protected NumberAttributeType inNumberIndividualOldEligibilityEnumValue;
    @XmlElement(name = "in_number_individual_randomNumber")
    protected NumberAttributeType inNumberIndividualRandomNumber;
    @XmlElement(name = "in_text_individual_dentalEligibility")
    protected TextAttributeType inTextIndividualDentalEligibility;
    @XmlElement(name = "in_text_individual_name")
    protected TextAttributeType inTextIndividualName;
    @XmlElement(name = "in_text_individual_newEligibility")
    protected TextAttributeType inTextIndividualNewEligibility;
    @XmlElement(name = "in_text_individual_oldEligibility")
    protected TextAttributeType inTextIndividualOldEligibility;
    @XmlElement(name = "out_boolean_individual_disenrollmentDeterminedBy23rdRule")
    protected BooleanAttributeType outBooleanIndividualDisenrollmentDeterminedBy23RdRule;
    @XmlElement(name = "out_boolean_individual_enrollmentDeterminedBy23rdRule")
    protected BooleanAttributeType outBooleanIndividualEnrollmentDeterminedBy23RdRule;
    @XmlElement(name = "out_date_individual_APTCDisenrollment")
    protected DateAttributeType outDateIndividualAPTCDisenrollment;
    @XmlElement(name = "out_date_individual_APTCEnrollment")
    protected DateAttributeType outDateIndividualAPTCEnrollment;
    @XmlElement(name = "out_date_individual_dentalEligibilityEndDate")
    protected DateAttributeType outDateIndividualDentalEligibilityEndDate;
    @XmlElement(name = "out_date_individual_dentalEligibilityEndDateHousehold")
    protected DateAttributeType outDateIndividualDentalEligibilityEndDateHousehold;
    @XmlElement(name = "out_date_individual_dentalEligibilityStartDate")
    protected DateAttributeType outDateIndividualDentalEligibilityStartDate;
    @XmlElement(name = "out_date_individual_dentalEligibilityStartDateHousehold")
    protected DateAttributeType outDateIndividualDentalEligibilityStartDateHousehold;
    @XmlElement(name = "out_date_individual_disenrollmentDateIfDifferentPlanIsSelected")
    protected DateAttributeType outDateIndividualDisenrollmentDateIfDifferentPlanIsSelected;
    @XmlElement(name = "out_date_individual_disenrollmentDateIfDifferentPlanIsSelectedHousehold")
    protected DateAttributeType outDateIndividualDisenrollmentDateIfDifferentPlanIsSelectedHousehold;
    @XmlElement(name = "out_date_individual_disenrollmentDateIfNoPlanIsSelected")
    protected DateAttributeType outDateIndividualDisenrollmentDateIfNoPlanIsSelected;
    @XmlElement(name = "out_date_individual_disenrollmentDateIfNoPlanIsSelectedHousehold")
    protected DateAttributeType outDateIndividualDisenrollmentDateIfNoPlanIsSelectedHousehold;
    @XmlElement(name = "out_date_individual_disenrollmentDateIfSamePlanIsSelected")
    protected DateAttributeType outDateIndividualDisenrollmentDateIfSamePlanIsSelected;
    @XmlElement(name = "out_date_individual_disenrollmentDateIfSamePlanIsSelectedHousehold")
    protected DateAttributeType outDateIndividualDisenrollmentDateIfSamePlanIsSelectedHousehold;
    @XmlElement(name = "out_date_individual_earliestEligibleEventChange")
    protected DateAttributeType outDateIndividualEarliestEligibleEventChange;
    @XmlElement(name = "out_date_individual_enrollmentDateIfDifferentPlanIsSelected")
    protected DateAttributeType outDateIndividualEnrollmentDateIfDifferentPlanIsSelected;
    @XmlElement(name = "out_date_individual_enrollmentDateIfDifferentPlanIsSelectedHousehold")
    protected DateAttributeType outDateIndividualEnrollmentDateIfDifferentPlanIsSelectedHousehold;
    @XmlElement(name = "out_date_individual_enrollmentDateIfNoPlanIsSelected")
    protected DateAttributeType outDateIndividualEnrollmentDateIfNoPlanIsSelected;
    @XmlElement(name = "out_date_individual_enrollmentDateIfNoPlanIsSelectedHousehold")
    protected DateAttributeType outDateIndividualEnrollmentDateIfNoPlanIsSelectedHousehold;
    @XmlElement(name = "out_date_individual_enrollmentDateIfSamePlanIsSelected")
    protected DateAttributeType outDateIndividualEnrollmentDateIfSamePlanIsSelected;
    @XmlElement(name = "out_date_individual_enrollmentDateIfSamePlanIsSelectedHousehold")
    protected DateAttributeType outDateIndividualEnrollmentDateIfSamePlanIsSelectedHousehold;
    @XmlElement(name = "out_date_individual_latestEventChangeDateWithinEligibleTimeframe")
    protected DateAttributeType outDateIndividualLatestEventChangeDateWithinEligibleTimeframe;
    @XmlElement(name = "out_date_individual_lifeEventChangeCategory")
    protected TextAttributeType outDateIndividualLifeEventChangeCategory;
    @XmlElement(name = "out_date_individual_lifeEventChangeDate")
    protected DateAttributeType outDateIndividualLifeEventChangeDate;
    @XmlElement(name = "out_text_individual_APTCEligibilityDate")
    protected TextAttributeType outTextIndividualAPTCEligibilityDate;
    @XmlElement(name = "out_text_individual_QHPEligibilityDate")
    protected TextAttributeType outTextIndividualQHPEligibilityDate;
    @XmlElement(name = "out_text_individual_lifeEventChange")
    protected TextAttributeType outTextIndividualLifeEventChange;
    @XmlElement(name = "out_text_individual_lifeEventChangeBasis")
    protected TextAttributeType outTextIndividualLifeEventChangeBasis;
    protected EntityIndividualInstanceType.Relationships relationships;
    @XmlElement(name = "list-lifeeventchange")
    protected LifeeventchangeEntityListType listLifeeventchange;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the inBooleanIndividualEnrolledQHP property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanAttributeType }
     *     
     */
    public BooleanAttributeType getInBooleanIndividualEnrolledQHP() {
        return inBooleanIndividualEnrolledQHP;
    }

    /**
     * Sets the value of the inBooleanIndividualEnrolledQHP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanAttributeType }
     *     
     */
    public void setInBooleanIndividualEnrolledQHP(BooleanAttributeType value) {
        this.inBooleanIndividualEnrolledQHP = value;
    }

    /**
     * Gets the value of the inNumberIndividualNewEligibilityEnumValue property.
     * 
     * @return
     *     possible object is
     *     {@link NumberAttributeType }
     *     
     */
    public NumberAttributeType getInNumberIndividualNewEligibilityEnumValue() {
        return inNumberIndividualNewEligibilityEnumValue;
    }

    /**
     * Sets the value of the inNumberIndividualNewEligibilityEnumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberAttributeType }
     *     
     */
    public void setInNumberIndividualNewEligibilityEnumValue(NumberAttributeType value) {
        this.inNumberIndividualNewEligibilityEnumValue = value;
    }

    /**
     * Gets the value of the inNumberIndividualOldEligibilityEnumValue property.
     * 
     * @return
     *     possible object is
     *     {@link NumberAttributeType }
     *     
     */
    public NumberAttributeType getInNumberIndividualOldEligibilityEnumValue() {
        return inNumberIndividualOldEligibilityEnumValue;
    }

    /**
     * Sets the value of the inNumberIndividualOldEligibilityEnumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberAttributeType }
     *     
     */
    public void setInNumberIndividualOldEligibilityEnumValue(NumberAttributeType value) {
        this.inNumberIndividualOldEligibilityEnumValue = value;
    }

    /**
     * Gets the value of the inNumberIndividualRandomNumber property.
     * 
     * @return
     *     possible object is
     *     {@link NumberAttributeType }
     *     
     */
    public NumberAttributeType getInNumberIndividualRandomNumber() {
        return inNumberIndividualRandomNumber;
    }

    /**
     * Sets the value of the inNumberIndividualRandomNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberAttributeType }
     *     
     */
    public void setInNumberIndividualRandomNumber(NumberAttributeType value) {
        this.inNumberIndividualRandomNumber = value;
    }

    /**
     * Gets the value of the inTextIndividualDentalEligibility property.
     * 
     * @return
     *     possible object is
     *     {@link TextAttributeType }
     *     
     */
    public TextAttributeType getInTextIndividualDentalEligibility() {
        return inTextIndividualDentalEligibility;
    }

    /**
     * Sets the value of the inTextIndividualDentalEligibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextAttributeType }
     *     
     */
    public void setInTextIndividualDentalEligibility(TextAttributeType value) {
        this.inTextIndividualDentalEligibility = value;
    }

    /**
     * Gets the value of the inTextIndividualName property.
     * 
     * @return
     *     possible object is
     *     {@link TextAttributeType }
     *     
     */
    public TextAttributeType getInTextIndividualName() {
        return inTextIndividualName;
    }

    /**
     * Sets the value of the inTextIndividualName property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextAttributeType }
     *     
     */
    public void setInTextIndividualName(TextAttributeType value) {
        this.inTextIndividualName = value;
    }

    /**
     * Gets the value of the inTextIndividualNewEligibility property.
     * 
     * @return
     *     possible object is
     *     {@link TextAttributeType }
     *     
     */
    public TextAttributeType getInTextIndividualNewEligibility() {
        return inTextIndividualNewEligibility;
    }

    /**
     * Sets the value of the inTextIndividualNewEligibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextAttributeType }
     *     
     */
    public void setInTextIndividualNewEligibility(TextAttributeType value) {
        this.inTextIndividualNewEligibility = value;
    }

    /**
     * Gets the value of the inTextIndividualOldEligibility property.
     * 
     * @return
     *     possible object is
     *     {@link TextAttributeType }
     *     
     */
    public TextAttributeType getInTextIndividualOldEligibility() {
        return inTextIndividualOldEligibility;
    }

    /**
     * Sets the value of the inTextIndividualOldEligibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextAttributeType }
     *     
     */
    public void setInTextIndividualOldEligibility(TextAttributeType value) {
        this.inTextIndividualOldEligibility = value;
    }

    /**
     * Gets the value of the outBooleanIndividualDisenrollmentDeterminedBy23RdRule property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanAttributeType }
     *     
     */
    public BooleanAttributeType getOutBooleanIndividualDisenrollmentDeterminedBy23RdRule() {
        return outBooleanIndividualDisenrollmentDeterminedBy23RdRule;
    }

    /**
     * Sets the value of the outBooleanIndividualDisenrollmentDeterminedBy23RdRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanAttributeType }
     *     
     */
    public void setOutBooleanIndividualDisenrollmentDeterminedBy23RdRule(BooleanAttributeType value) {
        this.outBooleanIndividualDisenrollmentDeterminedBy23RdRule = value;
    }

    /**
     * Gets the value of the outBooleanIndividualEnrollmentDeterminedBy23RdRule property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanAttributeType }
     *     
     */
    public BooleanAttributeType getOutBooleanIndividualEnrollmentDeterminedBy23RdRule() {
        return outBooleanIndividualEnrollmentDeterminedBy23RdRule;
    }

    /**
     * Sets the value of the outBooleanIndividualEnrollmentDeterminedBy23RdRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanAttributeType }
     *     
     */
    public void setOutBooleanIndividualEnrollmentDeterminedBy23RdRule(BooleanAttributeType value) {
        this.outBooleanIndividualEnrollmentDeterminedBy23RdRule = value;
    }

    /**
     * Gets the value of the outDateIndividualAPTCDisenrollment property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualAPTCDisenrollment() {
        return outDateIndividualAPTCDisenrollment;
    }

    /**
     * Sets the value of the outDateIndividualAPTCDisenrollment property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualAPTCDisenrollment(DateAttributeType value) {
        this.outDateIndividualAPTCDisenrollment = value;
    }

    /**
     * Gets the value of the outDateIndividualAPTCEnrollment property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualAPTCEnrollment() {
        return outDateIndividualAPTCEnrollment;
    }

    /**
     * Sets the value of the outDateIndividualAPTCEnrollment property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualAPTCEnrollment(DateAttributeType value) {
        this.outDateIndividualAPTCEnrollment = value;
    }

    /**
     * Gets the value of the outDateIndividualDentalEligibilityEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualDentalEligibilityEndDate() {
        return outDateIndividualDentalEligibilityEndDate;
    }

    /**
     * Sets the value of the outDateIndividualDentalEligibilityEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualDentalEligibilityEndDate(DateAttributeType value) {
        this.outDateIndividualDentalEligibilityEndDate = value;
    }

    /**
     * Gets the value of the outDateIndividualDentalEligibilityEndDateHousehold property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualDentalEligibilityEndDateHousehold() {
        return outDateIndividualDentalEligibilityEndDateHousehold;
    }

    /**
     * Sets the value of the outDateIndividualDentalEligibilityEndDateHousehold property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualDentalEligibilityEndDateHousehold(DateAttributeType value) {
        this.outDateIndividualDentalEligibilityEndDateHousehold = value;
    }

    /**
     * Gets the value of the outDateIndividualDentalEligibilityStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualDentalEligibilityStartDate() {
        return outDateIndividualDentalEligibilityStartDate;
    }

    /**
     * Sets the value of the outDateIndividualDentalEligibilityStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualDentalEligibilityStartDate(DateAttributeType value) {
        this.outDateIndividualDentalEligibilityStartDate = value;
    }

    /**
     * Gets the value of the outDateIndividualDentalEligibilityStartDateHousehold property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualDentalEligibilityStartDateHousehold() {
        return outDateIndividualDentalEligibilityStartDateHousehold;
    }

    /**
     * Sets the value of the outDateIndividualDentalEligibilityStartDateHousehold property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualDentalEligibilityStartDateHousehold(DateAttributeType value) {
        this.outDateIndividualDentalEligibilityStartDateHousehold = value;
    }

    /**
     * Gets the value of the outDateIndividualDisenrollmentDateIfDifferentPlanIsSelected property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualDisenrollmentDateIfDifferentPlanIsSelected() {
        return outDateIndividualDisenrollmentDateIfDifferentPlanIsSelected;
    }

    /**
     * Sets the value of the outDateIndividualDisenrollmentDateIfDifferentPlanIsSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualDisenrollmentDateIfDifferentPlanIsSelected(DateAttributeType value) {
        this.outDateIndividualDisenrollmentDateIfDifferentPlanIsSelected = value;
    }

    /**
     * Gets the value of the outDateIndividualDisenrollmentDateIfDifferentPlanIsSelectedHousehold property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualDisenrollmentDateIfDifferentPlanIsSelectedHousehold() {
        return outDateIndividualDisenrollmentDateIfDifferentPlanIsSelectedHousehold;
    }

    /**
     * Sets the value of the outDateIndividualDisenrollmentDateIfDifferentPlanIsSelectedHousehold property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualDisenrollmentDateIfDifferentPlanIsSelectedHousehold(DateAttributeType value) {
        this.outDateIndividualDisenrollmentDateIfDifferentPlanIsSelectedHousehold = value;
    }

    /**
     * Gets the value of the outDateIndividualDisenrollmentDateIfNoPlanIsSelected property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualDisenrollmentDateIfNoPlanIsSelected() {
        return outDateIndividualDisenrollmentDateIfNoPlanIsSelected;
    }

    /**
     * Sets the value of the outDateIndividualDisenrollmentDateIfNoPlanIsSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualDisenrollmentDateIfNoPlanIsSelected(DateAttributeType value) {
        this.outDateIndividualDisenrollmentDateIfNoPlanIsSelected = value;
    }

    /**
     * Gets the value of the outDateIndividualDisenrollmentDateIfNoPlanIsSelectedHousehold property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualDisenrollmentDateIfNoPlanIsSelectedHousehold() {
        return outDateIndividualDisenrollmentDateIfNoPlanIsSelectedHousehold;
    }

    /**
     * Sets the value of the outDateIndividualDisenrollmentDateIfNoPlanIsSelectedHousehold property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualDisenrollmentDateIfNoPlanIsSelectedHousehold(DateAttributeType value) {
        this.outDateIndividualDisenrollmentDateIfNoPlanIsSelectedHousehold = value;
    }

    /**
     * Gets the value of the outDateIndividualDisenrollmentDateIfSamePlanIsSelected property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualDisenrollmentDateIfSamePlanIsSelected() {
        return outDateIndividualDisenrollmentDateIfSamePlanIsSelected;
    }

    /**
     * Sets the value of the outDateIndividualDisenrollmentDateIfSamePlanIsSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualDisenrollmentDateIfSamePlanIsSelected(DateAttributeType value) {
        this.outDateIndividualDisenrollmentDateIfSamePlanIsSelected = value;
    }

    /**
     * Gets the value of the outDateIndividualDisenrollmentDateIfSamePlanIsSelectedHousehold property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualDisenrollmentDateIfSamePlanIsSelectedHousehold() {
        return outDateIndividualDisenrollmentDateIfSamePlanIsSelectedHousehold;
    }

    /**
     * Sets the value of the outDateIndividualDisenrollmentDateIfSamePlanIsSelectedHousehold property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualDisenrollmentDateIfSamePlanIsSelectedHousehold(DateAttributeType value) {
        this.outDateIndividualDisenrollmentDateIfSamePlanIsSelectedHousehold = value;
    }

    /**
     * Gets the value of the outDateIndividualEarliestEligibleEventChange property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualEarliestEligibleEventChange() {
        return outDateIndividualEarliestEligibleEventChange;
    }

    /**
     * Sets the value of the outDateIndividualEarliestEligibleEventChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualEarliestEligibleEventChange(DateAttributeType value) {
        this.outDateIndividualEarliestEligibleEventChange = value;
    }

    /**
     * Gets the value of the outDateIndividualEnrollmentDateIfDifferentPlanIsSelected property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualEnrollmentDateIfDifferentPlanIsSelected() {
        return outDateIndividualEnrollmentDateIfDifferentPlanIsSelected;
    }

    /**
     * Sets the value of the outDateIndividualEnrollmentDateIfDifferentPlanIsSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualEnrollmentDateIfDifferentPlanIsSelected(DateAttributeType value) {
        this.outDateIndividualEnrollmentDateIfDifferentPlanIsSelected = value;
    }

    /**
     * Gets the value of the outDateIndividualEnrollmentDateIfDifferentPlanIsSelectedHousehold property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualEnrollmentDateIfDifferentPlanIsSelectedHousehold() {
        return outDateIndividualEnrollmentDateIfDifferentPlanIsSelectedHousehold;
    }

    /**
     * Sets the value of the outDateIndividualEnrollmentDateIfDifferentPlanIsSelectedHousehold property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualEnrollmentDateIfDifferentPlanIsSelectedHousehold(DateAttributeType value) {
        this.outDateIndividualEnrollmentDateIfDifferentPlanIsSelectedHousehold = value;
    }

    /**
     * Gets the value of the outDateIndividualEnrollmentDateIfNoPlanIsSelected property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualEnrollmentDateIfNoPlanIsSelected() {
        return outDateIndividualEnrollmentDateIfNoPlanIsSelected;
    }

    /**
     * Sets the value of the outDateIndividualEnrollmentDateIfNoPlanIsSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualEnrollmentDateIfNoPlanIsSelected(DateAttributeType value) {
        this.outDateIndividualEnrollmentDateIfNoPlanIsSelected = value;
    }

    /**
     * Gets the value of the outDateIndividualEnrollmentDateIfNoPlanIsSelectedHousehold property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualEnrollmentDateIfNoPlanIsSelectedHousehold() {
        return outDateIndividualEnrollmentDateIfNoPlanIsSelectedHousehold;
    }

    /**
     * Sets the value of the outDateIndividualEnrollmentDateIfNoPlanIsSelectedHousehold property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualEnrollmentDateIfNoPlanIsSelectedHousehold(DateAttributeType value) {
        this.outDateIndividualEnrollmentDateIfNoPlanIsSelectedHousehold = value;
    }

    /**
     * Gets the value of the outDateIndividualEnrollmentDateIfSamePlanIsSelected property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualEnrollmentDateIfSamePlanIsSelected() {
        return outDateIndividualEnrollmentDateIfSamePlanIsSelected;
    }

    /**
     * Sets the value of the outDateIndividualEnrollmentDateIfSamePlanIsSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualEnrollmentDateIfSamePlanIsSelected(DateAttributeType value) {
        this.outDateIndividualEnrollmentDateIfSamePlanIsSelected = value;
    }

    /**
     * Gets the value of the outDateIndividualEnrollmentDateIfSamePlanIsSelectedHousehold property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualEnrollmentDateIfSamePlanIsSelectedHousehold() {
        return outDateIndividualEnrollmentDateIfSamePlanIsSelectedHousehold;
    }

    /**
     * Sets the value of the outDateIndividualEnrollmentDateIfSamePlanIsSelectedHousehold property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualEnrollmentDateIfSamePlanIsSelectedHousehold(DateAttributeType value) {
        this.outDateIndividualEnrollmentDateIfSamePlanIsSelectedHousehold = value;
    }

    /**
     * Gets the value of the outDateIndividualLatestEventChangeDateWithinEligibleTimeframe property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualLatestEventChangeDateWithinEligibleTimeframe() {
        return outDateIndividualLatestEventChangeDateWithinEligibleTimeframe;
    }

    /**
     * Sets the value of the outDateIndividualLatestEventChangeDateWithinEligibleTimeframe property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualLatestEventChangeDateWithinEligibleTimeframe(DateAttributeType value) {
        this.outDateIndividualLatestEventChangeDateWithinEligibleTimeframe = value;
    }

    /**
     * Gets the value of the outDateIndividualLifeEventChangeCategory property.
     * 
     * @return
     *     possible object is
     *     {@link TextAttributeType }
     *     
     */
    public TextAttributeType getOutDateIndividualLifeEventChangeCategory() {
        return outDateIndividualLifeEventChangeCategory;
    }

    /**
     * Sets the value of the outDateIndividualLifeEventChangeCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextAttributeType }
     *     
     */
    public void setOutDateIndividualLifeEventChangeCategory(TextAttributeType value) {
        this.outDateIndividualLifeEventChangeCategory = value;
    }

    /**
     * Gets the value of the outDateIndividualLifeEventChangeDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateAttributeType }
     *     
     */
    public DateAttributeType getOutDateIndividualLifeEventChangeDate() {
        return outDateIndividualLifeEventChangeDate;
    }

    /**
     * Sets the value of the outDateIndividualLifeEventChangeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAttributeType }
     *     
     */
    public void setOutDateIndividualLifeEventChangeDate(DateAttributeType value) {
        this.outDateIndividualLifeEventChangeDate = value;
    }

    /**
     * Gets the value of the outTextIndividualAPTCEligibilityDate property.
     * 
     * @return
     *     possible object is
     *     {@link TextAttributeType }
     *     
     */
    public TextAttributeType getOutTextIndividualAPTCEligibilityDate() {
        return outTextIndividualAPTCEligibilityDate;
    }

    /**
     * Sets the value of the outTextIndividualAPTCEligibilityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextAttributeType }
     *     
     */
    public void setOutTextIndividualAPTCEligibilityDate(TextAttributeType value) {
        this.outTextIndividualAPTCEligibilityDate = value;
    }

    /**
     * Gets the value of the outTextIndividualQHPEligibilityDate property.
     * 
     * @return
     *     possible object is
     *     {@link TextAttributeType }
     *     
     */
    public TextAttributeType getOutTextIndividualQHPEligibilityDate() {
        return outTextIndividualQHPEligibilityDate;
    }

    /**
     * Sets the value of the outTextIndividualQHPEligibilityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextAttributeType }
     *     
     */
    public void setOutTextIndividualQHPEligibilityDate(TextAttributeType value) {
        this.outTextIndividualQHPEligibilityDate = value;
    }

    /**
     * Gets the value of the outTextIndividualLifeEventChange property.
     * 
     * @return
     *     possible object is
     *     {@link TextAttributeType }
     *     
     */
    public TextAttributeType getOutTextIndividualLifeEventChange() {
        return outTextIndividualLifeEventChange;
    }

    /**
     * Sets the value of the outTextIndividualLifeEventChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextAttributeType }
     *     
     */
    public void setOutTextIndividualLifeEventChange(TextAttributeType value) {
        this.outTextIndividualLifeEventChange = value;
    }

    /**
     * Gets the value of the outTextIndividualLifeEventChangeBasis property.
     * 
     * @return
     *     possible object is
     *     {@link TextAttributeType }
     *     
     */
    public TextAttributeType getOutTextIndividualLifeEventChangeBasis() {
        return outTextIndividualLifeEventChangeBasis;
    }

    /**
     * Sets the value of the outTextIndividualLifeEventChangeBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextAttributeType }
     *     
     */
    public void setOutTextIndividualLifeEventChangeBasis(TextAttributeType value) {
        this.outTextIndividualLifeEventChangeBasis = value;
    }

    /**
     * Gets the value of the relationships property.
     * 
     * @return
     *     possible object is
     *     {@link EntityIndividualInstanceType.Relationships }
     *     
     */
    public EntityIndividualInstanceType.Relationships getRelationships() {
        return relationships;
    }

    /**
     * Sets the value of the relationships property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityIndividualInstanceType.Relationships }
     *     
     */
    public void setRelationships(EntityIndividualInstanceType.Relationships value) {
        this.relationships = value;
    }

    /**
     * Gets the value of the listLifeeventchange property.
     * 
     * @return
     *     possible object is
     *     {@link LifeeventchangeEntityListType }
     *     
     */
    public LifeeventchangeEntityListType getListLifeeventchange() {
        return listLifeeventchange;
    }

    /**
     * Sets the value of the listLifeeventchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifeeventchangeEntityListType }
     *     
     */
    public void setListLifeeventchange(LifeeventchangeEntityListType value) {
        this.listLifeeventchange = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Relationships {


    }

}
