//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.01 at 11:05:18 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxspecialenrollmentservice/schema")
package com.deloitteinnovation.us.hbx.enrollment.specialenrollment.driver.service;
