//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.10 at 03:28:34 PM IST 
//


package com.deloitteinnovation.us.hbx.edbc.documentrequest.driver.service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DecisionReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecisionReportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="relationship-node" type="{http://hbx.us.deloitteinnovation.com/ws/hbxdocumentrequestservice/schema}RelationshipNodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="attribute-node" type="{http://hbx.us.deloitteinnovation.com/ws/hbxdocumentrequestservice/schema}AttributeNodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="already-proven-node" type="{http://hbx.us.deloitteinnovation.com/ws/hbxdocumentrequestservice/schema}AlreadyProvenNodeType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="report-style" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecisionReportType", namespace = "http://hbx.us.deloitteinnovation.com/ws/hbxdocumentrequestservice/schema", propOrder = {
    "relationshipNodeOrAttributeNodeOrAlreadyProvenNode"
})
public class DecisionReportType {

    @XmlElements({
        @XmlElement(name = "relationship-node", type = RelationshipNodeType.class),
        @XmlElement(name = "attribute-node", type = AttributeNodeType.class),
        @XmlElement(name = "already-proven-node", type = AlreadyProvenNodeType.class)
    })
    protected List<Object> relationshipNodeOrAttributeNodeOrAlreadyProvenNode;
    @XmlAttribute(name = "report-style")
    protected String reportStyle;

    /**
     * Gets the value of the relationshipNodeOrAttributeNodeOrAlreadyProvenNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relationshipNodeOrAttributeNodeOrAlreadyProvenNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelationshipNodeOrAttributeNodeOrAlreadyProvenNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationshipNodeType }
     * {@link AttributeNodeType }
     * {@link AlreadyProvenNodeType }
     * 
     * 
     */
    public List<Object> getRelationshipNodeOrAttributeNodeOrAlreadyProvenNode() {
        if (relationshipNodeOrAttributeNodeOrAlreadyProvenNode == null) {
            relationshipNodeOrAttributeNodeOrAlreadyProvenNode = new ArrayList<Object>();
        }
        return this.relationshipNodeOrAttributeNodeOrAlreadyProvenNode;
    }

    /**
     * Gets the value of the reportStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportStyle() {
        return reportStyle;
    }

    /**
     * Sets the value of the reportStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportStyle(String value) {
        this.reportStyle = value;
    }

}
